idol/src/User/UserBase/UserBase.tsx, idol/src/User/UserProfile/UserProfile.lazy.tsx, idol/src/User/UserProfile/UserProfile.test.tsx, idol/src/User/UserProfile/UserProfile.tsx
This pull request is the first step towards implementing the member info form that allows a user to change their information on DTI's website. Log in to IDOL, navigate to Users > Edit Profile to access the form.
  
 
Currently no unit tests 
I created a dummy user to fill in the form information,  but the next step is to connect with the backend in order to retrieve actual user information from the database.
Optional fields, such as double major and minor, are currently set as empty strings. In the database, these are stored as null , so we will need to decide how to handle this situation.
=> implemented member info form

idol/src/API/MembersAPI.ts, idol/src/User/AddUser/AddUser.tsx, idol/src/User/UserBase/UserBase.tsx, idol/src/User/UserProfile/UserProfile.lazy.tsx, idol/src/User/UserProfile/UserProfile.test.tsx, idol/src/User/UserProfile/UserProfile.tsx
This pull request is the next step towards implementing the member info form that allows a user to change their information on DTI's website. Log in to IDOL, navigate to Users > Edit Profile to access the form.
 
Still having issues with null/undefined. The Member type had fields like minor, double major, etc. as optional, but they are stored as null in the database. I changed the types of these fields in Member on the frontend to be string | null so that the updated user object conforms to the Member type, but now the Member type for backend and frontend don’t match. In the future, we need to figure out if we want to store null or empty strings in firebase.
=> Connected member form to backend

README.md
=> Add Spring 2021 devs

frontend/package.json, frontend/src/API/LoginAPI.ts, frontend/src/API/MembersAPI.ts, frontend/src/API/RolesAPI.ts, frontend/src/API/TeamsAPI.ts, frontend/src/environment.ts
This PR leverages the config from create-react-app to make frontend dev experience better.
Check preview site to ensure that the site can still load and login.
=> Simplify frontend environment config

backend/src/api.ts, backend/src/dao/TeamsDao.ts
I just fixed the issue with the teams page not loading. 
Edit teams page should not have "spinning wheel of doom" anymore.
=> Fix issue with teams page not loading

backend/src/api.ts, backend/src/memberAPI.ts, frontend/src/API/APIWrapper.ts, frontend/src/API/MembersAPI.ts
Fixed issue with not being able to delete users from edit users page. 
Should be able to successfully delete users now.
=> fix issue with deleting members

backend/data/firebase.ts, backend/data/run.ts, backend/src/DataTypes.d.ts, frontend/src/API/MembersAPI.ts, frontend/src/User/AddUser/AddUser.tsx, frontend/src/User/EditTeam/EditTeam.tsx, frontend/src/User/UserProfile/UserProfile.tsx
This pull request updates the `member` and `role` data types for IDOL to match Nova's member jsons. The existing documents in the firebase are also updated to reflect the same changes.
- Consider sharing .d.ts files with frontend for data type consistency
- Updated `Member` type: Check and update any frontend functionality for the same.
=> Update IDOL Data Types to Match Nova

backend/package.json, backend/src/DataTypes.d.ts, backend/src/permissions.ts, backend/src/types.d.ts, common-types/index.d.ts, common-types/package.json, dti-website/package.json, dti-website/src/types.d.ts, frontend/package.json, frontend/src/API/MembersAPI.ts, frontend/src/API/RolesAPI.ts, frontend/src/User/AddUser/AddUser.tsx, frontend/src/User/UserProfile/UserProfile.tsx, frontend/src/react-app-env.d.ts, frontend/src/utils.ts, package.json
Currently the idol type is still inconsistent with the nova type. However, since we are now in a monorepo, we can start to tweak the nova type to be closer to idol type.
This is a type only change, so check CI to ensure no errors.
=> Setup common types between frontend, backend, and nova

README.md
This pull request adds my name to the list of contributors in the IDOL README.
=> Add contributor to README

common-types/package.json, dti-website/next-env.d.ts, dti-website/src/components/HeadshotGrid.tsx, dti-website/src/components/MemberProfile.tsx, dti-website/src/components/MemberProfileModal.tsx, dti-website/src/components/TeamMembers.tsx, dti-website/src/data/all-members.json, dti-website/src/pages/team.tsx, dti-website/src/types.d.ts
Cleanup the nova workspace to prepare for using script to fetch from idol backend:
- Use the types from common-types
- Tweak json field order to be consistent
It's a type only change plus some json field order change. It should have no runtime effect. Check CI logs to ensure everything still passes.
=> Cleanup nova project to prepare integration

common-types/index.d.ts, dti-website/src/components/MemberProfile.tsx, dti-website/src/data/all-members.json
They are never meaningfully used, since we always have a name field.
Things still type check.
=> [nova] Remove firstName and lastName from member json

backend/src/api.ts, backend/src/imageAPI.ts, backend/src/memberAPI.ts, backend/src/roleAPI.ts, backend/src/teamAPI.ts
Setup the logged in check in one place, so we don't have to check at again at every handler. It can also help remove undefined returns in those endpoints, so we have less linter warnings.
Start frontend and backend to ensure that every endpoint can still work.
The PR will be very to review if you turn on hide whitespace change in github UI:
=> Setup login-checked endpoints

backend/src/permissions.ts, common-types/index.d.ts, frontend/src/User/UserProfile/UserProfile.tsx, frontend/src/utils.ts
Now we have an admin collection, we no longer needs an admin role. This PR removes all of them.
👀
=> Remove all admin role from codebase

.github/workflows/pull-from-idol.yml, dti-website/package.json, dti-website/pull-from-idol.ts, yarn.lock
Add a CI cron job that runs every day. If there is a change in member json, it will commit and create a PR with the change.
See this auto-generated PR: https://github.com/cornell-dti/idol/pull/56
=> Setup a CI cron job to update idol member json

backend/src/api.ts, backend/src/imageAPI.ts, backend/src/memberAPI.ts, backend/src/site-integration.ts, backend/src/teamAPI.ts
Right now, every xxxApiHandler checks whether the member actually exists in database, which is a check that can be easily forgotten by programmers. In addition, every handler parsed information from the request object on its own, which can be error prone.
This PR moves all the logic to `loginCheckedHandler`, which checks the existence of user in db and returns a user object to the handler. Each handler is also provided information relevant to them in typed form, so that all the request object parsing happens in one place: `api.ts`
Start frontend and backend to ensure that every endpoint can still work.
=> Ensure type safety and basic member authorization in loginCheckedHandler

frontend/src/User/Shoutouts/ShoutoutForm/ShoutoutForm.tsx, frontend/src/User/Shoutouts/Shoutouts.tsx, frontend/src/User/UserBase/UserBase.tsx
This pull request is the first step towards implementing the shoutouts page on Idol. The form allows the user to select a DTI member and write a shoutout message.
Currently, the user can only select one member to give a shoutout to. A future consideration is if we would like the user to be able to select multiple members for one shoutout.
=> Shoutout Form

dti-website/next.config.js, dti-website/package.json, dti-website/src/pages/_app.tsx, yarn.lock
=> [dti-website] Fix font size by importing missing scss

image-cli/index.js, image-cli/package.json, package.json, yarn.lock
After this step, the nova repo can be fully archived.
👀
=> Copy over image-cli for compressing images from nova to idol repo

backend/package.json, dti-website/next.config.js, dti-website/package.json, dti-website/src/components/NavItem.tsx, frontend/package.json, frontend/src/API/MembersAPI.ts, frontend/src/User/DTI48/DTI48.module.css, frontend/src/User/DTI48/DTI48.tsx, frontend/src/User/DTI48/DTI48GameCard.module.css, frontend/src/User/DTI48/DTI48GameCard.tsx, frontend/src/User/DTI48/DTI48MainGame.module.css, frontend/src/User/DTI48/DTI48MainGame.tsx, frontend/src/User/DTI48/DTI48ProfileCard.module.css, frontend/src/User/DTI48/DTI48ProfileCard.tsx, frontend/src/User/DTI48/dti48-upgrade-chain.test.ts, frontend/src/User/DTI48/dti48-upgrade-chain.ts, frontend/src/User/DTI48/game-board.ts, frontend/src/User/UserBase/UserBase.tsx, image-cli/package.json, yarn.lock
This PR implements the DTI48 game as proposed in the meeting.
You start as yourself. 2 of you create your manager, 2 of your manager create your manager's manager, etc, until you win by merging together two ops leads.
- Restart game
- Play as another DTI member
Using the following rules:
dev < TPM < @chansen424 < @JBoss925 < @meganyin13 < Ops Lead
design < PM < Product Lead < Ops Lead
business < Ehi < Ops Lead
Design Lead < Ops Lead
This isn't ideal, but we are constrained by the fact that one node can only have one parent, so at some point we make to make decisions like does design belong to PM or design leads. In the future, we can provide customization abilities.
Another issue is how which dev lead to be the parent of all TPMs. I don't have an answer, so I just make an order of dev …
=> DTI48 GAME!

frontend/src/User/DTI48/dti48-upgrade-chain.ts
Currently DAC has APMs. In order to avoid having two parents for designers on DAC, we chain the PMs together like dev leads. Therefore, we will have the chain `designer -> PM 1 -> PM 2 -> Product Lead -> Ops Lead`
`yarn workspace frontend start` still pass. Play with the frontend to check that we have `Andrea Chen -> Ying Yang -> Aram` order.
=> [DTI48] Chaining together PMs to work for APM case

.eslintrc.json, frontend/src/API/PermissionsAPI.ts, frontend/src/Admin/AdminShoutouts/AdminShoutouts.tsx
Make `unused-var` rule error level so that it will always be respected.
👀
=> [easy] Fix linter warnings and strictify config

backend/src/api.ts, backend/src/shoutoutAPI.ts, frontend/src/API/MembersAPI.ts, frontend/src/User/ShoutoutsPage/ShoutoutForm/ShoutoutForm.tsx, frontend/src/User/ShoutoutsPage/ShoutoutsPage.tsx, frontend/src/User/UserProfile/UserProfile.tsx
This should fix (at least mostly) the bug in prod that's causing sessions to randomly time out. Essentially, there were some requests in the shoutouts page that were happening concurrently that I guess were causing the backend to bug. I chained together these requests so that they were no longer happening at the same time. 
On the preview, you should not be randomly logged out as you click around, particularly on the `Shoutouts` and `Edit Profile` pages.
=> Fix session bug

dti-website/src/data/apply.json, dti-website/src/pages/apply.tsx
Implement multiple buttons in Applications section to support this semester's "common app" system.
Update zoom links for info sessions, replacing current placeholder links.
=> Update cornelldti.org Apply page with info session links and new general application

frontend/src/Games/DTI48/DTI48.tsx, frontend/src/Games/DTI48/DTI48MainGame.tsx
Fetch all semesters' data and let user choose. Step 2 of making DTI 48 playable for old members. Next step would be allow old members to log in.
=> [dti48] Allow user to choose a different semester of data

dti-website/src/pages/courses.tsx
Updates trends app link to https://bit.ly/web-dev-fa21
Link works.
=> Update application link for trends fa21

dti-website/src/data/apply.json
Updates info session data to reflect upcoming events.
Made sure the dates + locations + links were accurate.
=> update info session times dates

frontend/src/Admin/AdminBase.tsx, frontend/src/Common/NavigationCard.module.css, frontend/src/Common/NavigationCard.tsx, frontend/src/Forms/FormsBase.module.css, frontend/src/Forms/FormsBase.tsx, frontend/src/Games/GamesBase.module.css, frontend/src/Games/GamesBase.tsx
There are a lot of copy-pasta of duplicated code. I factored them into a single component to help code reuse.
Cards appear as usual:
=> Factor out common nav card code in `XxxBase` components into `NavigationCard`

frontend/src/Common/NavigationCard.tsx
Simple typo fix. It's causing some test warnings.
👀
=> [easy] Fix typo in Card list key

README.md
This pull request adds Fall 2021 contributors to the list in IDOL README.
=> Update Contributers for Fall 2021

.github/workflows/ci-build.yml
Change config so that CI build workflow runs on PR to `release` branch
N/A
=> Add release branch for CI build workflow 

README.md
Added myself to the list of developers for Fall 2021. 
Test nothing broke.
=> Added myself to devs FA21.

frontend/src/components/Admin/SignInFormCreator.tsx, frontend/src/components/Forms/SignInForm/SignInForm.tsx
This pull request is the first step towards implementing the attendance feature. This should fix the current routing error that prevents admins from creating new sign-in forms and users from signing-in.
Tested locally and seems to work
=> Fix routing issues for sign-in forms

dti-website/next.config.js, frontend/next.config.js
It seems to cause some issues with local development.
CI.
=> Disable experimental swc loader

backend/src/permissions.ts
This pull request refactors the permissions manager for backend to avoid duplication of code.
No changes to functionality.
=> Refactor permissions

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/pages/admin/index.tsx, frontend/src/pages/forms/index.tsx
This PR makes the team events pages unstable because they are incomplete.
=> make team events page unstable

.gitignore, frontend/src/components/Admin/AddUser.module.css, frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Common/UserProvider.tsx, frontend/src/pages/_app.tsx
Hide the admin navbar item so users without admin permission won't enter a confusing white page.
Login as non-admin to check.
=> Hide Admin NavItem if the user is not admin

frontend/src/API/MembersAPI.ts, frontend/src/API/TeamsAPI.ts, frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/EditTeam.tsx, frontend/src/components/Common/FirestoreDataProvider.tsx, frontend/src/components/Common/Search.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
This PR converts `EditTeam` to use hooks, and thus able to listen to the members collection and derived team data. The code is greatly shortened as well.
Edit team should still work.
=> Make EditTeam component listen to derived team information

frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Common/FirestoreDataProvider.tsx, frontend/src/components/Common/Search.tsx
Make the team information be editable on the member editing side.
=> Support edit team information in admin member info editor

backend/src/api.ts, backend/src/memberAPI.ts, frontend/src/API/MembersAPI.ts, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/UserProfile/UserProfile.tsx, frontend/src/utils.ts
Remove these legacy APIs with firestore listeners.
Affected page of user profile and team event credit form works fine.
=> Remove `getMember` and `APICache` API

backend/tests/TeamEventsAPI.test.ts
Tested API endpoints for Team Events. 
Included tests for admin users with permissions and users without permissions so that errors were thrown as needed.
=> Test Team Events API 

dti-website/src/pages/courses.tsx
Changes Trends link for SP22 semester in the Courses page.
=> change Trends link for sp22

dti-website/src/data/apply.json, dti-website/src/pages/apply.scss, dti-website/src/pages/apply.tsx
This updates the apply page with new dates and some changed layout to better suit this semester's timeline (no more freshman split timelines)
TODO: Add design application link
=> SP22 Apply Page

dti-website/src/data/apply.json
Replaced placeholder links for our recruitment info sessions
Updated the application due date to 2/6
=> Add Info Session Zoom links and update recruitment timeline

dti-website/src/data/apply.json
We have a new link for developer applications in SP22
=> update dev application link

dti-website/pull-from-idol.ts
Update `pull-from-idol.ts` for `master` branch change to `main`. I think this should fix `Pull From IDOL` workflow. 
👀
=> update pull-from-idol script

frontend/src/components/Admin/TeamEventForm.tsx
This pull request updates the TEC admin form so that it clears after a new form is successful created (as discussed in #254).
https://user-images.githubusercontent.com/55467524/157079152-f4bfacd2-7a9a-4cb5-b56b-354285a5b394.mov
=> Update TEC admin form to clear on submission

README.md, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
Implement the dropdown search bar for the Team Events Credit form. Users can search for and and select from a list of event names.
Used Semantic UI React - Search Selection.
=> Implement teamEventCredits form searchbar

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.module.css, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditsDasboard.tsx
Changed styling of TEC member-side dashboard to card format
Added more data to dev firebase and made sure that logic was being displaying correctly. Here is a screenshot of the current formatting:
=> Change styling of TEC member-side dashboard 

frontend/src/components/Common/SiteHeader/SiteHeader.tsx
This pull request adds the homepage link to the DTI logo on the site header.
Clicking the logo from any page on the IDOL platform should take us to the homepage.
https://user-images.githubusercontent.com/55467524/166169238-97414a5e-5cfd-45d0-b741-f61c4eacfea6.mov
=> Add link to homepage

dti-website/src/data/all-members.json
```diff
--- existing.json	2022-05-02 04:09:50.945028916 +0000
+++ src/data/all-members.json	2022-05-02 04:09:50.941028684 +0000
@@ -1 +1,1690 @@
-[{"netid":"aa2235","name":"Aira Agrawal","pronouns":"","graduation":"May 2023","major":"CS","hometown":"Albany, NY","about":"Hi, I'm Aira! I'm a junior in Engineering studying Computer Science with minors in Business and Information Science. Outside of school, I enjoy dancing, baking, and exploring nature. ","subteams":["idol"],"roleId":"developer","roleDescription":"Developer","minor":"Business, InfoSci"},{"netid":"aa753","name":"Akash Aryal","pronouns":"","graduation":"May 2023","major":"Computer Science ","hometown":"Butwal, Nepal","about":"Hi! I'm a CS and Math double major in the college of A&S. My main interests are in web dev, data …
```
=> [bot] Automatically pull latest data from IDOL backend

backend/src/API/devPortfolioAPI.ts, backend/src/dao/DevPortfolioDao.ts, backend/src/types/DataTypes.d.ts, backend/src/utils/githubUtil.ts, backend/tests/DevPortfolioDao.test.ts, backend/tests/data/createData.ts, common-types/index.d.ts, frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
This PR changes the type for dev portfolio submissions so that each PR submitted can receive individual feedback on whether it was valid or invalid.
- Combine PR url and validation result into one type `PullRequestSubmission` 
- Add date validation helper function 
- Added function to create fake PR links for testing
Existing tests for dev portfolios were updated to use the new type and the generated fake PRs.
=> Update dev portfolio submission type to allow result for each PR submitted 

.github/PULL_REQUEST_TEMPLATE.md, backend/src/api.ts, backend/src/openapi.yaml
This pull request adds the remaining endpoints to the backend api specification document. It also updates the PR template to include a checkbox for updating the documentation whenever endpoints are added/modified.
The api spec should cover all the existing endpoints with accurate descriptions.
=> Update backend api specification

dti-website/src/pages/_app.tsx, frontend/src/API/APIWrapper.ts, frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
This PR should resolve the existing GitHub warnings under `Unchanged files with check annotations`.
There should be no change in functionality.
=> Resolve GitHub warnings

.github/PULL_REQUEST_TEMPLATE.md
Apparently the PR template needs to be in the default branch
=> Add figma file section to PR template 

backend/src/API/mailAPI.ts, backend/src/nodemailer.ts, frontend/src/components/Forms/UserProfile/UserProfile.tsx
There were a couple of places where GitHub Actions had warnings. This PR should just address those warnings.
There shouldn't be any more GitHub Actions Check warnings 👀
=> Fix GitHub Actions warnings 

dti-website/src/pages/courses.tsx
This PR updates the link for trends course application!
=> Update trends application link for fa22

README.md
=> Add PM and Design to sp22 contributors

.github/PULL_REQUEST_TEMPLATE.md
Title. Makes it easier for reviewers to understand the requirements for a change and why the changes are necessary.
=> Add Notion link reference to PR template 

frontend/src/API/DevPortfolioAPI.ts, frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx, frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Implemented frontend-backend integration of Dev Portfolio on both the member side and admin side. Users can now submit dev portfolio submissions, admins can create and delete dev portfolios. Admins can also view current dev portfolio submissions.
Manual testing, video attached
N/A
https://user-images.githubusercontent.com/59291082/191875922-f0544295-db59-4d92-a8f4-771881087431.mov
=> Andrewchen devportfolio frontend backend integration

frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- Added due date to dev portfolio assignment so members can easily identify which is the current assignment.
- Checked if current submission date is past the selected dev portfolio assignment due date and improved the UI error message to the member. 
- Checked if current submission date is before the selected dev portfolio assignment starts accepting submissions and improved the UI error message to the member.
=> Add Date Validation to Dev Portfolio Submissions

frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
Add reason for why the DP submission is invalid to the table.
https://www.notion.so/cornelldti/DP-View-Display-why-DP-submission-is-invalid-c851f5342cb84198808435b73b159766
Manual, screenshot attached.
=> display invalid dp submission reason

frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
This PR hides the regrade button from the user's submission history view.
Regrade button should be visible for admin's view, but not for user's view.
=> Hide regrade button for user view.

backend/src/utils/githubUtil.ts, common-types/index.d.ts, frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
This PR ensures that there is a `reason` associated with a submission result only if it is determined to be `invalid`
Only invalid results should have the reason displayed under them.
=> Populate `reason` only if PR is invalid.

frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
This PR makes it so that the word "submission" is only singular when there is 1, and plural otherwise.
Previously
Now
=> Fix typo in deciding when to make a word plural.

frontend/src/components/Modals/DevPortfolioTextModal.tsx
This PR fixes a visual bug in displaying the text associated with a submission.
Before:
Now:
=> Fix text view for dev portfolios.

backend/src/API/devPortfolioAPI.ts, backend/src/api.ts, backend/src/dao/DevPortfolioDao.ts, backend/src/types/DataTypes.d.ts, backend/src/utils/githubUtil.ts, common-types/index.d.ts, frontend/src/API/DevPortfolioAPI.ts, frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx, frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx, frontend/src/components/Modals/DevPortfolioTextModal.tsx
This PR adds the ability for admins to manually set the status of a submission after the automatic validation process. Any submissions with a `text` field associated with it will be set to `pending`, which an admin will manually review to determine whether it is `valid` or `invalid`. 
- (Text feature will be added by this PR) #349 
---
- Added `status` field to each dev portfolio submission.
- In admin details view, added a dropdown menu to display the status of each submission.
- Changing the dropdown menu selection will update the submission in the db immediately to reflect the new status. The menu is disabled while the change is being processed.
- Added new API endpoint `/updateDevPortfolioSubmissions` that replaces an existing portfolio's array of submissions. …
=> Allow admins to manually set status of dev portfolio submission.

frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.module.css, frontend/src/components/Homepage/Homepage/Homepage.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/forms/index.tsx
This PR puts the Shoutouts form on the homepage, reveals it to non-admin members in the Forms tab, and makes some minor cosmetic changes to deploy the feature for beta testing. Also made shoutouts anonymous by default.
Use preview to see whether the shoutouts feature shows on forms tab, and use the form (on desktop and mobile) to see if the experience is user friendly and polished.
=> Deploy Shoutouts feature

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
When new TEC submission is made, the member-side dashboard immediately reflects the new submission under the pending section with needing to refresh the page. 
There isn't specific ticket for this PR but is apart of [this epic](https://www.notion.so/cornelldti/Team-Events-Credit-Beta-Release-905f5593bcef4f0392dbda09fe0dfddb)
TEC dashboard should immediately display pending submission after making a submissions
=> Update pending list when new TEC submission is made

frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Add info message on dev portfolio form to indicate that re-submissions replace previous submissions.
[Notion link](https://www.notion.so/cornelldti/DP-Feedback-Make-it-more-clear-that-additional-submissions-are-resubmissions-32d065f5ceae49f095f2bb88e624907b)
👀
=> Add info message about dev portfolios re-submissions

backend/src/API/shoutoutAPI.ts, backend/src/dao/ShoutoutsDao.ts, backend/src/types/DataTypes.d.ts, common-types/index.d.ts, dti-website-redesign/next-env.d.ts, frontend/src/API/ShoutoutsAPI.ts, frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutCard.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutList.tsx, frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
Unify shoutouts type 
[Notion link](https://www.notion.so/cornelldti/Shoutouts-Unify-shoutout-type-9c71990843ab4573b0f7fba79a0fb090)
Existing functionality still works, tests pass
=> Unify shoutouts type 

.gitignore
Title 
https://nextjs.org/docs/basic-features/typescript
https://cornelldti.slack.com/archives/C01BYPLV0KY/p1672199464929079
N/A
=> Add next-env.d.ts to gitignore

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
This PR changes the required team events credits to 6 for leads and updates the tec instructions for leads. 
https://www.notion.so/cornelldti/TEC-Leads-need-6-credits-b2c1dfffd424437a8c39309cd29a58c7
These changes do not break anything for non-lead members.
=> change tec requirements for leads

README.md, frontend/src/components/Common/SignIn/SignIn.module.css, frontend/src/components/Common/SignIn/SignIn.tsx, frontend/src/components/Common/SiteHeader/SiteHeader.module.css, frontend/src/components/Common/SiteHeader/SiteHeader.tsx
Change sign in view
<https://www.notion.so/cornelldti/Frontend-Improve-the-login-screen-dfa1ee8c4173406fa982ad364637f626?pvs=4>
=> update sign in

backend/package.json, backend/src/api.ts, yarn.lock
Setup request logging on the backend. The logging is setup to log all requests in the format: 
```
[timestamp] [log-level] - [method] [endpoint-path] [response-status] -- [request-body]
```
For example:
```
2023-03-06T03:55:47.130Z info - POST /.netlify/functions/api/updateMember 200 -- {"netid":"hl738","email":"hl738@cornell.edu","firstName":"Henry","lastName":"Li","pronouns":"he/him","role":"tpm","roleDescription":"Technical PM","graduation":"May 2023","major":"Information Science","doubleMajor":null,"minor":"Computer Science","hometown":"Albany, NY","about":"why isn't this working :(\n","website":null,"linkedin":"https://linkedin.com/in/henryli6","github":null,"subteams":["idol"],"formerSubteams":[]}
```
[Notion link](https://www.notion.so/cornelldti/Add-backend-request-logging-8169c279 …
=> Setup request logging for backend 

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.module.css, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- Sorted dropdown events in reverse chronological order
changed the date object to be in a more representable format -example: Tuesday, Feb 14, 2023
=> Added date to team events dropdown

README.md
added Hope and Jason to Spring 2023 contributors 
added Henry as Fall 2022 dev 
Notion
https://www.notion.so/cornelldti/Add-Jason-and-Hope-to-README-979c08806cda41ff885d5839e9da0bff
=> added Jason,Hope,and Henry to readme

backend/src/dao/TeamEventAttendanceDao.ts, backend/src/firebase.ts, backend/src/types/DataTypes.d.ts, backend/tests/data/createData.ts, common-types/index.d.ts, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- Update the `TeamEventAttendance` and `DBTeamEventAttendance` types. Add the `team-event-attendance` collection reference.
- Add the `team-event-attendance` collection reference to `firebase.ts`.
- Add an empty `TeamEventAttendanceDao` class
- Modify the `TeamEventAttendance` and `DBTeamEventAttendance` types
This pull request is the first step towards implementing the refactoring of the TEC backend.
https://www.notion.so/cornelldti/TEC-Backend-Redesign-d9393218d4f440bc823319f052cec03b
N/A
=> Set up TEC Backend Refactoring

frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.module.css, frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
Before: 
After:
N/A
👀 - Just styling changes
=> Minor styling changes for admin shoutouts 

backend/src/api.ts
TItle. Test error endpoint was accidentally not removed when working on request logging. 
N/A
👀
=> Remove test error endpoint 

backend/tsconfig.json
This PR updates `tsconfig.json` in the backend directory to fix an issue with unresolved types that appears when some of us use VS Code.
`src/**/*` should match the same as `src/*`, so this technically shouldn't change anything.
=> Change `src/*` -> `src/**/*`

backend/src/dao/TeamEventAttendanceDao.ts
This pull request is the first step towards implementing feature TeamEventAttendanceDao 
- implemented `createteamEventAttendance`
- implemented `updateteamEventAttendance`
- implemented `deleteteamEventAttendance`
https://www.notion.so/cornelldti/Implement-create-update-and-deleteTeamEventAttendance-methods-in-TeamEventAttendanceDao-6fbf330dc7b442029e85c91ce0d14163
"
testing creating with and without the `hoursAttended` field"
tested updating Teameventattendance doc 
testing deleting
=> Implemented Create, Update, and delete for TeamEventAttendanceDao

backend/scripts/update-dev-db.ts, backend/src/dao/TeamEventAttendanceDao.ts, backend/src/firebase.ts, backend/src/utils/firebase-utils.ts
Implemented dao methods to:
- delete all team event attendance
- get all team event attendance by user
- get all team event attendance by event
- get all team event attendance
https://www.notion.so/cornelldti/Implement-deleteAllTeamEventAttendance-and-get-dao-methods-for-TeamEventAttendanceDao-6e9407c1e1834c28af665951c975a3ca?pvs=4
Tests are from the following file:
```
import { fakeIdolMember } from '../../tests/data/createData';
import { teamEventAttendanceCollection } from '../firebase';
import TeamEventAttendanceDao from './TeamEventAttendanceDao';
const member1 = {
netid: 'ow39',
email: 'ow39@cornell.edu',
firstName: 'Oscar',
lastName: 'Wang',
pronouns: '',
graduation: '',
major: '',
hometown: '',
about: '',
subteams: '',
role: 'developer',
roleDescription: 'Developer'
};
const …
```
=> implemented dao methods

backend/src/API/teamEventsAPI.ts
Implemented Update and Delete in teamEventsAPI
- Changed ‘attendance argument’ to “teamEventAttendance for consistency ”
This pull request is the one of many steps towards refactoring the TEC backend
https://www.notion.so/cornelldti/Implement-updateTeamEventAttendance-and-deleteTeamEventAttendance-endpoints-for-teamEventsAPI-c834c5c0105241d1b4de5aabafea6a94
tested locally, and looks good 
here are test
=> Implemented Update and Delete in teamEventsAPI

backend/src/API/teamEventsAPI.ts
This pull request implements the `getTeamEventAttendanceByUser` endpoint in `teamEventsAPI`.
https://www.notion.so/cornelldti/Implement-getTeamEventAttendanceByUser-endpoint-for-teamEventsAPI-1687f4e99ca84479bd0e831fc85aafd0?pvs=4
manual testing using the following code (in dao directory):
```
import { fakeIdolMember } from '../../tests/data/createData';
import { teamEventAttendanceCollection } from '../firebase';
import TeamEventAttendanceDao from './TeamEventAttendanceDao';
import { getTeamEventAttendanceByUser } from '../API/teamEventsAPI';
const member1 = {
netid: 'ow39',
email: 'ow39@cornell.edu',
firstName: 'Oscar',
lastName: 'Wang',
pronouns: '',
graduation: '',
major: '',
hometown: '',
about: '',
subteams: '',
role: 'developer',
roleDescription: 'Developer'
};
const member2 = …
```
=> Tec api/get by user

backend/src/api.ts
Remove the unused `/info` endpoint that was accidentally left in a PR. 
N/A
👀 - endpoint isn't used anywhere
=> Remove unused /info endpoint 

backend/src/API/teamEventsAPI.ts, backend/src/dao/TeamEventAttendanceDao.ts
Refactors `TeamEventAttendanceDao` to extend `BaseDao`
N/A
👀
`TeamEventDao` still hasn't been updated yet so will refactor that class in a later PR.
=> Refactor TeamEventAttendanceDao to extend BaseDao 

frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
Title.
[Notion link](https://www.notion.so/cornelldti/Shoutouts-Fix-How-Shoutouts-Are-Loaded-In-on-Admin-View-d13356cdbb5b4bd598b6b7aec9f9c9fc?pvs=4)
👀
=> Add loading wheel for shoutouts

dti-website/pull-compress-headshots.ts, dti-website/pull-from-idol.ts
Fixed failing job, which depends on an API endpoint that was changed in: https://github.com/cornell-dti/idol/pull/472, but I forgot to update the endpoint in the job here.
=> Update References to API

frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx, frontend/src/pages/App.css
- adds loader before the TEC proof photo loads when admin reviews TEC submission
=> Add loader when tec proof image is loading

frontend/src/components/Homepage/Homepage/Homepage.tsx
Added a card for the TEC tracker on the Homepage.
=> add tec card to homepage

README.md
Make README more user-friendly for non-DTI users to understand what IDOL is.
=> Update README description of IDOL

backend/src/api.ts
Use `getCurrentOrPastMemberByEmail` instead of `getMember` for `/hasIDOLAccess`
N/A
👀
=> give me idol access again

README.md
created a new branch (updating-names-on-readme) to add/merge names (Patricia Huang, Kevin Ram, Vicky Wang, Vannessa Wong) without conflicts.
=> add name(s) to contributors list

backend/src/dao/CandidateDeciderDao.ts
added documentation to CandidateDeciderDao -  documenting the purpose and usage of each method within the class.
=> added documentation, CandidateDeciderDao

backend/src/dao/DevPortfolioDao.ts
Added documentation for the methods in DevPortfolioDao.
=> Add documentation to DevPorfolioDao

backend/src/dao/ShoutoutsDao.ts
- Adds documentation to all the methods in `ShoutoutsDao.ts`
=> add documentation to ShoutoutsDao methods

backend/src/utils/firebase-utils.ts
Add docstrings to the Firebase Utils function as well as more type hints.
=> Add Firebase Utils Documentation

backend/src/API/mailAPI.ts
Prevent mail from being sent in non-prod environments.
Verified:
=> Prevent mail sends in Non-Prod Environments

backend/src/dao/SignInFormDao.ts
added documentation to SignInFormDao- documenting the purpose and usage of each method within the class.
=> added documentation, SignInFormDao

backend/src/API/signInFormAPI.ts
added documentation to SignInFormAPI- documenting the purpose and usage of each method within the class.
=> added documentation, SignInFormAPI

backend/src/API/memberAPI.ts, backend/src/api.ts
- See title
- Changed `body` parameters to `member`
- removed unused `request` parameter in `updateMember`
=> Add documentation for memberAPI

backend/src/API/mailAPI.ts
Added documentation to each function in mailAPI.ts.
=> Add documentation to mail API

frontend/src/components/Admin/AddUser/AddUser.tsx
Add error alert if role is not selected and if valid Cornell email is not provided (or field is left blank)
Manual (see video attached).
https://github.com/cornell-dti/idol/assets/59291082/2a1493d5-3ed8-40b3-bfe0-f99c2c1dc3dc
=> Improve error handling for edit users tool (require role to be selected, valid Cornell email)

backend/src/API/imageAPI.ts
- adds documentation to all methods in `imageAPI.ts`
=> Add documentation for imageAPI

.github/workflows/restore-from-backup.yml, backend/package.json, backend/scripts/restore-from-backup.ts
Add script and corresponding and GitHub Actions job (not cron, as we only want to run this on demand) for restoring the prod DB.
Ran script and the prod data matches the backup DB.
=> Add Restore from Backup Script

frontend/src/components/Modals/DevPortfolioTextModal.tsx
Quick fix to resolve text overflow issue with the text modal in dev portfolios.
=> Fix text overflow in modal

README.md
Added self to the Spring 2024 contributors list and edit roles.
=> Update SP24 contributors

backend/src/API/candidateDeciderAPI.ts
added documentation to CandidateDeciderAPI- documenting the purpose and usage of each method within the class.
- (didn't include @param to avoid redundancy)
=> added documentation, CandidateDeciderAPI

backend/tests/CandidateDeciderDao.test.ts, backend/tests/data/createData.ts
Tested CandidateDeciderDao with a test file by creating mock data, and ensuring certain properties are met after using CandidateDeciderDao functions.
=> Test CandidateDeciderDao

frontend/src/consts.ts
Flip feature flag to disable TEC Initiative events
=> TEC: disable tec initiative events

frontend/src/components/Candidate-Decider/ResponsesPanel.tsx, frontend/src/components/Candidate-Decider/ratings-utils.ts
Change text for ratings to be strong no - no - maybe - yes - strong yes.
=> Candidate Decider: change wording of ratings

frontend/src/components/Candidate-Decider/ResponsesPanel.tsx
Change header to "Link your resume"
This value should not have been hardcoded to the value it was at (too specific and it's impossible to get manually edit the database to get the \n characters). We should eventually have standardized columns here.
=> Candidate Decider: Change header to "Link your resume"

frontend/src/components/Modals/CandidateDeciderEditModal.tsx
Fix comment and rating exporting (small mistake in the `reduce` operation)
=> Candidate Decider: fix comment and rating exporting

backend/tests/CoffeeChatDao.test.ts, backend/tests/data/createData.ts
This PR tests the `getCoffeeChatsByUser` function in `CoffeeChatDao.ts`, since optional fields were added. The rest of the functions are indirectly tested in `CoffeeChatAPI.test.ts`.
=> Test getCoffeeChatsByUser

frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx, frontend/src/components/Modals/CoffeeChatDetailsModal.tsx
Allow members to delete approved coffee chats in case they change their mind about putting a coffee chat in a certain category.
=> Allow Deletion of Approved Coffee Chats

frontend/src/components/Admin/CoffeeChats/CoffeeChats.module.css, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChats.module.css, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx
This PR helps teams members track how many bingos they have and also if they have a blackout. 
https://github.com/user-attachments/assets/037e34fb-cc18-456c-86ed-3302f248cdd0
=> Track Bingo/Blackout on Member Side

frontend/src/components/Admin/CoffeeChats/CoffeeChatDetails.tsx
- Fix infinite loop bug on admin view: we put an API call directly inside of a component instead of a `useEffect` call. Since the callback function updates the state, this causes the component to re-render, which then makes the API call again, resulting in an infinite loop
- Improve loading state so that the colors don't flash in the user's face (wait for the auto-checker to finish running against all the coffee chats first, then display all the cards with their auto-checker results)
- Manually observe only the correct number of API calls are made, no more infinite loop when trying to repro
=> Coffee Chat: Fix Infinite Calls to Coffee Chat API Bug on Admin Tool

backend/src/API/coffeeChatAPI.ts, backend/src/api.ts, frontend/src/API/CoffeeChatAPI.ts, frontend/src/components/Admin/CoffeeChats/CoffeeChatDetails.tsx, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
This PR makes sure the submitter email for the `checkMemberMeetsCategory` endpoint is specified. The function used to assume that the submitter was the current user, which worked for the member side, but not the admin side.
=> Coffee Chat: Fix checkMemberMeetsCategory Endpoint

README.md
This pull request adds **Juliet Crane** to the list of contributors in the `README.md` for the current semester.
I manually verified that my name was correctly added to `README.md`
=> add name to contributors list

new-dti-website/src/app/initiative/page.tsx
Fix a small bug with the blurring of the Navbar menu in mobile view.
Before:
https://github.com/user-attachments/assets/f551d60f-9cd5-4d5f-8267-46cd0693afad
After:
https://github.com/user-attachments/assets/d3be5594-8939-46dc-8a21-78707ceda3a8
=> New Website: Fix Mobile Navbar Blur on Initiatives Page

frontend/src/API/CoffeeChatAPI.ts, frontend/src/components/Admin/CoffeeChats/CoffeeChatDetails.tsx
On the admin side, the color of each chat was being fetched live, which caused some lagging. The chats were also not being updated automatically after clicking "Re-run autochecker."
=> Coffee Chat: Remove Live Checking and Update Chats After Running Autochecker

frontend/src/components/Forms/CoffeeChatsForm/CoffeeChats.module.css, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx
The blackout message appears while the coffee chats are loading, which could be misleading if the chats load for a longer period of time. Instead, the bingo count or blackout text shouldn't appear while the chats are loading.
=> Coffee Chat: Fix Submission Page Loading

new-dti-website/components/initiatives/InitiativeDisplay.tsx, new-dti-website/src/app/initiatives/page.tsx
This PR fixes the initiatives page based on recent comments.
* Fixed featured initiative page
* Increase vertical margin
* Increase text height to `1.75rem=28px`
* Remove box shadows from images 
[Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/DTI-New-Landing-Website?node-id=7-14&node-type=frame&t=TasRikzIqlSw53ng-0#1038253703)
["Give back to community" section fixes](https://www.notion.so/Idol-FA24-1030ad723ce1804ca825d0ec8972c711?p=14a0ad723ce180e28043fa5ac258f3dc&pm=s)
Featured initiative before:
Featured initiative after:
=> Website: Initiatives Page Improvements

new-dti-website/components/apply/ApplicationTimeline.tsx, new-dti-website/components/bottom.tsx, new-dti-website/components/team/TeamFooter.tsx, new-dti-website/config.json, new-dti-website/src/app/course/page.tsx
Replace all text that was previously all caps with capitalized text (for proper nouns) and sentence caps.
https://www.notion.so/Remove-all-caps-1510ad723ce1807a86a0ec056ec8d21e?pvs=4
Before:
After:
=> New Website: Remove All Caps

dti-website/next-env.d.ts, new-dti-website/src/app/layout.tsx, new-dti-website/src/consts.ts, new-dti-website/src/hooks/useGoogleAnalytics.ts
Largely copy paste from https://github.com/cornell-dti/idol/pull/283, adapted to work with `app/` directory instead of the older `pages/` directory model.
Configured a new stream on our google analytics account for new website and set the URL to be new.cornelldti.org while we're still pre-launch.
https://www.notion.so/Set-up-google-analytics-for-new-website-d8d425162cd24b29b48a248d948a8665?pvs=4
We can test this by hitting the website a bunch of times across a few days to see if any data is received. It can take up to 48 hours for data to begin showing.
=> New Website: Set up Google Analytics

frontend/src/components/Admin/CoffeeChats/CoffeeChatDashboard.tsx
Previous logic was overwriting the value of bingo for every "bingo line" that it checked, so the final value of `bingo` would only be the last one checked.
Change this to show bingo as true if at least one line evaluates to true.
=> Coffee Chat: Bingos Aren't Showing Up Correctly on Bingo Dashboard

new-dti-website/components/bottom.tsx, new-dti-website/src/app/course/page.tsx
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce180f18672ff882babf85f)
=> Clement past student projs copy edit

new-dti-website/components/apply/ApplicationTimeline.tsx
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce180feaeddc781a6d0cccb)
|Before|After|
|-|-|
|<img width="1649" alt="Screenshot 2024-12-07 at 6 19 54 PM" src="https://github.com/user-attachments/assets/ce95b1dc-6889-461c-b8ea-adc1d8af6650">|<img width="1649" alt="Screenshot 2024-12-07 at 6 19 16 PM" src="https://github.com/user-attachments/assets/0fa97c9b-281e-400d-8b26-0b4f55a63b5f">|
=> Clement apply page tab styling

new-dti-website/components/team/MemberGroup.tsx
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce180acaa3ce7c5080de7c5)
|Before|After|
|-|-|
|<img width="1374" alt="Screenshot 2024-12-07 at 5 14 20 PM" src="https://github.com/user-attachments/assets/601985d7-2f29-42e3-8c92-05e2e2b419d0">|<img width="1374" alt="Screenshot 2024-12-07 at 5 14 08 PM" src="https://github.com/user-attachments/assets/720aa946-683e-4de4-9d51-8b9e013ac75e">|
=> About page: made profile card pills smaller

new-dti-website/components/apply/ApplyFAQ.tsx, new-dti-website/components/apply/data/applications.json
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce18035823adf7105d05bb4) and [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce180349dc6cee48fe68b53)
no screenshots cuz just text change 🤡
=> Apply page: copy edits

new-dti-website/src/app/globals.css
agreed with Vannessa to change secondary button styling for hover state
|Where|Before|After|
|-|-|-|
|Apply page|<img width="1204" alt="1 old" src="https://github.com/user-attachments/assets/600c6464-c1dd-4aa7-8394-2093f8214b3c" />|<img width="1204" alt="1 new" src="https://github.com/user-attachments/assets/4717fed3-d058-4d53-97be-24f5edcc546c" />|
|Course page|<img width="1204" alt="2 old" src="https://github.com/user-attachments/assets/ea399cca-2b6d-4e6b-9547-060781c380f5" />|<img width="1204" alt="2 new" src="https://github.com/user-attachments/assets/495a5cdd-c290-4262-bc66-422790026ad1" />|
=> Changed secondary button color

new-dti-website/src/app/initiatives/page.tsx
This PR implements feedback from latest leads sync.
[Notion](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce1803eb684d51971b93351)
Netlify deploy vs. current website
=> Website: More Initiatives Page Improvements

new-dti-website/components/apply/ApplicationTimeline.tsx, new-dti-website/components/apply/ApplyFAQ.tsx, new-dti-website/components/apply/RoleDescription.tsx, new-dti-website/components/apply/data/applications.json, new-dti-website/components/blob.tsx, new-dti-website/config.json, new-dti-website/src/app/apply/page.tsx, new-dti-website/src/app/globals.css
Fixes the following features
[Notion](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#cd388ffaf03b4c6d9d5ddb5de752155c)
Local deployment
=> Website: More Apply Page Improvements

common-types/constants.js, common-types/index.d.ts
We are missing AAP from the IDOL dropdown list.
=> IDOL: Add AAP to colleges

new-dti-website/config.json
Update coffee chat links for sp25 recruitment.
=> Website: Update Coffee Chat SP25 Links

new-dti-website/config.json
=> Website: Add SP25 Recruitment Events

new-dti-website/config.json
There was a typo in the date for the URMC event. It should be on Monday not Tuesday.
=> Website: Update URMC event date

new-dti-website/components/apply/data/applications.json
james requested this, just a small content change
=> updated designer description

new-dti-website/components/course/data/config.json, new-dti-website/components/course/data/timeline_events.json
change trends application link and timeline for sp25
=> Website: Update course timeline and application link

new-dti-website/components/course/data/timeline_events.json
Updated dates for Trends. Lecture 1 and sign-up deadline has been moved back to accommodate for February break.
=> Website: Update Trends timeline

new-dti-website/components/course/data/timeline_events.json
Changes the timeline to the correct lecture 1 date and notes that the lecture will be conducted asynchronously.
=> Website: Change lecture 1 date and specify asynchronous

frontend/src/components/Forms/CoffeeChatsForm/CoffeeChats.module.css, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx, frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
Added dropdown to coffee chat bingo board to see previously approved coffee chats
=> Added drop down to see previous coffee chats

new-dti-website/components/apply/ApplicationTimeline.tsx, new-dti-website/components/apply/RoleDescription.tsx, new-dti-website/components/team/TeamAbout.tsx, new-dti-website/components/team/TeamHero.tsx, new-dti-website/src/app/apply/page.tsx, new-dti-website/src/app/course/page.tsx, new-dti-website/src/app/initiatives/page.tsx, new-dti-website/src/app/page.tsx, new-dti-website/src/app/products/page.tsx, new-dti-website/src/app/sponsor/page.tsx
[figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1294-1572&p=f&t=3auvilVN7vUBuemK-11)
we've decided to remove all red dots/blobs on every page for Giving Day.
=> removed all red dots

new-dti-website/src/app/page.tsx
[le figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1320-5017&t=gmS4fmYML25hwknA-11)
I initially removed all red dots in [this PR](https://github.com/cornell-dti/idol/pull/861)
so now im adding a decorational element (just for homepage hero section though)
|-|-|-|
|Desktop|<img width="1556" alt="Screenshot 2025-02-27 at 2 36 43 PM" src="https://github.com/user-attachments/assets/19068286-60e4-48fd-b0c5-a000c2b42185" />|<img width="1556" alt="Screenshot 2025-02-27 at 2 36 20 PM" src="https://github.com/user-attachments/assets/6df3a998-0c7d-4dd1-ac3e-86b433f671cf" />|
|Mobile|<img width="362" alt="Screenshot 2025-02-27 at 2 37 27 PM" src="https://github.com/user-attachments/assets/50118933-27f8-4b2d-81cd-b7a86c97e1b6" …
=> Added decoration to homepage hero section

frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx, frontend/src/consts.ts
This pull requests implements the new TEC requirements in IDOL's submit TEC page. It prevents members from submitting a TEC if they already submitted one in the current 5-week period, unless they missed the last period or they are a lead. 
[https://www.notion.so/Track-new-TEC-requirements-1950ad723ce180e8b18df88a3d7f0388](https://www.notion.so/Track-new-TEC-requirements-1950ad723ce180e8b18df88a3d7f0388)
https://github.com/user-attachments/assets/de0f8025-5b54-4c30-a24b-89dc25313d18
=> Tracking New TEC Requirements 

frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx, frontend/src/components/Modals/CoffeeChatDetailsModal.module.css
There was a bug that prevented people from viewing coffee chats from previous semesters. Previous coffee chats are valid if the other member exists and the status is approved.
=> Previous Semester's Coffee Chats Bug Fixes

new-dti-website/components/team/TeamAbout.tsx, new-dti-website/components/team/TeamFooter.tsx
Two images on the team page had the wrong source. `alt` was also changed to reflect the new image.
=> Website: Fix Image Source

frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx, frontend/src/components/Modals/CoffeeChatDetailsModal.tsx
Added code to filter out coffee chat suggestions with people from past semester (approved archived chats).
=> filter out cc suggestions from archived chats

new-dti-website/components/page.tsx
[slack link](https://cornelldti.slack.com/archives/C086SPYP5D5/p1742000764382029)
|Before|After|
|-|-|
|<img width="1548" alt="Screenshot 2025-03-14 at 11 08 49 PM" src="https://github.com/user-attachments/assets/fb7487d3-6d4c-4348-a9b6-51fe8c8eda58" />|<img width="1565" alt="Screenshot 2025-03-14 at 11 08 57 PM" src="https://github.com/user-attachments/assets/4d6a4674-79c5-40f9-88f7-b59148df0e39" />|
=> Changed banner text

new-dti-website/components/hero.tsx, new-dti-website/components/page.tsx, new-dti-website/src/app/page.tsx
Removed giving day banner, no need it anymore since we're past giving day date.
=> rm giving day banner

backend/src/API/interviewSchedulerAPI.ts
- Added documentation to the interviewSchedulerAPI
=> added documentation to interview scheduler api

frontend/src/pages/App.css
remove fixed height on main container
=> hotfix: remove height from app sidebar

backend/src/utils/githubUtil.ts, common-types/index.d.ts, frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx, frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Allow devs to submit personal repositories instead of opened PR for dev portfolios
https://www.notion.so/Dev-Portfolio-Allow-Devs-to-Submit-Repositories-as-Opened-PR-19e0ad723ce180579503ccfbd1a7a351
=> Submit personal repos for dev portfolios

yarn.lock
=> Cleaning yarn.lock

frontend/src/components/Common/Selector/Selector.module.css
Added `cursor: pointer;` for a better affordance
|Before|After|
|-|-|
|<img width="567" alt="Screenshot 2025-04-29 at 7 54 17 PM" src="https://github.com/user-attachments/assets/36e6b08b-4d81-472b-8d93-2616a1b4c9c6" />|<img width="538" alt="Screenshot 2025-04-29 at 7 54 05 PM" src="https://github.com/user-attachments/assets/bd460a72-ddf1-432f-bf2f-fa6f713120f8" />
| HEADER   |   HEADER |
|-|-|
| content #1     | # content 2 |
|Before|After|
|-|-|
|<img width="567" alt="Screenshot 2025-04-29 at 7 54 17 PM" src="https://github.com/user-attachments/assets/365fed8b-2b91-4eff-adf6-d3ef46086502" />|<img width="538" alt="Screenshot 2025-04-29 at 7 54 05 PM" src="https://github.com/user-attachments/assets/ee83f11c-2479-42d5-8040-8e1d7d684711" />
=> [Cand decider] Added cursor pointer to the selector component

new-dti-website-redesign/src/app/design-system/CardLink.tsx, new-dti-website-redesign/src/app/design-system/PageLayout.tsx, new-dti-website-redesign/src/app/design-system/PageSection.tsx, new-dti-website-redesign/src/app/design-system/Sidebar.tsx, new-dti-website-redesign/src/app/design-system/components/button/page.tsx, new-dti-website-redesign/src/app/design-system/components/card/page.tsx, new-dti-website-redesign/src/app/design-system/components/chip/page.tsx, new-dti-website-redesign/src/app/design-system/components/icon-wrapper/page.tsx, new-dti-website-redesign/src/app/design-system/components/icon/PlusIcon.tsx, new-dti-website-redesign/src/app/design-system/components/icon/RocketIcon.tsx, new-dti-website-redesign/src/app/design-system/components/icon/icons.tsx, new-dti-website-redesign/src/app/design-system/components/icon/page.tsx, new-dti-website-redesign/src/app/design-system/components/input/page.tsx, new-dti-website-redesign/src/app/design-system/components/tabs/page.tsx, new-dti-website-redesign/src/app/design-system/nav.config.ts, new-dti-website-redesign/src/app/design-system/page.tsx, new-dti-website-redesign/src/app/design-system/styles/color/page.tsx, new-dti-website-redesign/src/app/design-system/styles/layout/layouts.ts, new-dti-website-redesign/src/app/design-system/styles/layout/page.tsx, new-dti-website-redesign/src/app/design-system/styles/typography/page.tsx, new-dti-website-redesign/src/app/design-system/styles/typography/typography.ts, new-dti-website-redesign/src/app/globals.css, new-dti-website-redesign/src/app/test-page/page.tsx, new-dti-website-redesign/src/components/Chip.tsx, new-dti-website-redesign/src/components/DevNavbar.tsx, new-dti-website-redesign/src/components/Footer.tsx, new-dti-website-redesign/src/components/Layout.tsx, new-dti-website-redesign/src/components/Navbar.tsx
- Not much in this PR other than updating the design system library
- Reminder: this design system library is essentially a collection of all the styles and components we use to build the DTI website. It's meant to serve as a reference for future maintenance, and also i'd like to it to be public in the spirit of open source + to educate others
- I'll provide more detailed analysis inline in the actual code since there are lots of small changes dispersed everywhere, but here's a high level overview:
- Created `<PageSection>` component , a reusable component used for layout in the design system library pages
- Styles:
- Updated `/typography` with all the typography styles
- Components:
- Updated `/button` and `/input` with the relevant components
- Created `/card`, `/chip`, `/icon`, …
=> [New Website] Design System Library Updates

new-dti-website-redesign/src/app/apply/RoleDescriptionCard.tsx, new-dti-website-redesign/src/app/apply/page.tsx, new-dti-website-redesign/src/app/apply/roleDescriptions.json, new-dti-website-redesign/src/components/Tabs.tsx
- Created `RoleDescriptionCard.tsx` component to display skills + responsibilities for joining DTI
- Added data in `roleDescriptoins.json`
- Mapped out cards + data in `<Tabs>` in `apply/page.tsx`
https://github.com/user-attachments/assets/1235c8c8-e582-4511-aff8-e1794a778bf5
- Head to `/apply`
- Make sure clicking tabs brings you correct card
- Test for responsiveness too
=> [New Website] Apply page role description card + section

new-dti-website/components/footer.tsx, new-dti-website/config.json, new-dti-website/src/app/apply/page.tsx, new-dti-website/src/app/layout.tsx
- updates apply page to accurately show that fall 25 applications are not currently open
- added todos to revert hardcoded changes once we have a new application timeline
- adds "This organization is a registered student organization of Cornell University" to footer to ensure compliance
- update `layout.tsx` script tags to be inside body, fixing React hydration error on startup
=> FA25 compliance

new-dti-website-redesign/src/app/team/TeamDisplay.tsx, new-dti-website-redesign/src/components/SectionSep.tsx, new-dti-website-redesign/src/components/course/CourseStaff.tsx, new-dti-website-redesign/src/hooks/useIsMobile.ts
- Minor fixes to SectionSep component
- apply the default sectionSep class unless disableSectionSepStyle is passed as a prop (used to remove margins and width constraints when needed)
=> [New Website] SectionSep component fix

new-dti-website-redesign/src/app/page.tsx, new-dti-website-redesign/src/components/Hero.tsx, new-dti-website-redesign/src/components/Navbar.tsx
- Fixes Notion issues:
- [Update hero section gradients](https://www.notion.so/Update-hero-section-gradients-24a0ad723ce1802c8de0cf38b9f4d54f?source=copy_link)
- [Mobile navbar accessibility](https://www.notion.so/Mobile-navbar-accessibility-23f0ad723ce1806a8db5c0f61d1a25cf?source=copy_link)
|-|-|-|
|Home|<img width="1788" height="940" alt="Screenshot 2025-08-10 at 11 17 03 PM" src="https://github.com/user-attachments/assets/366c2949-9c12-4a76-8b91-efe8ec2029df" />|<img width="1788" height="940" alt="Screenshot 2025-08-10 at 11 16 57 PM" src="https://github.com/user-attachments/assets/05c672ed-0499-43e5-8a93-35080ec67432" />|
|Apply|<img width="1788" height="940" alt="Screenshot 2025-08-10 at 11 17 08 PM" src="https://github.com/user-attachments/assets/99d82ae4-6e4b-48ee-b …
=> [New Website] Various #A11y fixes in hero sections, navbar, and logo carousel

new-dti-website-redesign/src/app/team/page.tsx
- Added coffee chat spreadsheet link to CTA section at bottom of team page
[Coffee Chat link](https://www.notion.so/Team-Website-Task-Force-1be0ad723ce18020aad2fea7c24a58ef?p=2440ad723ce1809e8545e15703d401ab&pm=s)
=> [New Website] Added coffee chat link

new-dti-website-redesign/src/app/apply/ApplicationTimeline.tsx, new-dti-website-redesign/src/app/course/PastStudentProjects.tsx, new-dti-website-redesign/src/app/products/products.json, new-dti-website-redesign/src/app/team/WhoWeAre.tsx, new-dti-website-redesign/src/components/FeatureCard.tsx, new-dti-website-redesign/src/components/Footer.tsx, new-dti-website-redesign/src/components/Tabs.tsx, new-dti-website-redesign/src/components/TeamCard.tsx, new-dti-website-redesign/src/components/TimelineCard.tsx
- Notion [ticket](https://www.notion.so/Perform-screenreader-audit-24c0ad723ce180839543e14f2cfcb6d1?source=copy_link)
We should make an effort to ensure that the website is as accessible by anyone, regardless of their way of using the website.  This includes individuals who navigate the website using only their keyboard (and by using Screen Reader technology)
I audited the website using only a screen reader to check for things like image alt text, correct button labels, semantic navigation, intuitive labels, etc.
Made a few fixes to make things as clear as possible to someone who might be navigating the website blind for example, or who might not be able to use their mouse.
- Test out website using screen reader technology
=> [New Website] Screenreader audit

new-dti-website-redesign/config.json, new-dti-website-redesign/src/app/course/data/timeline_events.json, new-dti-website-redesign/src/app/team/page.tsx
- Updated Trends instructors
- Changed Trends timeline to TBD for now
- Removed capitalization of "Chat"
=> [New Website] Quick fixes

new-dti-website-redesign/src/app/apply/page.tsx, new-dti-website-redesign/src/components/Hero.tsx
Made "Apply to DTI" button on "Apply" page non disabled
=> [New Website] Make "Apply to DTI" button on "Apply" page non-disabled

new-dti-website-redesign/src/app/apply/events.json
=> add info sesh 1 location

new-dti-website-redesign/src/app/apply/events.json
Add the "Cracking the PM Interview" recruitment event.
=> update recruitment event

new-dti-website-redesign/src/app/apply/roleDescriptions.json
On biz leads request, edited requirements on Apply page for biz team. [Slack for context](https://cornelldti.slack.com/archives/C0960JD5BLK/p1756511439003489)
=> [New Website] Apply page biz team copy updates

new-dti-website-redesign/src/app/apply/events.json
=> update urmc date

new-dti-website-redesign/src/app/products/ProductsList.tsx, new-dti-website-redesign/src/app/products/page.tsx
The "View products" button was bringing the user back Home, but it should be scrolling you down instead.
=> [New Website] Fixed broken link on Products page

new-dti-website-redesign/src/app/course/data/config.json, new-dti-website-redesign/src/app/course/data/timeline_events.json
Updated Trends application link and application deadline.
=> update trends app link to fa25

backend/src/API/mailAPI.ts, backend/src/API/teamEventsAPI.ts, backend/src/api.ts, backend/src/consts.ts, frontend/src/API/MembersAPI.ts, frontend/src/components/Admin/TeamEvent/TeamEventDashboard.module.css, frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx, frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx, frontend/src/components/Modals/NotifyMemberModal.tsx, frontend/src/consts.ts, frontend/src/utils.ts
Updated TEC requirements to be monthly periods with no carryover from previous periods. Members must submit 1 per period and leads 2 per period. 
- Changed TEC deadlines
- Fixed TEC form and TEC dashboard to reflect new requirements
- Adjusted emails so that leads only send emails to remind members who need to complete tec for the current period, no semester reminders
[tec updates](https://linear.app/cornelldti/issue/IDOL-21/tec-updates)
- In TEC dashboard normal view, members only green if they are up to date on tec for all periods so far
- In TEC dashboard period view, members only green if they are up to date on current period's tec requirement
- Notify button sends emails to all members who have missing credits for current period (in logs in non-prod)
=> Update TEC requirements

frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
Admin dev portfolio details table rows were misaligned with no-pr submissions.
[linear issue](https://linear.app/cornelldti/issue/IDOL-22/admin-dev-portfolio-table-columns)
=> Fix admin devportfolio table row issue
