- .github/workflows/ci-policies.yml
All DTI repos must have [big-diff-warning](https://github.com/cornell-dti/big-diff-warning) enabled to prevent again large PRs.
PR comment.
> Set up big-diff CI

- backend/src/api.ts
- backend/src/memberAPI.ts
In our meeting, we decide to make this API public to help nova integration. This API is readonly, and the info it exposed will be on the public team website anyways, so it won't introduce any security vulnerability.
Check you can visit the public API url in deploy preview. (sad the instance still hasn't secret set, so the endpoint fails)
> Change memberAPI to remove auth requirement for nova integration

- frontend/src/API/MembersAPI.ts
- frontend/src/API/RolesAPI.ts
- frontend/src/User/AddUser/AddUser.tsx
- frontend/src/User/UserProfile/UserProfile.tsx
- frontend/src/utils.ts
Unbreak saving user on the frontend by deriving netid and role description from existing fields. In the future, we probably shouldn't store them at all, since we can always easily derive them.
A screenshot showing that a setMember request sent by frontend. Here, the role description and netid is correct.
> Derive NetID and role description from email and role

- frontend/src/User/UserProfile/UserProfile.test.tsx
- frontend/src/User/UserProfile/UserProfile.tsx
The user can now only edit their first and last name if they have the correct permissions ('admin' or 'lead').
Form for a user with 'admin' permissions.
Form for a user with 'developer' permissions.
- This has a bit of duplicated code, so if anyone has any suggestions on how to reduce that I would appreciate it!
- I also noticed that the error modal isn't working when a user with the wrong permissions tries to edit their information, so that needs to be addressed
> only edit name if user has correct permissions

- backend/src/memberAPI.ts
This pull request updates the backend function to fix the check for user permissions for updating member documents. Previously, there was an error where the user could not update their own information if their role was not `'admin'` or `'lead'`. 
The changes in this PR fixes that and also displays the appropriate error message in case the member's document is not in the Firebase.
> Update permissions and error messages for updateMember

- backend/src/dao/MembersDao.ts
- backend/src/dao/TeamsDao.ts
- backend/src/firebase.ts
- backend/src/imageAPI.ts
- backend/src/memberAPI.ts
- backend/src/permissions.ts
- backend/src/teamAPI.ts
- frontend/src/User/EditTeam/EditTeam.tsx
Using typescript with [`FirestoreDataConverter`](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter) gives all the database operations a more specific type instead of any type. This means that we won't accidentally write data that doesn't belong to a collection.
Here is a little demo showing how it can help to type check database operations:
I replaced all the existing untyped calls to the database collection methods with the typed ones. This change reveals the hidden bug where we don't check member is `null` in team API and using `first_name` instead of `firstName` in member API.
Start frontend and backend to ensure that every endpoint can still work.
> Use firestore data converter for statically typed DB operations

- dti-website/src/components/DtiFooter.tsx
According to accessibility standards, `a` tag must have `href`. In the existing code, we are mostly using `a` tag to achieve some styling effect, which is bad. This PR replaces it with `div` and everything still looks the same.
No change in appearance
> [easy] Fix simple accessibility warning on website button

- dti-website/src/components/CircleProgressIndicator.tsx
This PR fixes a UI bug on the team page of the DTI website. 
The bug caused the gender ratio donut graph to bug out:
https://cornelldti.slack.com/files/U77S15WQL/F01T18XDR0R/idol-bug.mp4
Just start the website and make sure the donut graph looks normal.
> Fix UI bug on DTI website on team page

- .eslintrc.json
- frontend/src/API/APIWrapper.ts
- frontend/src/API/ImagesAPI.ts
- frontend/src/API/LoginAPI.ts
- frontend/src/API/MembersAPI.ts
- frontend/src/API/RolesAPI.ts
- frontend/src/API/TeamsAPI.ts
- frontend/src/Admin/DTI-Site-Deployer/SiteDeployer.tsx
- frontend/src/User/UserProfile/UserProfile.tsx
- frontend/src/UserProvider/UserProvider.tsx
- All the APIWrapper's config parameters are all about `withCredentials: true`, which is already set in APIWrapper. Therefore, there is no need to pass it again, so I removed the parameters.
- Strictified the types of APIWrapper return a little bit
As a result of this refactoring all the linter warnings are gone!
Close #27.
Go into the app to ensure that things can load, which shows that the credentials are still being correctly passed.
> Refactor frontend API calls to reduce boilerplate

- backend/README.md
- frontend/README.md
- frontend/src/environment.ts
- frontend/src/firebase.ts
I just added documentation for the frontend and backend READMEs for configuring the dev and prod Firebase instances when running IDOL locally. 
👀
Added a `useProdDb` variable in `environment.ts` for the frontend so that the frontend can be configured to use dev/prod for Google authentication during login. In #88, the frontend was unable to run locally when the backend was connected to the production firebase instance.
> Add documentation to READMEs for configuring dev vs prod Firebase instances 

- dti-website/src/components/DtiMainMenu.scss
- dti-website/src/components/DtiMainMenu.tsx
See test plan.
Navbar no longer shown in transparent state on mobile:
Expanded view has nice margin:
> [dti-website] Fix navbar on mobile

- backend/data/download-images.ts
- backend/data/firebase.ts
- backend/package.json
- yarn.lock
This pull request implements a script `download_images.ts` to download all member images from the `images` bucket in IDOL's Firebase Storage and saves them with the same name (i.e. _netid.jpg_). It does not affect any existing functionality.
None
> Script to download all member images from Firebase Storage

- backend/package.json
- backend/src/api.ts
- backend/src/dao/MembersDao.ts
- backend/src/firebase.ts
- backend/src/memberAPI.ts
- backend/src/permissions.ts
- backend/src/util.ts
- backend/tsconfig.json
- common-types/index.d.ts
- frontend/src/Admin/AdminBase/AdminBase.tsx
- frontend/src/Admin/MemberReview/MemberReview.module.css
- frontend/src/Admin/MemberReview/MemberReview.tsx
- frontend/src/Common/Search/Search.tsx
- yarn.lock
The current flow of member information change approval has a big issue: if one member's information change has something we don't want, we cannot approve others' information without leaving the bad one out.
This PR aims to fix the issue by building a per-person information change approval flow. I build an IDOL page that loads in diffs **on each member**, and allows the admin to selectively approve a subset of them. This allows the good ones to go through, without making the bad change taking hostage of the entire flow.
This PR only implements the review part. It does not alter the rest of the system yet. It currently only stores the approved members' information into a separate collection. I exposed an endpoint that fetches from that collection instead of the old collection. In the next …
> Allow approving a subset of member information change

- dti-website/pull-from-idol.ts
Update the pull-from-idol script to fetch only approved member data list. This finishes the per-member approval integration.
👀
> Update pull-from-idol script to fetch approved member data list

- backend/src/api.ts
- backend/src/dao/MembersDao.ts
- backend/src/memberAPI.ts
- frontend/src/Admin/MemberReview/MemberReview.tsx
This PR adds support for reverting a change in member information. This is helpful in several scanarios:
- Some member just puts some bad stuff that can never be accepted, so it's better to reject it.
- We put in some changes to test the system. It's handy to build some UI to revert some of the testing changes.
> Allow both accept and revert in member reviews

- backend/src/DataTypes.d.ts
- backend/src/api.ts
- backend/src/dao/ShoutoutsDao.ts
- backend/src/firebase.ts
- backend/src/permissions.ts
- backend/src/shoutoutAPI.ts
- frontend/src/API/ShoutoutsAPI.ts
- frontend/src/User/ShoutoutsPage/ShoutoutCard/ShoutoutCard.tsx
- frontend/src/User/ShoutoutsPage/ShoutoutForm/ShoutoutForm.tsx
- frontend/src/User/ShoutoutsPage/ShoutoutList/ShoutoutList.tsx
- frontend/src/User/ShoutoutsPage/ShoutoutsPage.tsx
- frontend/src/environment.ts
This pull request is the next step towards implementing the shoutouts page on IDOL. The user can now send shoutouts to other DTI members and view their given and received shoutouts from Firebase.
- Ensured that nothing breaks when users have either or both lists of shoutouts empty
- Ensure that users can’t post shoutouts for themselves
- Right now users can view their shoutouts right as they are posted, not sure if we would want to give the leads the ability to look over each shoutout before confirming that they are ok?
> shoutouts backend

- frontend/src/User/DTI48/DTI48MainGame.tsx
There is currently a subtle bug on master about keyboard control.
When you are selecting a player, you can type in using keyboard. If you type `Henry` and hit enter, then `Henry Li` will be selected, but the focus is still on the dropdown, so when the user wants to play the game using wsad, it will reopen the dropdown, which is very confusing.
This PR fixes that by force changing the key when dropdown closes (i.e. finished selection), so that the entire DOM tree will be nuked on rerender, which ensures that the dropdown will not be kept focused.
Before:
https://user-images.githubusercontent.com/4290500/117400643-10e87600-aed1-11eb-8a42-bc9207ee522d.mov
After:
https://user-images.githubusercontent.com/4290500/117400642-10e87600-aed1-11eb-8e16-7984de9538a3.mov
> [DTI48] Fix an edge case of keyboard control

- dti-website/src/components/RoleSelector.scss
- dti-website/src/components/RoleSelector.tsx
- dti-website/src/pages/apply.scss
- dti-website/src/pages/apply.tsx
Previously a header that said "Applications 👇" was added to the RoleSelector component, which was used in multiple places in the website. This resulted in the header appearing in unintended places.
The header has been factored out of the RoleSelector component and into the `apply` page ONLY, which is its intended behavior.
> Fix team page

- backend/src/api.ts
- backend/src/dao/MembersDao.ts
- backend/src/dao/SignInFormDao.ts
- backend/src/memberAPI.ts
- backend/src/members-archive/index.ts
This PR implements signin support for past members that have been removed from `members` collection, so that they can continue access the site, and most importantly, play DTI48. After this PR, the project to allow past members to play DTI48 is done.
It's achieved by making the members stored inside the archive as a fallback.
1. Temporarily remove yourself in the members collection.
2. Try to sign in. You should be able to successfully signin.
3. Try to play DTI48 as yourself in spring 2021. It should still be the default choice.
It's important to note that this does open up some security issues, although not that critical. For example, past leads will be still be able to have admin permissions. In the future,  I plan to attach an optional flag `isPastMember` so that we can distinguish …
> Allow past members to signin

- frontend/src/App.tsx
Next.JS routing is [based on filesystem](https://nextjs.org/docs/routing/introduction). For common components of all pages, it [uses the template defined in `src/pages/_app`](https://nextjs.org/docs/advanced-features/custom-app).
To prepare the eventual switch to this model, I refactored `src/App.tsx` to have a `AppContent` component with signature `({children}) => JSX.Element`. This will become the component in `src/pages/_app` when we migrate to Next.JS
Site still loads. You can login and move around pages.
> Factor out page templates to prepare for Next.js migration

- common-types/index.d.ts
Added new `TeamEvent` type to `common-types` for team event tracking 
```
interface TeamEvent {
readonly name: string,
readonly attendees: IdolMember[],
readonly uuid: string
}
```
No functional changes, only added new type
> Add TeamEvent type for team event tracking

- dti-website/package.json
- dti-website/src/components/DtiFooter.scss
- dti-website/src/components/DtiMainMenu.scss
- dti-website/src/components/DtiMainMenu.tsx
- dti-website/src/components/HeadshotCard.scss
- dti-website/src/components/MemberProfile.tsx
- dti-website/src/pages/courses.scss
- dti-website/src/pages/courses.tsx
- dti-website/src/pages/sponsor.scss
- dti-website/src/pages/sponsor.tsx
- dti-website/src/pages/team.scss
- dti-website/src/pages/team.tsx
- dti-website/src/scss/index.scss
- yarn.lock
Bootstrap 4's scss uses a lot of deprecated features, and it's causing a lot of non-actionable warnings in the build.
In this PR, I migrated it to bootstrap 5 to eliminate all the build warnings and keep things up-to-date.
Changed items:
- navbar
- footer
- profile card
- donut graph
- sponsor page and courses page buttons
Check each page to see nothing goes wrong.
> Migrate DTI website to use bootstrap 5

- dti-website/src/components/CircleProgressIndicator.scss
See https://sass-lang.com/documentation/breaking-changes/slash-div
Still looks fine
> [easy][dti-website] Use `math.div` to replace `/` in scss

- .github/workflows/ci-build.yml
- backend/tests/setup.ts
- jest.config.js
Fixed the config for jest backend testing, the original config for testing the backend wasn't finding any tests.
Changes:
- `testMatch`: changed from `<rootDir>/backend/**/*.test.ts` to `<rootDir>/**/*.test.ts'`
- `backend/tests/setup.ts`: created setup file to configure `.env` when running tests locally 
Also added Firebase private keys to repo secrets so that Firebase can be configured during test workflow 
Test step now runs `IDOL Backend Tests` in CI checks and pass
> Fix backend testing config 

- dti-website/next.config.js
- frontend/next.config.js
- Skip type checking during build since it's checked in other CI scripts
- Use rust-based swc tooling: https://nextjs.org/blog/next-11-1#adopting-rust-based-swc
CI. Preview shouldn't change.
> Speed up website builds

- frontend/src/components/Common/UserProvider.tsx
On page reload, the page would be stuck on the loading symbol.
Seemed like it was an issue with async commands executing in the wrong order in `UserProvider.tsx`
```
setUser({ email: getUserEmail(userAuth) });
cachedUser = userAuth;
```
where `setUser` was completing before `cacheduser = userAuth` causing `cachedUser` to be `null`. 
The solution in this PR is just to chain the commands with `.then()` so the assignment always finishes first. 
Check on netlify preview that sign in forms load after refresh
> Fix issue with sign in form creator page forever loading 

- frontend/src/components/Common/NavigationCard.tsx
- frontend/src/pages/admin/hidden.tsx
- frontend/src/pages/admin/index.tsx
Add `unstable: true` to a navigation card data and they will be hidden if you are not admin.
Added an example hidden page for admin. It will not be visible if you are not admin.
> [easy] A small framework to hide entry point if user is not admin

- backend/tests/data/jagger-profile.json
- frontend/src/components/Admin/EditTeam.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
Co-authored-by: Henry Li <hl738@cornell.edu>
This fixed the issue where the search bar for members was not auto-populating search results. The issue was resolved by checking that the field for a member was not null before trying to match it to what was being searched. 
Tested on local machine and was able to find a member and add/delete them from a team.
> Fix search bar error for members

- frontend/next.config.js
- frontend/src/components/Admin/SiteDeployer.tsx
- frontend/src/components/Common/FirestoreDataProvider.tsx
- frontend/src/components/Common/Search.tsx
- frontend/src/components/Common/UserProvider.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
- frontend/src/firebase.ts
- frontend/src/pages/_app.tsx
By listening these data in real-time, we can avoid API calls to the backend here and there, and make the dev experience a lot better by avoiding a lot of async calls. See https://firebase.google.com/docs/firestore/query-data/listen
I migrated some of the components to use the new API, but more remains unmigrated to keep this PR small.
Affected pages (shortout, site deployer) work without issue.
> Setup firestore listeners for members and approved members collection

- dti-website/src/components/RoleSelector.tsx
Fix regression on role selector on the teams page. Regression seems to be caused by #159 when Bootstrap version was upgraded to 5.
Current role selector:
Fixed role selector: 
Check preview
> Fix spacing on teams page role selector 

- frontend/src/components/Admin/EditTeam.tsx
- frontend/src/components/Common/FirestoreDataProvider.tsx
- frontend/src/components/Forms/UserProfile/UserProfile.test.tsx
- frontend/src/components/Forms/UserProfile/UserProfileImage.tsx
Node 16 starts to fail program when there is an unhandled promise. This happens in our frontend tests a lot since we are trying to fetch some API that we don't have enough permission, or when we are missing the context to provide info. This PR fixes all of the problems and make the tests to pass on Node 16.
`yarn test` on Node 16
> Fix frontend tests under Node 16

- frontend/src/components/Admin/EditTeamEvent.tsx
- frontend/src/components/Admin/TeamEventDetails.module.css
- frontend/src/components/Admin/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEventForm.module.css
- frontend/src/components/Admin/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvents.module.css
- frontend/src/components/Admin/TeamEvents.tsx
- frontend/src/pages/admin/team-events.tsx
This pull request is the next step towards implementing tracking team event credits on IDOL. On the details page, admin members can edit the details of existing team events.
> edit existing team events

- frontend/src/components/Admin/AddUser.module.css
- frontend/src/components/Admin/AddUser.tsx
- frontend/src/components/Admin/AdminShoutouts.module.css
- frontend/src/components/Admin/AdminShoutouts.tsx
- frontend/src/components/Admin/EditTeam.module.css
- frontend/src/components/Admin/EditTeam.tsx
- frontend/src/components/Common/UserProvider.module.css
- frontend/src/components/Common/UserProvider.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.module.css
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
- frontend/src/components/Forms/UserProfile/ProfileImageEditor.module.css
- frontend/src/components/Forms/UserProfile/ProfileImageEditor.tsx
- frontend/src/components/Homepage/Spotlight.module.css
- frontend/src/components/Homepage/Spotlight.tsx
- frontend/src/pages/App.css
- frontend/src/pages/_app.tsx
Use classnames to replace inline styles. Some of the rules have to have `!important` added because the default semantic UI css is too specific. This is probably one of the reasons we should eventually replace it, but it's probably a project for next semester...
Affected pages all look fine:
> Use classnames instead of inline styles

- backend/src/api.ts
- backend/src/team-events-imageAPI.ts
- common-types/index.d.ts
This pull request implements the backend for handling proof images for Team Event Credit. It does the following:
- sets proof image
- get proof image
- get all proof images for a member
- delete a proof image
- delete all proof images for a member
The images are stored in Firebase as `eventProofs/${netID}/{$name}` where `netID` is for identifying the user and `name` is the event name for which proof is uploaded.
Not tested yet.
> Add backend api for handling event proof images

- frontend/src/components/Forms/UserProfile/UserProfile.tsx
This PR fixes some issues with the profile editor #222. It makes pronouns a required field and shows the error modal when not all fields are filled out.
This pull request is the first step towards implementing feature Foo
> make pronouns required and show error modal

- dti-website/src/data/apply.json
Fixes typo communicate -> communicative
communicative is spelled correctly and is an adjective
> Fix typo in developer apply section

- dti-website/src/data/all-projects.json
Fix typo on https://www.cornelldti.org/projects/zing
"studetnts" --> "students" 
👀
> Fix typo in zing description

- backend/src/DataTypes.d.ts
- backend/src/dao/TeamEventsDao.ts
- backend/tests/TeamEventsAPI.test.ts
- backend/tests/TeamEventsDao.test.ts
- common-types/index.d.ts
- frontend/src/components/Admin/EditTeamEvent.tsx
- frontend/src/components/Admin/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvents.module.css
- frontend/src/components/Admin/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
This PR is the next step towards implementing team event credits on IDOL. It allows admins to see a list of pending credit requests, view the request's attached image, and decide whether or not to approve the credit request.
> admins approve/reject credit requests

- common-types/index.d.ts
- frontend/package.json
- frontend/src/components/Admin/AdminCandidateDecider.module.css
- frontend/src/components/Admin/AdminCandidateDecider.tsx
- frontend/src/pages/admin/candidate-decider.tsx
- frontend/src/pages/admin/index.tsx
- yarn.lock
This pull request is the first step towards integrating Candidate Decider into IDOL. It adds an admin page for creating new "instances" of Candidate Decider where IDOL admins can upload a csv file of the application results spreadsheet to create a new instance. 
The uploaded csv file is parsed into `CandidateDeciderInstance` type: 
```
interface CandidateDeciderRating {
readonly reviewer: IdolMember;
readonly rating: number;
}
interface CandidateDeciderComment {
readonly reviewer: IdolMember;
readonly comment: string;
}
interface CandidateDeciderCandidate {
readonly responses: any[];
readonly id: number;
ratings: CandidateDeciderRating[];
comments: CandidateDeciderComment[];
}
interface CandidateDeciderInstance {
readonly name: string;
readonly headers: string[];
readonly candidates: …
```
> Candidate Decider admin page 

- frontend/src/components/Common/FirestoreDataProvider.tsx
- frontend/src/environment.test.ts
- frontend/src/environment.ts
This PR adds a feature that allows testing as a non-admin user locally. You can do this by setting `allowAdmin` in `frontend/src/environmen.ts` to `false` and you will effectively be a non-admin user on IDOL. 
N/A
> Testing as non-admin user locally

- backend/src/api.ts
- backend/src/dao/TeamEventsDao.ts
- backend/src/team-eventsAPI.ts
- frontend/src/API/TeamEventsAPI.ts
- frontend/src/components/Admin/EditTeamEvent.tsx
- frontend/src/components/Admin/TeamEventDetails.module.css
- frontend/src/components/Admin/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvents.tsx
- frontend/src/environment.ts
- frontend/src/utils.ts
This pull request connects the admin forms for the team event credit to the api to create new events and display their details. The backend endpoints were updated to support the following.
next pr:
tested the endpoints and above functionality locally; data collection was updated as expected and was displayed on frontend
**Creation of Team Event and Fetching all Team Events**
**Team Event Details**
> Connect admin forms for team event credit to the api and display details

- backend/src/api.ts
- backend/src/team-events-imageAPI.ts
- frontend/src/API/APIWrapper.ts
- frontend/src/API/ImagesAPI.ts
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
This pull request implements image uploading for the team event credit form. The image name (eventProofs/[netid]/[timestamp]) is saved as part of the `TeamEventAttendance`.
> Implement image uploading for team events

- common-types/index.d.ts
Add types for [Dev Portfolio Automation feature ](https://www.notion.so/Dev-Portfolio-Automation-66804d95ee1d4e55b2d1426b268405cc)
```
interface DevPortfolio {
name: string;
deadline: number;
earliestValidDate: number;
submissions: DevPortfolioSubmission[];
}
interface DevPortfolioSubmission {
member: IdolMember;
openedPR: string;
reviewedPR: string;
status: 'valid' | 'invalid' | 'pending';
}
```
Read dev portfolio automation feature proposal and confirm that type declarations are reasonable
> New types for dev portfolio automation 

- backend/src/dao/SignInFormDao.ts
- backend/src/signinformAPI.ts
- backend/tests/SignInFormDao.test.ts
This PR moves validation logic from the sign-in form DAO to its API. 
There is also a bug fix with boolean Promises that resulted in always-true or always-false values (explanation [here](https://www.aleksandrhovhannisyan.com/blog/async-functions-that-return-booleans/)).
Revised unit test suite to account for removed validation from DAO. Manually tested API for edge and typical cases:
> Refactor `SignInFormDAO` and `signinformAPI`

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This PR fixes the issue on the admin shoutouts page that @riyajaggi discovered. Since shoutouts use `DocumentReference` for the givers and receivers, we get an error for former members (i.e. members that are no longer n the `members` collection). 
The solution implemented in this PR is the replace the name of the giver/receiver with `(Former member)` if the giver/receiver is `undefined.`
Check deploy preview to ensure that the admin shoutouts page is loading 
In the future, we should probably consider implementing a more robust system in the backend for dealing with document references to former members (possibly by looking through archived members).
> [bug-fix] Fix admin shoutouts for former members 

- backend/src/API/siteIntegrationAPI.ts
- backend/src/api.ts
This PR renames `siteIntegration.ts` to `siteIntegrationAPI.ts` in the initiative to standard BE file names 
N/A - No functionality changes
> [RFC] Rename and move siteIntegration.ts

- dti-website/src/pages/_app.tsx
This PR attempts to add Google Analytics to the DTI website. 
No functionality changes but ensure that the entire website looks good (I will check the Google Analytics page to make sure tracking is working)
> Add Google Anaytics to DTI website 

- backend/src/utils/githubUtil.ts
This PR revises the placeholder logic for determining whether a PR or review is trivial. 
- There is no way that an opened PR can be trivial. This allowed for some unnecessary API calls for validating an opened PR to be removed 
- A review can be trivial if it has less than 10 words. This is as opposed to a minimum character count so that things like [Henry's beautiful artworks](https://github.com/cornell-dti/idol/pull/267#pullrequestreview-929767102) dont count.
- Determining whether a collection of comments is trivial was factored out in to a separate function to allow for easier modification later if course policy changes
No changes to functionality.
> Determine whether PR or review is trivial for dev portfolio automation

- backend/tests/types.d.ts
This PR is a QOL change that adds a `types.d.ts` to `backend/tests/` so that the backend tests can reference `common-types`. This should remove the type not found errors in VSCode. 
No changes in functionality -- all existing tests should pass.
> [QOL] Add type references for backend tests 

- .github/workflows/pull-from-idol.yml
This PR adds config to the `Pull from IDOL` workflow to allow the workflow to be triggered manually from the GitHub UI. 
N/A
> [QOL] Allow Pull from IDOL to be triggered manually 

- frontend/src/components/Admin/AdminCandidateDecider/AdminCandidateDecider.tsx
- frontend/src/components/Admin/SignInForm/SignInFormCreator.tsx
On the admin side, there are forms to make a sign-in link and to create a candidate decider instance. Previously, after the form is submitted, the input in each field remains there, so the user would have to manually delete the input to submit new data. This PR clears the form fields by simply clearing the different states upon clicking the submit button.
1a
1b
2a
2b
> Clear fields of admin forms after each submission

- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
Debug dev portfolio admin page -- Fixed validation to make sure the deadline is not before the earliest valid date. Improved error messages for date-related validation errors.
[Notion issue](https://www.notion.so/cornelldti/Debug-and-Improve-Dev-Portfolio-Admin-Page-43fe2466a786404a877231f7fc541ec2) 
- Creating a dev portfolio when the deadline is the current date should be successful 
- Trying to create a dev portfolio where the deadline is before the earliest valid date should be unsuccessful 
I think ```Maybe: allow for time selection with deadline (or at least say that the deadline is 11:59pm on the chosen day etc.)``` can be addressed in a separate PR.
> Debug admin dev portfolio form

- frontend/src/components/Common/NavigationCard/NavigationCard.module.css
- frontend/src/components/Common/NavigationCard/NavigationCard.tsx
Centers navigation cards on a smaller screen 
Currently, navigation cards look like this on a smaller screen which doesn't look great. 
Updated navigation cards:
[Larger project](https://www.notion.so/cornelldti/Make-IDOL-more-mobile-friendly-a86a30e44322432ca848aa8e835e67e7)
[Specific issue](https://www.notion.so/cornelldti/Admin-forms-games-card-pages-4a681a37beaf4b869a8796cef0d7feef)
Navigation cards for `Forms`, `Admin`, and `Games` pages should be centered on a smaller screen.
> Center navigation cards on small screen

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Tested both fixes. Below is a screenshot of typing in the "Reviewed PR" box and the text shows up correctly and does not affect what is in the "Opened PR" section.
> Fixed Bugs in Dev Portfolio Submission Page

- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.module.css
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.module.css
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
- frontend/src/components/Homepage/Homepage/Homepage.tsx
This PR is the first step towards making the IDOL frontend more mobile-friendly. It addresses responsivity for the shoutouts page and contains some other general refactoring changes.
Changes:
- Made shoutouts form and shoutouts display responsive for mobile screens
- Created `.module.css` file for `ShoutoutForm` component and removed inline CSS 
- Changed `ShoutoutForm` component to update given shoutouts when a new shoutout is submitted  
[Notion link](https://www.notion.so/cornelldti/Shoutouts-form-dbb163886d4e4704a88936e83aad411b)
- Shoutout page should look the same on desktop 
- Shoutout page should be responsive for mobile 
- Newly given shoutouts should appear automatically without needing to refresh the page 
You can get a mobile sized version of the page by right click on page -> …
> Shoutouts page refactor 

- backend/src/API/devPortfolioAPI.ts
- backend/tests/DevPortfolioAPI.test.ts
- frontend/src/pages/_app.tsx
Adds testing for the API layer for dev portfolios
Tests:
- Permissions tests for getting, deleting, and creating new dev portfolios 
- Logic tests for whether or not a portfolio can submitted to a dev portfolio assignment (i.e. making sure that a submission can only be made to an assignment that is currently open) 
[Notion link](https://www.notion.so/cornelldti/Backend-Test-dev-portfolio-API-ec5eb701160e4d5ba8256975e242f16f)
All tests should pass. Tests should hopefully cover all the logic in the API layer for Dev Portfolios.
> Add tests for dev porfolio api layer

- backend/src/utils/githubUtil.ts
This PR fixes a bug in the validation where member's usernames must exactly match the case of their username on GitHub, otherwise their comments and PRs are filtered out as if it was a different user.
For example, the username derived from profile page github.com/jacksonstaniec is `jacksonstaniec`, and will now match comments and PRs opened by user `JacksonStaniec` on GitHub.
[Notion](https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=8bafac625b944c7198d93fc3c3a938ed&pm=s)
Tests for this functionality will be included in the `githubUtil.ts` test suite ([Notion task](https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=c88bce9db3d043c29a9bb42166fec4a7&pm=s)).
For now, submissions from users that previously failed should work as expected …
> Change Dev Portfolio validation to be case-insensitive

- backend/src/utils/githubUtil.ts
This PR uses a GitHub access token to authenticate API calls during made during dev portfolio validation, increasing the rate limit from 60 calls per hour to 5000 calls per hour. 
We can estimate that each dev portfolio submission has 2 opened PR links and 2 reviewed PR links (even though only 1 of each is required by the assignment). It costs 1 API call to validate an opened PR, and 4 API calls to validate a reviewed PR. So, this new rate limit allows the dev portfolio to validate up to 500 submissions per hour. 
[Notion](https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=2e4df035eb8d41c98fde53062e110baa&pm=s)
Check the API rate limit by running:
```typescript
octokit.rest.rateLimit.get().then((res) => console.log(res.data.rate));
```
with `octokit` initialized …
> Increase GitHub API Rate Limit

- backend/src/API/devPortfolioAPI.ts
- backend/src/api.ts
- backend/src/dao/DevPortfolioDao.ts
- backend/tests/DevPortfolioAPI.test.ts
- backend/tests/DevPortfolioDao.test.ts
- frontend/src/API/DevPortfolioAPI.ts
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/pages/admin/dev-portfolio/[uuid].tsx
- frontend/src/pages/forms/dev-portfolio-submissions/[uuid].tsx
- frontend/src/pages/forms/submissions/[uuid].tsx
- Users were previously not able to see their previous submissions. Now, users can see dev portfolios that they’ve submitted to, and a table of their submissions, using analogous components to the admin dashboard.
- Users are not able to see the validation results, just the submissions. We've hidden their results for now. The results are only available from the admin side.
- Added getAllDevPortfoliosNonAdmin and getDevPortfolioNonAdmin routes, which only return information about the dev portfolios that are accessible to a non-admin (aka, deadline, earliest date, and that member's submissions ONLY). Trying to access the admin-only routes as a non-admin still throws a permissions error. Admins can call the nonAdmin route, which returns information only as if they were a non-admin.
- …
> Members Can View Past DP Submissions

- backend/src/utils/githubUtil.ts
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Bug fix
Regex currently doesn't support URLs that contain . (periods).
i.e. https://github.com/cornell-dti/course-reviews-react-2.0/pull/362 did not work.
Manually tested and successfully submitted an example URL
We should probably look into adding other symbols eventually too, pushing this one for now because it's urgent.
> Bug fix: add . to regex

- backend/src/API/devPortfolioAPI.ts
- backend/tests/DevPortfolioAPI.test.ts
The date from the date picker component wasn't specifying the hours/minutes/seconds of the dates enough so users could be unable to make submissions even before the deadline hadn't actually passed. This PR makes code changes on the backend to specify the hours/minutes/seconds for these dates. For DP deadline, set the time of the deadline to 23:59:59 on that date. For DP earliest valid date, set the time on that date to 00:00:00. 
[Notion link](https://www.notion.so/cornelldti/DP-Deadline-and-earliest-valid-dates-should-be-start-and-end-of-day-7aa220f353d446d98d7c0d8d1d9557d1)
Added unit testing to ensure that dev portfolio is created with correct dates.
Test by creating a dev portfolio with the deadline being today and ensuring that you can make submissions.
> Set hours/minutes/seconds for deadline and earliest valid dates

- backend/src/API/devPortfolioAPI.ts
- backend/src/api.ts
- backend/src/dao/DevPortfolioDao.ts
- backend/tests/DevPortfolioAPI.test.ts
- frontend/src/API/DevPortfolioAPI.ts
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.module.css
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
Adds the ability for leads/admins to request a regrade of all submission for a dev portfolio 
[Notion link](https://www.notion.so/cornelldti/DP-View-Manually-Trigger-Regrade-6e5e2e4eda1044758e129ebecba93078)
Added unit testing for `devPortfolioAPI.regradeSubmissions`.
> Add regrade submissions functionality for dev portfolios

- frontend/package.json
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- yarn.lock
This pull request implemented "export to csv" functionality for dev leads to easily grade dev portfolio submissions. It includes the columns `name`, `netid`, `opened_score`, `reviewed_score`, and `total_score`. Submissions are sorted by netid and the csv only includes one submission from each member. 
If a dev portfolio assignment has no submissions, an error message will pop-up. 
- Manually tested and checked that all submissions were present in CSV with correct values.
- All submissions were correctly sorted by netID.
- Tested dev portfolio with multiple submissions from one member. 
- Tested dev portfolio with no submissions.
> Export Dev Submissions to CSV

- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
Changes PR link behavior to open in a new tab instead of in the current tab. 
[Notion link](https://www.notion.so/cornelldti/Admin-DP-dashboard-links-should-open-new-tab-2238d09419a845b2ba4bd8c67f6154c4)
Clicking on a PR link should open the link in a new tab
> PR links open new tabs 

- backend/src/dao/ShoutoutsDao.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
Fixed bug in Shoutouts page so that shoutouts marked as anonymous show up as "From: Anonymous" in the admin Shoutouts page and the member's Shoutout page. 
Manually tested that shoutouts were showing up with correct and matching information in member's view and admin view.
Here is the member view:
Here is the admin view:
> Fixed Anonymous Bug in Shoutouts Page

- backend/src/API/shoutoutAPI.ts
- backend/src/dao/ShoutoutsDao.ts
- backend/src/types/DataTypes.d.ts
- backend/tests/ShoutoutsDao.test.ts
- frontend/src/API/ShoutoutsAPI.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutCard.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.module.css
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.module.css
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
- frontend/src/pages/forms/index.tsx
- Unified Shoutouts type by removing variant without the `giver` field
- Updated Shoutout `recipient` to be type `string` instead of `IdolMember`
- Removed "Received Shoutouts" section from members Shoutouts page
- Removed Shoutouts with old type from dev Firebase 
- Updated Dao tests for correct type
- Manually tested that the Shoutouts form works and collects the correct information
- Ensured that anonymous and non-anymous Shoutout functionality still works
- Verified that correct Shoutout information appears in admin view as well as member view
- Ensured that submitted Shoutouts appear in dev Firebase
> Unified Shoutouts type and removed requirement that recipient be IDOL user

- common-types/index.d.ts
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/components/Modals/DevPortfolioTextModal.tsx
This PR is the first step to be able to associate text with a dev portfolio submission. Just for the TPM paragraph requirement:
[Notion](https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=224afb83e4274d219f257c43d2f4786e&pm=s)
- text area should not show for non-TPMs
- details view should not change if no submissions have text fields
Text area on submission form:
View from admin details:
View from user details:
Clicking "Show Text"
This text field format may be able to be reused for non-TPMs as an area to explain why they were granted an exception from certain PR requirements ([Notion task](https://www.notion.so/cornelldti/DP-Add-Other-Category-to-Allow-Exceptions-1f4c5b41c7cd48c488ac2b22b668f62d)).
> Add text field for TPM dev portfolio submission.

- backend/src/API/devPortfolioAPI.ts
- backend/src/types/DataTypes.d.ts
- backend/src/utils/githubUtil.ts
- backend/tests/DevPortfolioAPI.test.ts
- backend/tests/data/createData.ts
- common-types/index.d.ts
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.module.css
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/environment.ts
Added support for late deadline for dev portfolios. A late deadline is optional when creating a new dev portfolio.
[Notion link](https://www.notion.so/cornelldti/Late-Submissions-for-Dev-Portfolios-30da8b9dbefb4f6298906f4023b6f38c)
- Updated backend unit testing 
- Test validation for creating a new portfolio (i.e. late deadline is after the normal deadline, etc.) 
- Test that late submissions are marked as late (and that submission before the deadline isn't marked late)
- Test that late submissions have a `*` by the submission status 
- Test that a dev portfolio should behave normally if the late deadline wasn't set 
- Test that you can't submit a portfolio past the late deadline 
- Test that late deadline is used (only if it was set) as the "end date" for submission validation 
- ~~CSV …
> Add late deadline feature 

- frontend/src/components/Candidate-Decider/CandidateDeciderBase.module.css
- frontend/src/components/Candidate-Decider/CandidateDeciderBase.tsx
- frontend/src/pages/_app.tsx
- frontend/src/pages/forms/index.tsx
This PR removes access to broken pages or features that are not ready for release.
- Removed "Games" tab
- Add message if user's arent supposed to see candidate decider instances
- Hide shoutouts feature until ready for use
Non-admin view
> Hide broken/in-progress pages from users.

- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
- backend/src/dao/TeamEventsDao.ts
- frontend/src/API/TeamEventsAPI.ts
- frontend/src/components/Admin/TeamEvent/TeamEvents.module.css
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Modals/ClearTeamEventsModal.tsx
- frontend/src/environment.ts
Allow admins to delete all team events on the admin dashboard 
[Notion link](https://www.notion.so/cornelldti/Admin-TEC-Add-ability-to-delete-events-2fb725f13de345b1bb1208545b7d2547)
Test locally -- You will need to create team events/request credit since all existing ones have been deleted.
> Allow admins to delete all team events 

- backend/src/API/shoutoutAPI.ts
- backend/src/api.ts
- backend/src/dao/ShoutoutsDao.ts
- backend/src/types/DataTypes.d.ts
- backend/src/utils/permissionsManager.ts
- backend/tests/ShoutoutsDao.test.ts
- frontend/src/API/ShoutoutsAPI.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.module.css
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
This pull request is the first step towards implementing hiding shoutouts in the admin view. 
Manually tested using dev environment. Also added Dao test to test `hideShoutout()` endpoint.
https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=d932c4d29e014f0481afb3016bcdeb39&pm=s
Next step will be to add 3-part button to toggle between hidden, unhidden, and all shoutouts.
> Hide shoutouts from admin view

- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
This PR resets the form to be anonymous by default after submitting, and makes the checkbox in sync with whether the shoutout is anonymous or not.
Try submitting 2 anonymous shoutouts in a row, then uncheck the box to send a non anonymous one
> Fix bug with anonymous shoutouts

- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
- backend/src/dao/TeamEventsDao.ts
- common-types/index.d.ts
- frontend/src/API/TeamEventsAPI.ts
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
- Added `TeamEventInfo` type with the metadata for `TeamEvent` type 
```
interface TeamEventInfo {
readonly name: string;
readonly date: string;
readonly numCredits: string;
readonly hasHours: boolean;
readonly uuid: string;
}
```
- Member-side team event form only retrieves `TeamEventInfo` type now so that members aren't able to see who has pending/approved TEC requests 
- Changed the way that new TEC requests are handled so that frontend doesn't need access to the `TeamEvent` object 
- Changed the way that the TEC dashboard for members retrieves/determines the pending/approved requests for a member 
- Only leads/admins have permissions to call the `/getAllTeamEvents` endpoint now 
[Notion link](https://www.notion.so/cornelldti/Member-TEC-Security-Fix-644f57516d0a474688a5d3c5878bbdec)
- …
> Add meta data type for TEC to patch security issue 

- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
This PR allows users to see the results of validation on their submission. This was previously blocked until we implemented the ability for admins to override the results of the validation:
- #354 
Changes:
[Notion](https://www.notion.so/cornelldti/Idol-FA22-5a158866a8a1472c98b1f3c042b480f8?p=de7e03efa5b44f1d81e82b641aa0322e&pm=s)
See that validation results show up in non-admin view, but cannot override the results.
> Show dev portfolio validation results in non-admin view.

- backend/src/API/shoutoutAPI.ts
- backend/src/api.ts
- backend/src/dao/ShoutoutsDao.ts
- frontend/src/API/ShoutoutsAPI.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This PR refactors the backend for hiding shoutouts. Hiding a shoutout is now handled through `hideShoutout` in the API layer which only uses the shoutout's uuid. This makes it possible to create a separate `updateShoutout` endpoint if we ever wanted to grant users the ability to edit existing shoutouts. 
N/A
Should be able to hide shoutouts without any issue
Is there supposed to be a way to unhide shoutouts from UI/is this a planned feature?
> Refactor hiding shoutouts backend

- frontend/src/components/Admin/TeamEvent/TeamEventForm.tsx
Fixes bug that prevented 0.5 credit team events from being created 
[Notion link](https://www.notion.so/cornelldti/TEC-Bug-Can-t-set-event-credits-amount-to-0-5-63dbafe26c504e1499ab7f3691c18901)
Should be able to create a 0.5 credit team event
> fix bug to allow 0.5 credit team events to be created

- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
Added loading indicators on admin TEC dashboard and TEC details page to indicate that data is still loading when fetching from the backend. 
- `/admin/team-events` 
- `/admin/team-events/<uuid>`
[Notion link](https://www.notion.so/cornelldti/Admin-TEC-form-loading-indicator-a288d04dc48a4fdb82d62a25ce297932)
Loading indicator should appear when fetching from the backend. Some version of "No results" should still be displayed if the data is empty after fetching from the backend.
> Add loading indicators on TEC admin-side 

- backend/src/API/signInFormAPI.ts
- backend/src/api.ts
- backend/src/dao/SignInFormDao.ts
- backend/src/types/DataTypes.d.ts
- common-types/index.d.ts
This PR is a step towards adding optional questions to sign-in forms. It adds backend support to make it possible to create sign-in forms with an optional prompt and to require sign-in requests to have a response to the prompt if the form has a prompt. 
[Notion link](https://www.notion.so/cornelldti/Sign-in-Option-for-Adding-Questions-692bec37614d48a39b3d51982acc8858) (doesn't close this ticket) 
There isn't really a good way to test this at the moment... But check the deploy preview to ensure that the user-facing functionality hasn't broken. The sign-in backend is missing a test suite ;~;. Might be worth it to add a test suite for sign-in feature in the future.
> Add backend support for sign-in form questions

- backend/src/API/devPortfolioAPI.ts
- backend/tests/DevPortfolioAPI.test.ts
Add validation in `createNewDevPortfolio` to validate the new dev portfolio's name, earliestValidDate, deadline, and lateDeadline. 
[Notion link](https://www.notion.so/cornelldti/DP-Admin-Add-validation-for-creating-new-DP-assignment-1958f66c24254272a93fbdda0c7fe5a6)
Added tests to verify that the validation works
> Add backend validation for creating new dev portfolio 

- backend/src/api.ts
- frontend/src/API/MembersAPI.ts
- frontend/src/components/Common/FirestoreDataProvider.tsx
Add a message when a user that logs in is not registered as IDOL member. Also add a sign out button to allow users to logout in case the user accidentally logged in with a different email address. 
[Notion link](https://www.notion.so/cornelldti/Frontend-Gracefully-handle-login-for-non-members-a971c61611f64db5814aeae2b1e8b7b9)
- Login with non @cornell.edu email address -- the error message and sign out button should appear. 
- Sign out button should log you out 
- Login with your @cornell.edu email address -- the error message should not appear
> Add message and sign out button if signed in user is not idol user

- backend/src/API/shoutoutAPI.ts
- backend/src/api.ts
- frontend/src/API/ShoutoutsAPI.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.module.css
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This pull request adds more filtering functionality for the admin view of shoutouts.
(https://www.notion.so/cornelldti/Shoutouts-Add-switcher-to-filter-hidden-shoutouts-e500323c198f4b278541214be232e1ca)
Manually tested that each of the 3 buttons worked and that shoutouts show up with correct information.
> add three view button for admin shoutouts view

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This PR addresses small comments made in PR #381.
- Making ViewMode type to filter Shoutouts by view.
- Changing button color to indicate which view is currently on the page. 
A future PR will have to be made to refactor this module so that we need less `important` tags for this frontend.
> Shoutouts page formatting changes

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
This PR refactors the dev portfolio PR inputs into a separate reusable component. This is part of the effort to add the "other" category for dev portfolios (more info about that [here](https://www.notion.so/cornelldti/DP-Add-Other-Category-to-Allow-Exceptions-8873daf2380648d7b9a78b147c1eb02b)).
N/A
Existing functionality with adding pr links should work as before.
> Dev portfolios - Refactor PR inputs into a reusable component

- .github/workflows/ci-build.yml
- .github/workflows/pull-from-idol.yml
- .github/workflows/update-dev-db.yml
Specifies node version for GitHub actions to the version specified in `.node-version`
[Notion link](https://www.notion.so/cornelldti/Error-in-GitHub-Build-Workflow-1d745b7cdf7b43dcbb325616a4a77829?pvs=4)
CI checks should pass now
> Specify node version to .node-version file version for GitHub actions

- .github/workflows/ci-build.yml
- .github/workflows/pull-from-idol.yml
- .github/workflows/update-dev-db.yml
- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
The leads have decided not to have a separate community event tally this semester. However, this may be released in future semesters, so for now we should hide the ability to make Team Events "community" events, and hide the tally for community events from users.
[Notion](https://www.notion.so/cornelldti/Idol-SP23-e65533742dca4f898581cc5c496e821e?p=125511cf68374e268cc4edf42e88ec9b&pm=s)
Manually test to see that community events can no longer be created on the admin side, and that community event tallies are not visible on the member side.
I used a variable so we can toggle the community event visibility, instead of removing it or commenting it out. It is still spread out across several files which is not ideal, so im open to suggestions on how to accomplish this better.
> Temporarily disable community events for TEC

- backend/scripts/update-dev-db.ts
- backend/src/firebase.ts
- backend/src/utils/firebase-utils.ts
Refactored the `configureAccount` function for backend Firebase config to be one function in `firebase-utils.ts` that can be used for the backend functions and various scripts. 
N/A - This is an initial PR for setting up a cronjob to send profile update notification emails. 
Backend should work as before for prod and dev Firebase instances and existing cronjobs should run with no issue.
> Refactor backend Firebase config 

- .github/workflows/idol-notifications.yml
- backend/package.json
- backend/scripts/send-idol-notifications.ts
- backend/src/nodemailer.ts
Add cronjob that sends email notifications to IDOL admins if there are unapproved profile updates. The cronjob should run everyday at 6pm (I think 7pm with daylight savings). 
N/A
Tested the script locally, won't be able to test cronjob until this is merged.
> Add email notification cronjob for profile updates

- .github/workflows/idol-notifications.yml
- backend/scripts/send-idol-notifications.ts
Configured GitHub action for IDOL notifications to read oauth secrets for sending emails and added proper handling of errors for failed email sending. 
N/A
👀
> Handle errors and configure secrets for notification job

- backend/scripts/send-idol-notifications.ts
https://github.com/cornell-dti/idol/pull/407/files introduced a warning that keeps coming up on each PR. This PR gets rid of that by adding the return type to `sendMemberUpdateNotifications`.
> Add return type to sendMemberUpdateNotifications()

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
- broke up the `if` block in `updateShoutouts` into three blocks:
- first one checks if the date range is valid
- second one updates `allShoutouts` by calling `getAllShoutouts()` if `allShoutouts` is empty
- third one filters `allShoutouts` to display only shoutouts that are in the date range and/or hidden if it is not empty
- added `allShoutouts` to the dependency array for `updateShoutouts`
https://www.notion.so/cornelldti/Shoutouts-Fix-excess-reads-c9c10c482b644ae3a05e07f46f1b3b05?pvs=4
- reloading the page still makes a call to the API, which allows users to fetch any additional shoutouts if they were added after the page loaded
> updateShoutouts only fetches when allShoutouts is empty

- backend/package.json
- backend/src/API/devPortfolioAPI.ts
- backend/tests/DevPortfolioAPI.test.ts
- backend/tests/data/createData.ts
- frontend/package.json
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Admin/SignInForm/SignInFormCreator.tsx
- frontend/src/components/Common/SignIn/SignIn.tsx
- yarn.lock
The backend create dev portfolio endpoint now sets deadlines to end of the day in the `America/New_York` time zone (and also the start of the day for earliest submission). Previously, it was using the local time zone of the server (which was not the expected behavior).
Also updated the portfolio submission UI's text, table, and late icon. Previously, only the date was shown; now, it is clear when something is past the deadline. The Table header was also bugged.
Ticket: <https://www.notion.so/cornelldti/DP-Bug-Deadlines-are-not-in-EST-8de856d9a9d14261accb5afbf3c91669?pvs=4>
Instead of doing logic in the test files, updated tests with hard-coded values.
For some reason, when closing the sign-in popup (instead of signing in), the promise returns an error for popup cancelled, which was not …
> update time labels for portfolio

- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
Closes two tickets: Change frontend TE attendance object and Team event submission bug. 
Add a check to make sure team event has hours before validating that the number of hours submitted is under 0.5.
Also only submit the hours field if the event hasHours, otherwise just override the field to submit `undefined`.
https://www.notion.so/cornelldti/Change-frontend-TE-attendance-object-7077ac178e2442f0a4f8490f70ad1325?pvs=4
https://www.notion.so/cornelldti/Team-event-submission-bug-a984ffeb39e34a2fabc752f7b3aadead?pvs=4
Manual testing
> Change frontend TE attendance object and Team event submission bug

- backend/src/api.ts
- backend/src/firebase.ts
- frontend/src/API/MembersAPI.ts
- frontend/src/components/Common/FirestoreDataProvider.tsx
This PR restricts access to the staging API to only admins.
[Notion link](https://www.notion.so/cornelldti/Staging-Env-Only-allow-admins-to-access-the-staging-site-4ed8bac0895845b18790d25bfe8179c9?pvs=4)
If you remove yourself from the cornelldti-idol-dev `admins` collection, you shouldn't be able to access staging anymore and should see a staging specific error message.  
I also edited Firestore rules to limit reading members to only admins
> Restrict staging to only IDOL admins

- backend/src/API/memberAPI.ts
- backend/src/api.ts
- backend/src/dao/MembersDao.ts
This PR attempts to reduce the number of db reads when a user is logging in from the frontend. Previously, when a user logins in, the client hits the `/isIDOLMember/:email` endpoint which reads all documents from the `members` collection. This PR changes the endpoint to only read a single document with the user's email. 
N/A
Should still be able to login with your @cornell.edu email and see error message with non-@cornell.edu email.
> Reduce db reads on login 

- backend/tests/data/createData.ts
- createData should have all mock data align with the current types defined in `index.d.ts`
- VSCode has no "compilation errors" anymore for `createData.ts`
[](https://www.notion.so/cornelldti/Idol-SP23-e65533742dca4f898581cc5c496e821e?p=365deb41d6e64398a51ed9acd4e99fd8&pm=s)
Unit tests still pass.
- In the future, we should figure out a way to catch these type errors in general so the types in `index.d.ts` don't become out of sync with the mock data. Right now, when we see "compilation errors" in `createData.ts` we seem to just ignore them.
> Fix mock data in createData.ts

- backend/src/API/candidateDeciderAPI.ts
- backend/src/API/devPortfolioAPI.ts
- backend/src/API/memberAPI.ts
- backend/src/API/shoutoutAPI.ts
- backend/src/API/teamAPI.ts
- backend/src/dao/BaseDao.ts
- backend/src/dao/CandidateDeciderDao.ts
- backend/src/dao/DevPortfolioDao.ts
- backend/src/dao/MembersDao.ts
- backend/src/dao/ShoutoutsDao.ts
- backend/tests/DevPortfolioAPI.test.ts
- backend/tests/DevPortfolioDao.test.ts
- backend/tests/MembersDao.test.ts
- backend/tests/ShoutoutsDao.test.ts
- backend/tests/SignInFormDao.test.ts
This PR adds a new `BaseDao` class that is intended to serve as a parent class for the other Dao classes by implementing some of the shared CRUD logic. 
Dao classes that inherit from `BaseDao` need to supply the data type, the db data type, a Firestore collection, a function for materializing data from a document, and a function for serializing data into a document. 
```
export default abstract class BaseDao<E, D> {
readonly collection: firestore.CollectionReference<D>;
readonly materializeData: (d: D) => Promise<E>;
readonly serializeData: (e: E) => Promise<D>;
constructor(
collection: firestore.CollectionReference<D>,
materializeData: (d: D) => Promise<E>,
serializeData: (e: E) => Promise<D>
) {
this.collection = collection;
this.materializeData = materializeData;
this.serializeData = …
```
> Add BaseDao class and refactor daos 

- backend/src/dao/BaseDao.ts
- backend/src/dao/DevPortfolioDao.ts
- backend/src/dao/ShoutoutsDao.ts
This PR adds an abstraction to `BaseDao` for filtering Firestore queries. 
We have a new interface that defines a filter:
```
interface FirestoreFilter {
field: string;
comparisonOperator: FirebaseFirestore.WhereFilterOp
value: any
}
```
These filters can be passed to `BaseDao.getDocuments` as a list to perform filtering. 
e.g. instead of 
```
async getShoutouts(email: string, type: 'given' | 'received'): Promise<Shoutout[]> {
const givenOrReceived = type === 'given' ? 'giver' : 'receiver';
const shoutoutRefs = await this.collection
.where(givenOrReceived, '==', memberCollection.doc(email))
.get();
return Promise.all(
shoutoutRefs.docs.map(async (shoutoutRef) => materializeShoutout(shoutoutRef.data()))
);
}
```
we can have
```
async getShoutouts(email: string, type: 'given' | 'received'): …
```
> Abstract firestore filtering in BaseDao 

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
~~This PR fixes a couple of small issues with the dev portfolio form regarding submission:
- ~~Clears the dropdown for selecting dev portfolio after submission~~ 
- ~~Clears the text area after submission~~ 
- ~~Clears form state only after the submission request is successful~~
This PR removes clearing the dev portfolio form after submission. 
N/A - From #idol-support (https://cornelldti.slack.com/archives/C044T59JD34/p1681666314088999)
The dev portfolio form should not be cleared after submission. It should be possible to re-submit the form by just clicking on the submit button a second time.
> Clear dev portfolio form inputs upon submission

- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.module.css
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.module.css
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDasboard.tsx
- frontend/src/consts.ts
- frontend/src/pages/admin/team-events.tsx
- frontend/src/pages/admin/team-events/dashboard.tsx
- frontend/src/pages/admin/team-events/index.tsx
Add admin TEC dashboard to show all attendance for all events and all members. 
The name column on the left is sticky if the number of columns overflows: 
If a member has completed their TEC requirement, their name and total credit cells are highlighted green. 
[Notion link](https://www.notion.so/cornelldti/TEC-Admin-dashboard-to-glance-at-users-credits-49105c8ae1d64b179266e41d52357dbe?pvs=4)
👀
> Add admin TEC dashboard 

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This pull request changes the default date range on admin view of shoutouts to 13.5 days instead of 14 days, ensuring no overlap between separate All-Hands shoutouts. 
https://www.notion.so/cornelldti/Idol-SP23-e65533742dca4f898581cc5c496e821e?p=fe6e981c03e84cf4a3ca46e84096b7f8&pm=s
The date range shows 13 days instead of 14 days.
> Change shoutouts admin view date range to 13.5 days

- frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.module.css
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx
- Admin view: emphasize when event has >0 pending requests through bolding, color, etc.
- Admin view: automatically refresh pending/approved columns after approving/rejecting a TEC request
- Member view: Add loading for event cards and everything under the header text (i.e. "Your Approved Credits", "Remaining Credit Needed", and below)
- Member view: Fix remaining credits being calculated incorrectly. This was related to community events. If you completed all team event credit requirements, you would always have 1 remaining credit left to complete, and that would be the community event credit. I've hidden this logic for now using the `COMMUNITY_EVENTS` flag.
https://www.notion.so/cornelldti/TEC-Polishing-and-Bug-Fixes-for-Release-594270005d4246908460deff2480c949?pvs=4
Manual testing.
This …
> TEC - Polishing and Bug Fixes for Release

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
This PR refactors admin shoutouts to reduce unnecessary complexity:
- Changed `displayShoutouts` from component state and instead just derived from `allShoutouts`, `view`, `earlyDate`, and `lateDate`
- Moved the definitions of child components of `AdminShoutouts` outside of the definition of `AdminShoutouts`
- Moved general helper functions outside of definition of `AdminShoutouts`
- Removed complex dependency arrays for `useEffect` and `useCallback` (removed this altogether) 
- Removed `ButtonPiece` component 
This PR also fixes an issue where the updated state of hidden shoutouts isn't updated unless the page is refreshed. 
N/A
Manual testing:
- Existing functionality should stay the same 
- Hiding shoutouts should be updated without refreshing page 
I think backend tests are failing bc …
> Refactor admin shoutouts

- README.md
- dti-website-redesign/src/components/Footer.tsx
- dti-website-redesign/src/pages/team/index.tsx
As part of the rebranding, update README and two spots on the new website that contain the old team name with "Cornell Digital Technology & Innovation".
Manual. Did a Git grep to check for any instances of "Cornell Design & Tech Initiative", "Design & Tech", "Design and Tech", and "Initiative" and only found these three. Devs, feel free to put up a PR if you find any other ones.
We need to change the image on the new website. But that project is in progress, not public, and won't be released during Fall 2023.
> Rebrand to "Cornell Digital Technology & Innovation"

- README.md
-  Creates the Fall 2023 Idol contributors list with current members on README
> add fa23 contributors list to readme

- frontend/src/pages/App.css
This PR adds a workaround to `App.css` to allow for SemanticUI `Loader` component to show up properly inside `Modal`s.
This is a known issue, and since SemanticUI is on longer being maintained, will not be fixed: https://github.com/Semantic-Org/Semantic-UI/issues/4014.
We use a workaround recommended here: https://github.com/Semantic-Org/Semantic-UI-React/issues/3133#
issuecomment-418766748
Before (example of attempting to place a loader in a modal, which doesn't show up):
After:
> Add Workaround for Loader Showing up Properly inside Modal

- frontend/src/API/CandidateDeciderAPI.ts
The `/candidate-decider/${uuid}/rating` endpoint was updated to PUT instead of POST, but I missed this when getting this change in https://github.com/cornell-dti/idol/pull/472.
> Fix REST Method Typo in CandidateDeciderAPI

- frontend/src/components/Admin/AdminCandidateDecider/AdminCandidateDecider.tsx
While working on the candidate decider, I checked the network tab to debug something unrelated and noticed an infinite rendering loop that has been sitting there for awhile now that spams lots and lots of API calls!
Note for future users of the `useEffect` hook: if you're just trying to run some function/fetch once when the component mounts/page loads in, just leave the dependency array as empty. 
ESLint tends to be extra picky at times with adding functions used to the dependency array, but this can lead to infinite rendering loops (and a lot of Firebase reads!).
> Remove Candidate Decider Infinite Rendering Loop

- backend/src/api.ts
- frontend/src/API/ShoutoutsAPI.ts
Remove typo in ShoutoutsAPI call, an extraneous "}" that was accidentally introduced.
This should make "given" shoutouts visible again. Thanks @oscarwang20 for catching that!
(This PR might win the smallest PR award)
> Remove Extraneous } in ShoutoutsAPI call

- frontend/public/sample_candidate_decider_input.csv
- frontend/src/components/Admin/AdminCandidateDecider/AdminCandidateDecider.tsx
Add helper text for candidate decider input format and example .csv file.
> Add Helper Text for Candidate Decider Input Format

- backend/src/API/candidateDeciderAPI.ts
- backend/src/dao/CandidateDeciderDao.ts
This PR is part of the larger ticket to fix permission handling for the candidate decider.
Filter the candidate decider instances returned by `/candidate-decider` API endpoint to be only the ones that the user has permissions to access.
https://www.notion.so/cornelldti/Candidate-Decider-Fix-Permission-Handling-on-the-UI-and-in-Firebase-0c86c35b2f9643ffa37cc43ac0b0920c?pvs=4
I disabled my IDOL admin privileges and gave myself access to only one of the instances.
Before (and if you clicked on the instances you did not have access to, you would get Firestore permissions error):
After:
> Filter Candidate Decider Instances Returned from `/candidate-decider` by Permissions

- backend/src/types/DataTypes.d.ts
- common-types/index.d.ts
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
In response to the updated expectations for TPM and Dev portfolios, we're adding a new field for "Documentation" for both Devs and TPM views. This way, Devs and TPMs are reminded to include documentation, and they have a way of specifying the documentation they updated, whether or not it's in the PRs they submitted.
Update this in the DB schema and add a UI element.
https://www.notion.so/cornelldti/Add-Blurb-about-Linking-Documentation-for-TPM-Portfolio-bbcc3f76ec5844f981e90a7921083e17?pvs=4
Admin view:
Developer view:
TPM view:
> Add Documentation Field for Dev and TPM Portfolios

- backend/src/dao/TeamEventsDao.ts
- adds documentation to the methods in `TeamEventsDao.ts`
> add documentation to TeamEventsDao

- backend/src/API/candidateDeciderAPI.ts
- backend/src/api.ts
- frontend/src/API/CandidateDeciderAPI.ts
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
Fixes a concurrency issue found on candidate decider caused by two separate endpoints, update comment and update rating, which depending on the order in which they complete in, will overwrite each other. Because we now save comment and rating at the same time, this causes a race condition, so we should combine them as one `/rating-and-comment` endpoint.
> Candidate Decider Concurrency Issue

- backend/src/API/candidateDeciderAPI.ts
- backend/src/dao/CandidateDeciderDao.ts
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
This is a band-aid fix that will hopefully eliminate concurrency issues between users using the candidate decider at the same time, AND from requests from a single user that happen near-simultaneously. 
It uses firestore transactions in order keep the read/write operations atomic so that only they only happen one at a time, instead of in parallel.
> Use Transactions for Candidate Decider Rating and Comment Updates

- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/ResponsesPanel.tsx
Previously, we would update the rating and comment UI elements each time we pulled (using the Firestore listener) a new change from the candidate decider. This caused the UI to appear buggy because the comments and rating would get overridden due to the delayed update in the frontend state.
Make the comment/rating UI elements only get populated once from the DB's data. Since we are already maintaining comments and ratings in the frontend state in real-time, we won't need to pull after the initial ratings/comments are loaded in.
> Only Load From Firestore Once for User's Rating and Comments

- frontend/src/components/Modals/CandidateDeciderEditModal.tsx
To make the candidate decider results easier to view and export, add an "Export to CSV" button for candidate decider's admin view.
Click "Edit" on the candidate decider instance on the admin view, then there will be an "Export to CSV" button.
> Add export to CSV Button for Candidate Decider Admin View

- frontend/src/components/Modals/CandidateDeciderEditModal.tsx
In the CSV, switch out the numbers for the ratings to be strings instead.
Before:
After:
> Fix CSV Ratings to be Strings Instead of Numerical Value

- frontend/src/API/ShoutoutsAPI.ts
As part of the API refactor, introduced a typo for the shoutout DELETE endpoint, which has been changed from `deleteShoutout` to `shoutout/:uuid`.
Manually verified that deleting shoutouts works now.
> Fix typo in shoutout DELETE endpoint

- frontend/next-env.d.ts
- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
- frontend/src/components/Forms/ShoutoutsPage/ShoutoutsPage.tsx
Ticket: "Shoutouts - Fix How Shoutouts Are Loaded In on Admin View"
Notion: https://www.notion.so/cornelldti/Idol-FA23-08f1aac52a364b1dad8cde77ebc1c027?p=c402189001014a1798a22db9286d4566&pm=s
implemented Loader from Semantic UI into "Shoutouts" - Previously, users were presented with empty space while waiting for shoutouts to load, leading to confusion regarding the application's state. The incorporation of a loading indicator serves to improve the user experience by providing real-time feedback and a more intuitive interaction.
> add loading wheel, shoutouts

- backend/src/dao/CandidateDeciderDao.ts
Add docstring for `updateInstanceWithTransaction`, a special dao method that performs essentially the same functionality as `updateInstance`, but uses firestore transactions in order to prevent race conditions. I'm documenting this to make it more clear why this implementation is useful.
> Add docstring for updateInstanceWithTransaction CandidateDeciderDao method

- .github/workflows/backup-prod-db.yml
- backend/resources/cornelldti-idol-backup-9d909d7b0efc.json
- backend/scripts/backup-prod-db.ts
- backend/scripts/send-idol-notifications.ts
- backend/src/firebase.ts
- backend/src/utils/firebase-utils.ts
Add script and corresponding and GitHub Actions cron job for backing up the Dev DB.
I'm deliberately not changing the `.env.example` file, since we should not be working with the backup DB ever, except for backing up the data periodically, which will be done through the job.
Factored these methods to be shared between `update-dev-db` and `backup-prod-db` scripts.
https://www.notion.so/Add-Firebase-backup-DB-9962ea595ead417bb40bd53fad94388a?pvs=4
Ran cron job, and the data matches the prod DB.
> Configure Backup DB

- backend/package.json
Adds the backup prod db script to the backend workspace `package.json`, so we can run
```
yarn workspace backend backup-prod-db
```
in our GitHub actions cron job to run the script.
> Add Backup Prod DB Script to Backend Workspace

- backend/src/API/devPortfolioAPI.ts
- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
- backend/src/utils/firebase-utils.ts
- backend/src/utils/permissionsManager.ts
- backend/tests/DevPortfolioAPI.test.ts
- frontend/src/API/DevPortfolioAPI.ts
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.module.css
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolio.tsx
- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolioForm.tsx
- frontend/src/components/Admin/DevPortfolio/EditDevPortfolio.module.css
- frontend/src/components/Admin/DevPortfolio/EditDevPortfolio.tsx
- frontend/src/utils.ts
Notion ticket: https://www.notion.so/DP-Allow-Admins-to-Edit-Assignments-2307db13393c4f358e377e75f8bd6fea?pvs=4
Admins can now edit a dev portfolio without having to delete and replace an assignment with a new version (which was not feasible once submissions have been made). 
Frontend changes include adding an edit button for each portfolio that opens an edit modal, a success message if an edit is made, and error messages if conditions are violated. 
Backend changes include adding a new update endpoint, and documenting the Dev Portfolio API.
I tested if a dev portfolio is successfully edited by looking at the firebase database, and checking that it updated correctly.
Each portfolio card now has an edit button, which opens a form to edit the portfolio.
The form has pre-populated values …
> Allow admin to edit dev portfolios

- backend/src/API/mailAPI.ts
- backend/src/API/memberAPI.ts
- backend/src/api.ts
- Add permissions check in `sendMail` API endpoint to restrict to admins only
- Remove extraneous/outdated `isProd` check. The corresponding environment variable is not called `isProd` anymore.
- Remove `sendMemberUpdateNotifications` call for every Member information update. This endpoint was previously "dead code" anyway, and it doesn't make sense to keep (i.e. notify every admin every time someone updates a profile)
-  Replace usage of `EMAIL` env variable. This environment variable is not used in the codebase anymore. We use exclusively "dti.idol.github.bot@gmail.com" in our codebase.
Running this CURL command:
```
curl -X POST "localhost:9000/.netlify/functions/api/sendMail" -d '{"to": "<your email>", "subject": "test", "text": "Test test test"}' -H "auth-token:  <auth-token>" -H …
```
> Fix `sendMail` API endpoint

- backend/src/API/mailAPI.ts
Small change: set it so that only "prod" environments will allow for the sending of emails. This will prevent us from accidentally sending out emails in staging and dev environments to lots of members.
> Send staging emails to stdout

- frontend/src/components/Admin/AdminShoutouts/AdminShoutouts.tsx
For the latest shoutout date, adjust the time to be 11:59pm on the same day, now adjusted to the current local time zone.
> Adjust Shoutouts Ending Time to Local Time Zone

- backend/src/API/mailAPI.ts
- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
Before, the `/sendMail` endpoint just returned an IdolMember object for the recipient of the email, which wasn't very useful in figuring out whether or not the mail sent successfully.
I've changed this so that the response body contains the response received from the NodeMailer transporter, or if in non-prod environment, a message (which is also logged) that emails are not sent in non-production environments. 
This should make it easier to debug what's going wrong in prod right now with the mailAPI.
```
curl -X POST "localhost:9000/.netlify/functions/api/sendMail" -d '{"to": "axc2@cornell.edu", "subject": "test", "text": "Test test test"}' -H "auth-token:  <auth-token>" -H 'Content-Type: application/json'
```
Before (not useful at all):
```
{
"member": {
"firstName": "Andrew", …
```
> Improve mailAPI Response Body Data

- backend/src/API/mailAPI.ts
Previously, we had TeamEventAPI references in `mailAPI`, which may reduce some code duplication, however, there are some permissions/authorization checks we do at the API level that we don't want to check "twice." 
In this case, using `TeamEventsAPI` introduced a bug that led to us not able to send reminder TEC emails to non-IDOL Admins/non-leads. 
Instead, reference `TeamEventAttendanceDao` and `TeamEventsDao` directly.
Sent the rest of the emails to all non-admins successfully!
> Replace TeamEventsAPI references in MailAPI with Calls to Dao Instead

- frontend/src/components/Admin/AddUser/AddUser.tsx
This pull request provides confirmation for an ops lead on the edit users page that they have completed the action performed (edit user, create user, or save user).
https://www.notion.so/Edit-Users-Confirmation-after-Save-Delete-Create-User-Operations-f1efb32f482f449f82336b997d5e94b9?pvs=4
> Add confirmation for ops leads on edit users page

- backend/src/types/DataTypes.d.ts
- backend/src/utils/githubUtil.ts
- common-types/index.d.ts
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/components/Modals/DevPortfolioTextModal.tsx
The dev portfolio submissions form now has a third category besides “Opened PRs” and “Reviewed PRs” to handle exceptions that don’t fall into either category, but should be counted as valid. This category is automatically hidden unless the user explicitly clicks the arrow to open this section. 
https://www.notion.so/DP-Add-Other-Category-to-Allow-Exceptions-7ed09a2923ea4a51975ed773de0bcfd8?pvs=4
I checked that opening the third category will set the previous two categories to optional.
I created a test dev portfolio that used the other category, and checked the submissions dashboard to see that the submission is automatically set to pending.
The PRs and explanation are shown when the admin opens the "Show Text" button.
> Add other category to dev portfolio form

- frontend/src/components/Modals/DevPortfolioTextModal.tsx
We avoid checking the role since otherPRs applies to Dev's only. If there are other PR's submitted, then the submission is a Dev Portfolio submission, not a TPM portfolio. 
Consider the case where a member is promoted to TPM mid-semester. That should not change the way this Dev Portfolio is displayed. 
Consider also the case where a member switches from TPM to Dev mid-semester. (Yes, both of these cases have happened at some point!). We want to preserve the state of the portfolio.
> Check for otherPRs instead of Member Role for Admin Dev Portfolio Display

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
Context:
Just from taking a few passes on submissions this semester, I’ve noticed a lot of duplicate submissions for the TEC form and Dev Portfolios. This is most likely because for both the [TEC form](https://idol.cornelldti.org/forms/teamEventCredits) and [Dev Portfolio form](https://idol.cornelldti.org/forms/devPortfolio), when you submit, the form fields do not clear. So users might be confused as to whether or not their submissions went through, so they double/triple click and then we get a bunch of duplicate submissions.
This is by design, in case you wanted to make multiple submissions, or for Dev Portfolio, it was in case you wanted to replace your existing submission with a minor adjustment (so you don’t have to fill everything in the form again).
But I haven’t personally used …
> Clear TEC and Dev Portfolio Forms Upon Submission

- backend/src/API/mailAPI.ts
- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
- frontend/src/API/MembersAPI.ts
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.module.css
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Modals/NotifyMemberModal.tsx
Add ability to send an "end of semester" TEC submission reminder, which reminds members to submit all TEC credits after there are no more TEC credit events.
Feature request from Justin (C&I lead), most likely everyone has completed their TEC already, but they are procrastinating on submitting them.
> Add Ability to Send End of Semester TEC Submission Reminder

- backend/package.json
- backend/scripts/shoutout-leaderboard.ts
Add script that parses leaderboard for shoutout givers, given a `QUERY_DATE`, and outputs data to console (similar to Dev Wrapped script).
We can now run `yarn workspace backend shoutout-leaderboard` to get this info.
Ran script:
```
% yarn workspace backend shoutout-leaderboard
yarn workspace v1.22.19
yarn run v1.22.19
$ esr scripts/shoutout-leaderboard.ts
Collecting all shoutouts from 2023-08-01 until now...
[
[ 'Benjamin Tang (bt283)', 35 ],
[ 'Richard Gu (rg779)', 14 ],
[ 'Mikayla Lin (ml953)', 13 ],
[ 'Sophia Pham (tpp38)', 12 ],
[ 'Andrew Chen (axc2)', 11 ],
...
```
> Add Shoutout Leaderboard Script

- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.module.css
- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
We have a UI bug in the Dev Portfolio Details table due to longer documentation responses that are not being properly text-wrapped, so much so that some columns are not even visible unless you zoom out on a standard browser viewport.
Set max width of documentation column to be 200px and wrap the text.
Before:
After:
> Break Word in Documentation Cell in Dev Portfolio Table

- backend/src/API/candidateDeciderAPI.ts
- backend/src/utils/permissionsManager.ts
Bug: Candidate decider was responding with a permissions error (403) for accessing and updating ratings/comments for an instance, even if the member was listed under authorized members.
`/.netlify/functions/api/candidate-decider/rating-and-comment`
Response:
```
{
"error": "User with email axc2@cornell.edu does not have permission to access this Candidate Decider instance"
}
```
This is because `Array.includes(...)` checks for equality of two object references. Check equality by email field instead.
Manual:
1. Added myself to authorized members for an instance
2. Removed myself as an admin from IDOL
3. Verified that I am still able to update ratings and comments
- Also abstracted permissions logic for updating ratings/comments to a helper …
> Candidate Decider: Check Authorized Members By Email

- .github/workflows/idol-notifications.yml
Kevin requested to receive TEC notifications less frequently. 
- Maybe we could allow C&I lead to change the frequency of these emails themselves?
- Could potentially look into for Slack integrations as well.
> update TEC email notifs to only send weekly on mondays

- backend/src/API/teamAPI.ts
Added documentation to `teamAPI.ts`. The @throws were not included due to the error messages being self-explanatory.
> Add documentation to Team API

- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx
- frontend/src/consts.ts
- Factor out `INITIATIVE_EVENTS` from several files relating to TEC into `consts.ts`
- Add a line for displaying remaining initiative TEC needed
- Add label for initiative events when submitting TEC
- Previewing each page 
- The codebase still uses community instead of the initiative (official terminology) in several files, mainly in the API and backend files, which can be really confusing.
> Add support for initiative TEC

- backend/src/dao/TeamEventsDao.ts
- backend/tests/data/createData.ts
- common-types/index.d.ts
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventForm.tsx
- frontend/src/components/Admin/TeamEvent/TeamEvents.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx
- Change most (see notes below) references of `isCommunity` field to `isInitiativeEvent` in FE
- Fix bug with displaying total initiative event credits in Dashboard
- Fix bug with not retrieving `isInitiativeEvent` when requesting all team event info
This pull request is the second step towards implementing support for initiative TEC
https://www.notion.so/TEC-Add-support-for-Initiative-tec-279c8cac37124630b2b7d7f383c70e55
- `isCommunity` is still referenced in some files to be safe, namely in `index.d.ts` and `TeamEventForm.tsx` when editing an event. In the latter case, `isCommunity` is updated to the value of `isInitiativeEvent`.
- Database schema change (anything that changes Firestore collection structure)
> Refactor isCommunity field

- backend/src/dao/MembersDao.ts
Added documentation to `getAllTeams` and `getTeam` in `MembersDao.ts`. It wasn't immediately clear why these functions are in the Members DAO, so there is now a short clarification (based on the explanation of the `Team` data type in #581).
> Add documentation to Members DAO

- frontend/src/components/Admin/TeamEvent/TeamEventDetails.module.css
- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
- frontend/src/consts.ts
The admin page where the C&I lead can approve/reject TECs previously showed all submission statuses on one page, which caused inconvenient scrolling when there were many submissions. There is now a dropdown menu that can filter through each status and also go back to showing all statuses, if needed.
https://www.notion.so/Admin-TEC-Filter-by-status-04f238712c8245689253cfc53b8d065c?pvs=4
I checked that only TEC submissions of the selected status are shown, the "View All" button only appears when there is a status selected, and approving/rejecting a request will stay on the same selected status when the process is complete.
> Create filter for TEC status

- backend/src/API/mailAPI.ts
- backend/src/API/teamEventsAPI.ts
- backend/src/api.ts
- backend/src/utils/errors.ts
- dti-website-redesign/src/pages/App.css
- dti-website/src/components/ProjectGoTo.tsx
- frontend/src/components/Games/DTI48/dti48-upgrade-chain.test.ts
- package.json
- yarn.lock
This pr upgrades Prettier from version 2.4.1 to 3.2.5
> Bump prettier to v3.2.5

- common-types/constants.js
- common-types/index.d.ts
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
- frontend/src/utils.ts
- Adds `dev-advisor` as another role for IDOL members
- Dev advisors only need to submit documentation for dev portfolio
- Also changed dev portfolio requirements to reflect the new TPM expectations (opened PR is now mandatory)
- Changed `PRInputs` prop from `isTpm` to `isRequired`
Dev Advisor
TPM
- Changed myself to dev advisor and made sure dev portfolio submission is blocked if no documentation is provided
- Changed myself to tpm and made sure dev portfolio submission is blocked if no opened PR was provided
> add dev advisor role

- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.module.css
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
The leads needed a way to export the TEC information for each member to a CSV format. The TEC dashboard page now has the ability to export the entire table to a CSV format. The exported file will contain each member's name, netID, total TECs, initiative TECs, and the corresponding TECs they have from each team event.
For each member in `allMembers`, the `totalCredits` and `initiativeCredits` are calculated and added to the CSV data. Also, the number of credits they have for each team event in `teamEvents`  is added to the CSV data. After configuring the CSV format, the CSV exporter generates the file based on the data.
https://www.notion.so/TEC-Export-to-csv-30f17a9b406243f0a24ec297626c1025?pvs=4
I checked to see that the data in the exported CSV file aligns with what is shown in the TEC …
> Create export to CSV feature for TEC dashboard

- backend/tests/TeamEventAttendanceDao.test.ts
- backend/tests/data/createData.ts
I added unit testing for `TeamEventAttendanceDao` based on the previous tests files in the same directory. I also edited the random TeamEventAttendance generation to agree with the removal of pending and other field changes.
* In another PR, this directory should be cleaned up. Several files have type errors, and jest is not able to run the backend tests as a whole.
> Add test file for TeamEventAttendanceDao

- new-dti-website/next.config.js
- new-dti-website/package.json
- yarn.lock
This PR fixes the netlify deploy error by downgrading the nextjs version for the new dti website.
See [this thread](https://stackoverflow.com/questions/76083438/module-not-found-cant-resolve-swc-helpers-src-class-private-field-init-mjs) for details
- Checked deployment preview and confirmed it works again
> Downgrade Nextjs and set config for new website

- .eslintignore
- backend/src/API/memberAPI.ts
- backend/src/api.ts
- backend/src/dao/MembersDao.ts
- backend/src/members-archive/index.ts
- common-types/index.d.ts
- frontend/public/sample_returning_members.csv
- frontend/src/API/MembersAPI.ts
- frontend/src/components/Admin/AddUser/AddUser.tsx
This pull request adds a section to the `admin/edit` page to download an archive, in json form, of all past and present DTI members given a returning members survey. This will be used by the ops leads at the end of each semester to generate the next semester's roster. The json will contain three keys: current, alumni, inactive, each storing a list of member details. 
* `NovaMember` now has a purpose again! It represents a member on the new DTI website, specifically with a coffee chat and image field.
* A sample returning members survey is attached.
* Endpoint `/member-archive?semesters=` allows you to define a limit to how many semesters back, if any, to include in the archive. 
https://www.notion.so/Member-archive-script-0540cb5e7d0349c4921f344b1875387e?pvs=4
Test CSV:
``` …
```
> Add ability to archive members

- new-dti-website/components/products/imageCarousel.tsx
The image carousel wasn't stretching to the full viewport width after stretching the screen long enough.
Remove the width constraint to allow for the carousel to take up the entire viewport width.
Before:
After:
https://www.notion.so/Carousel-Hero-Component-0-5-sprints-ab360524d0c541f4aedcba75b55f29de
> Website: Remove width constraint on the image carousel

- frontend/src/components/Candidate-Decider/CandidateDecider.module.css
Noticing that there's text without spaces that overflows the text.
Discovered this from a person's application from SP24 which caused the entire left panel to overflow and take up the entire screen (you had to zoom out to see both left and right panels).
Before:
After:
Manual
> Candidate Decider: Wrap text without spaces to prevent overflow

- backend/src/API/candidateDeciderAPI.ts
- backend/src/api.ts
- backend/src/dao/CandidateDeciderDao.ts
- backend/src/dao/CandidateDeciderReviewDao.ts
- backend/src/firebase.ts
- backend/src/types/DataTypes.d.ts
- common-types/index.d.ts
- frontend/next-env.d.ts
- frontend/src/API/CandidateDeciderAPI.ts
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/GlobalProgressPanel.tsx
- frontend/src/components/Candidate-Decider/LocalProgressPanel.tsx
- frontend/src/components/Candidate-Decider/useCandidateDeciderInstance.tsx
- frontend/src/components/Modals/CandidateDeciderEditModal.tsx
Candidate Decider was having race conditions due to multiple people making reviews at a time. 
- Create new collection `candidate-decider-review` to factor out the ratings and comments into a separate collection. This will make it easier to implement database transactions on them.
- Use database transactions for updating ratings and comments
- Add firebase listener for `candidate-decider-review`
- Remove `ratings` and `comments` field from `CandidateDeciderInstance`
Also added this Firebase rule:
```
match /candidate-decider-review/{uuid} {
allow read: if 
get(/databases/$(database)/documents/members/$(request.auth.token.email)).data.role in 
get(/databases/$(database)/documents/candidate-decider/$(resource.data.candidateDeciderUuid)).data.authorizedRoles || …
```
> Candidate Decider: Refactor Reviews to Separate Collection to Prevent Race Conditions

- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/SearchBar.tsx
- frontend/src/components/Modals/CandidateDeciderEditModal.tsx
This PR does 4 things:
Bugs fixed:
- Fixes syncing issues between the dropdown, search bar, and the current candidate
- Fixes a bug that reverted the comment and review field to their last saved state when the rating/comment were set to blank, and someone else made a review
Changes:
- Hides the button to show other people's votes for non-admins
- Make candidates whose review is undecided not count as a completed review (won't contribute to the progress bar)
Bug bash 8/31: https://docs.google.com/spreadsheets/d/1uiReV7A3Xu5QwZMA3cr4SXSuylb4sJ_oqnXctik24Ug/edit?gid=0#gid=0
Manual, and second bug bash on the deployment preview
> Candidate Decider Bug Fixes

- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
There was a bug where clicking on any option in the dropdown would always default to the first option in the list, and the dropdown would close, preventing users from clicking on any other options.
Remove TEC info card so that it's possible to select other options. Frankly, I don't see why we need the card in the first place and it adds an unnecessary layer of complexity.
Before:
https://github.com/user-attachments/assets/72d10e30-89f7-4216-8a9e-8771d7841ce1
After:
https://github.com/user-attachments/assets/f3899ba2-a014-4027-a07e-781b95c71195
https://cornelldti.slack.com/archives/C044T59JD34/p1713279418092159
> TEC Form: remove tec info card and fix dropdown selection bug

- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
Currently we enforce TEC limit for single submissions that exceed the total credit limit of the TEC event. But we missed this check on bulk submissions, where a user can submit multiple events at a time that in total will exceed the max credit limit.
This PR enforces the TEC Limit for bulk submissions.
https://cornelldti.slack.com/archives/C07K7HFJLPJ/p1725836378114069
Manual
https://github.com/user-attachments/assets/27ae2aa6-f05e-4def-9dd3-7e04280623a1
> TEC Form: Enforce TEC Limit for Bulk Submissions

- frontend/src/components/Admin/DevPortfolio/AdminDevPortfolioForm.tsx
There was a bug with the newly created dev portfolio success message. The name and deadline were controlled by the state variables, so the UI would update as the corresponding fields were edited.
Store and read from a `lastCreatedPortfolio` instead.
Before:
https://github.com/user-attachments/assets/e0de1036-911d-4ccd-8b38-57323cb1c0d0
After:
https://github.com/user-attachments/assets/b4b2b224-a95b-47f7-9835-03868b9b1686
> Dev portfolio Admin Page: Fix Created Dev Portfolio State Bug

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
Make opened PR's Optional for TPMs (policy change now only requires 2/5 PR's, so TPM's will decide when they want to submit PR's)
https://www.notion.so/Dev-Portfolio-Make-opened-PR-s-Optional-for-TPMs-1080ad723ce1801c88b3de2b69cfbef1?pvs=4
Manually submitted a TPM portfolio without open PRs.
Tried manually submitting a Dev portfolio without open PR's and it was not allowed.
TPM view:
Dev view:
> Dev Portfolio: Make opened PR's Optional for TPMs

- new-dti-website/src/app/page.tsx
There's been a mysterious 3-second delay on the slideshow whenever it's loaded. Originally, we thought it was due to image size, but it was actually a bug caused by how the initial state of the slideshow is set!
Set the initial value to be image 0, so that the slideshow is loaded upon page load.
Load up the page and observe that the slideshow loads immediately and doesn't take 3 seconds.
> New Website: Fix 3 Second Slideshow Delay Bug

- new-dti-website/components/slideshow.tsx
I forget whether we added the fading transition for flair or if it was actually part of the design. Frankly I think it looks borderline buggy, and I don’t like how the header and the slide aren’t perfectly fading in alignment (even if we fixed that, I don’t know if I’d like it).
Let's try switching the slideshow component to switch between photos without the fading transition
Before:
https://github.com/user-attachments/assets/7e43744c-c6c3-4859-b632-fd422ca858d8
After:
https://github.com/user-attachments/assets/3d58d0f3-e071-4e52-8a86-95756ec0d73e
> New DTI Website: Remove Fading Transition for Photos in Slideshow

- frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
Previously, a TEC Admin would be able to Approve a request even if the "reason for reject" text field was not empty, leading to accidentally approvals. However, this change disables the "Approve" button if there's text in the "reason for reject" field. (see attached video)
https://github.com/user-attachments/assets/07ac6966-e6e9-4392-a8e5-9649fcabb2f2
> TEC Admin tool: disable "Approve" when reason for reject isn't empty.

- frontend/src/components/Admin/TeamEvent/TeamEventDetails.tsx
Previously, an Admin couldn't see the reason they previously wrote for rejecting someone's TEC request. However, this PR now displays it alongside the option for re-approval.
> [IDOL, TEC Admin] display TEC rejected reason

- backend/src/API/coffeeChatAPI.ts
- backend/src/dao/CoffeeChatDao.ts
- backend/src/types/DataTypes.d.ts
- backend/tests/CoffeeChatAPI.test.ts
- backend/tests/data/createData.ts
- common-types/index.d.ts
Make some updates to CoffeeChat and `DBCoffeeChat`, based on some requirement clarifications. This will make it more clear that a coffee chat needs to be submitted by both members, that the image is actually a Slack link.
We also don't need the description field.
https://www.notion.so/Design-Doc-c6dfb74b11cc4c7993ea0939109c9db8?pvs=4
Updated design doc to match the changes in the type.
- Updated unit tests
> Coffee Chat: Change Members Field to submitter and otherMember, Change image to slackLink, Remove Description

- frontend/src/components/Admin/TeamEvent/TeamEventCreditReview.tsx
Kevin found that images for rejected TEC requests weren't being saved. Looks like we used to remove the image upon rejecting a TEC attendance request since we used to delete the TEC attendance altogether when it was rejected, instead of saving a record.
Looks like there aren't any rejected requests yet so this hasn't been a problem, but we'll want these images when we start making them available on the admin view.
https://www.notion.so/TEC-Don-t-Delete-Image-When-Rejecting-TEC-Requests-1180ad723ce18075ad73c5e6c2478ccc?pvs=4
> TEC: Don't Delete Image when Rejecting TEC Requests

- frontend/src/components/Common/NavigationCard/NavigationCard.module.css
- frontend/src/components/Common/NavigationCard/NavigationCard.tsx
- frontend/src/components/Homepage/Homepage/Homepage.module.css
- frontend/src/components/Homepage/Homepage/Homepage.tsx
- frontend/src/pages/admin/index.module.css
- frontend/src/pages/admin/index.tsx
- frontend/src/pages/forms/index.module.css
- frontend/src/pages/forms/index.tsx
We previously were only filtering navigation cards on the "Forms" tab, but not the home page. This is because we had two navigation card components, `NavCard` and `NavigationCard`, the first of which did not contain logic to filter against the "adminOnly" flag. We should allow `adminOnly` to be used on the homepage if we want to gate something through a feature flag.
Also, update the Homepage to use `NavigationCard` and delete `NavCard`. This consequently also fixes an alignment issue on the homepage too.
Verification steps:
1. Check that the "Admin" and "Forms" tab still look the same
2. Check that the homepage styling still looks acceptable (in terms of spacing and alignment of the cards)
Before:
After:
> Filter Admin Only Cards for Home Page

- frontend/src/components/Admin/CoffeeChats/CoffeeChats.tsx
Noticed the hit box for the admin cell was a little small. I could only click into the cell once I hit the text, but we should be able to do it by clicking on the cell directly.
Wrap the entire cell in `Link`.
Manual:
https://github.com/user-attachments/assets/73f91314-840b-4174-ba07-a29523799610
> Coffee Chat Admin Tool: Wrap entire cell with link

- backend/src/API/coffeeChatAPI.ts
- backend/src/api.ts
- backend/tests/CoffeeChatAPI.test.ts
- frontend/src/API/CoffeeChatAPI.ts
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
- new-dti-website/.vscode/settings.json
This PR does a few things:
- There was a bug where if you created a few coffee chats and then delete one, all would be deleted. This is because we weren't storing the UUID of the newly created coffee chats in the state, so when we clicked the delete button, instead of hitting DELETE `/coffee-chat/:uuid`, we'd hit DELETE `/coffee-chat`, since uuid was undefined, so for admins submitting coffee chats, it was possible to accidentally clear all coffee chats in the DB.
Fix that by plumbing the UUID back to the frontend.
- I'm also adding a guard on the frontend to prevent even submitting a request unless the `uuid` is populated
- Also, improve the error messages a bit to be more clear why a submission isn't allowed (split up category and member exists cases)
Manual
> Coffee Chat Tool: Fix Delete All Coffee Chat Bug, Better Error Handling

- backend/src/API/coffeeChatAPI.ts
- backend/src/consts.ts
- backend/src/utils/permissionsManager.ts
- backend/tests/CoffeeChatAPI.test.ts
During our sync with the leads and testing the coffee chat tool out, we realized that the `clearAllCoffeeChats` operation is quite dangerous. Let's disable it for now.
> Coffee Chats: Disable API Endpoint That Clears All Coffee Chats

- frontend/src/components/Admin/DevPortfolio/DevPortfolioDetails.tsx
- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
The dev leads amended the documentation requirement for Dev Portfolios such that creating/updating tests can fulfill the requirement as well. Update the wording on the Dev Portfolio submission side to reflect that.
Also update the wording for TPM's to include the following line:
> However, you must open at least 2 PR's in total during the entire semester.
> Dev Portfolio: Update Documentation Directions to Allow Testing to Fulfill Requirement

- frontend/src/consts.ts
Since coffee chat bingo on IDOL is not ready for public use yet (still undergoing internal testing), we should hide it.
> Disable Coffee Chats For Non-Admins

- new-dti-website/components/apply/ApplicationTimeline.tsx
The timeline will automatically scroll to the next or current event, i.e the one that is selected. If there are no selected events, the timeline scrolls to the very bottom.
[Figma](https://www.figma.com/design/1nUpvsfgc9eftTyoHt7XuN/Website-Designs-SP24?node-id=1138-3162&node-type=frame&t=tgZ5CxIR1S9Z6T57-0)
https://github.com/user-attachments/assets/a8a71a34-fd79-45ba-8e4f-06a1f6a3bf96
> Auto-scroll to Selected Event

- backend/src/API/coffeeChatAPI.ts
- backend/src/api.ts
- backend/src/types/DataTypes.d.ts
- backend/tests/CoffeeChatAPI.test.ts
- common-types/index.d.ts
- frontend/src/API/CoffeeChatAPI.ts
- frontend/src/components/Admin/CoffeeChats/CoffeeChatDetails.module.css
- frontend/src/components/Admin/CoffeeChats/CoffeeChatDetails.tsx
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
This PR customizes each error message depending on the category, and displays the error message on the admin side if a member does not meet the category. There is also now a button to re-run the auto checker on the admin side.
The previous logic for `checkMemberMeetsCategory` didn't correctly identify between false/fail and undefined/no data, so that is fixed.
https://github.com/user-attachments/assets/1cc0b432-a7c4-4cd4-925f-bbf9a1d51e7d
> Coffee Chat: Show Error on Admin Side, Add Re-run Auto Checker Button, Fix checkMemberMeetsCategory Logic

- frontend/src/consts.ts
We're going to start rolling out coffee chats for DTI members. Rollout plan:
1. Enable on IDOL for non-members.
2. Have everyone on IDOL try it out
3. Select a few people who've submitted a lot of coffee chats to try the tool out
4. Launch at all-hands 11/9
Manually verified that all non-admins can see the tool now.
> Enable Coffee Chats on IDOL

- backend/src/dao/CoffeeChatDao.ts
- backend/tests/CoffeeChatAPI.test.ts
This PR adds unit tests for the more complicated cases in `checkMemberMeetsCategory`, including 'a pm (not your team)', 'a tpm (not your team)', and 'a lead (not your role)'.
> Test checkMemberMeetsCategory

- frontend/src/components/Forms/ShoutoutsPage/ShoutoutForm.tsx
Submitting the shoutouts form with a blank name or a blank message would lead to the button being stuck on "loading" forever. 
Set `isSubmitting` to stop the loading if the submission failed.
> Shoutouts Form: Fix Infinite Loading Bug

- new-dti-website/components/team/MemberGroup.tsx
- new-dti-website/src/utils/memberUtils.ts
We originally wanted to show "Technical Product Manager" for a TPM's role on the team page, but after some discussion, we're changing it to "Technical PM" to be more succinct.
https://www.notion.so/New-Website-Show-Technical-PM-instead-of-Technical-Product-Manager-on-Team-Page-13c0ad723ce18009b6ebd73828f7a56d?pvs=4
Manual (see screenshot):
> New Website: Show 'Technical PM' instead of 'Technical Product Manager' on Team Page

- backend/src/consts.ts
- frontend/src/consts.ts
Follow up PR to #683: Add the missing roles to `frontend/consts.ts` and `backend/consts.ts`.
> Add Missing Roles to consts.ts

- common-types/constants.d.ts
- common-types/constants.js
- frontend/src/components/Admin/AddUser/AddUser.tsx
- frontend/src/components/Admin/AdminCandidateDecider/AdminCandidateDecider.tsx
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Candidate-Decider/LocalProgressPanel.tsx
- frontend/src/components/Common/FirestoreDataProvider.tsx
- frontend/src/components/Common/Search/Search.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventsCreditDashboard.tsx
- frontend/src/components/Forms/UserProfile/UserProfile.tsx
- frontend/src/components/Modals/CandidateDeciderEditModal.tsx
- frontend/src/consts.ts
I noticed that the roles weren't showing up in the dropdown on IDOL.
Last follow up PR to https://github.com/cornell-dti/idol/pull/690. I accidentally had `ALL_ROLES` defined in both `constants.js` and `frontend/consts.ts` and forgot to update `constants.js` with the new roles. 
Since they're general to the codebase, not just the frontend, let's define the roles in `constants.js` and remove them from `frontend/consts.ts`.
Verify that the roles show in the dropdown on IDOL now:
> DTI Website: Read ALL_ROLES from frontend/consts.ts and Remove constants.js

- backend/src/API/coffeeChatAPI.ts
- backend/src/consts.ts
- backend/src/utils/memberUtil.ts
- backend/tests/CoffeeChatAPI.test.ts
- backend/tests/data/createData.ts
- common-types/constants.js
- common-types/index.d.ts
- frontend/src/utils.ts
I've cut over all leads and business members to their more specific roles. This PR deletes the `'lead'` and `'business'` roles in favor of the more specific ones.
Also, modify the coffee chat checker logic to use the more specific lead role, instead of pulling from `member-properties`.
https://www.notion.so/New-Website-IDOL-Add-Specific-Lead-and-Business-Roles-Add-Advisor-Roles-13c0ad723ce180708c9af4cf0181d3c6?pvs=4
Modified existing tests.
> IDOL/New DTI Website: Remove Lead and Business Analyst Roles

- new-dti-website/src/app/sponsor/page.tsx
The team photo looks squished horizontally on the sponsors page. Making the component wider doesn't fix this because as you decrease the width, the image gets squished.
Adding `object-cover` to crop the image so that it keeps its shape.
Before:
After:
https://github.com/user-attachments/assets/1858188b-b42a-4094-bc25-a1fbd5908c9d
https://www.notion.so/Website-Initiatives-Page-Image-Too-Narrow-13f0ad723ce1807d82b8c2961439c375?pvs=4
https://github.com/user-attachments/assets/b2f62c27-463b-42ef-999c-819e0f7d745a
> Fix Initiatives Page Squished Image

- new-dti-website/components/slideshow.tsx
- new-dti-website/src/app/layout.tsx
- new-dti-website/src/app/page.tsx
This PR adds responsiveness to the home page, primarily the hero component. The timeline was slightly reworked to only render one image at a time instead of all at once and changing visibility. The "Learn More" sign should be visible for almost all viewports (could not figure out some edge cases, but those are on weird dimension viewports).
[Notion](https://www.notion.so/Hero-Page-Mobile-Styling-a3192f43d4c44dc6a8f6ede779edb575)
Before:
After:
> Website: Home Page Responsiveness

- frontend/src/components/Common/NavigationCard/NavigationCard.tsx
- frontend/src/components/Homepage/Homepage/Homepage.tsx
- frontend/src/pages/forms/index.tsx
Added a disable feature to NavigationCardItem and disabled the Sign-In Form Navigation card on the Homepage and Forms Tab.
> Removed Sign In Form from Homepage and Forms Tab

- .github/workflows/pull-from-idol-images.yml
Confirmed that there is proper diff checking being done for the images in the "Pull from IDOL Images" job. If there are no changes, there will not be a pull from IDOL images job. Example run where it did not trigger a PR: https://github.com/cornell-dti/idol/actions/runs/11875583268
Set Pull from IDOL Images to Daily.
> Set Pull from IDOL Images to Daily

- backend/src/API/shoutoutAPI.ts
Previously, if an IDOL user deleted a shoutout that had an image attached to it, the image wouldn't get deleted (taking up space in our storage).
I tested this by submitting shoutouts with images, seeing them get added to the Firebase, and removed when I deleted the shoutout from IDOL.
> delete shoutout images w/ shoutout

- frontend/src/components/Forms/DevPortfolioForm/DevPortfolioForm.tsx
This PR allows users to submit dev portfolios with blank fields as long as the first field as long as there exists a valid GitHub link. It also ignores the empty fields in the actual submission. 
[https://www.notion.so/Dev-Portfolios-Ignore-Blank-PR-Fields-When-Submitting-13c0ad723ce1804d9a0ffcbda920e031](url)
https://github.com/user-attachments/assets/21212050-92b6-4593-8ba9-5fa388928023
> ignore blank fields in dev portfolio submissions

- new-dti-website/pull-from-idol.ts
The "Pull from IDOL" job breaks when the JSON diff output is too large. 
```
RequestError [HttpError]: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"} - https://docs.github.com/rest/pulls/pulls#create-a-pull-request
at fetchWrapper (/home/runner/work/idol/idol/new-dti-website/node_modules/@octokit/request/dist-bundle/index.js:119:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async main (/home/runner/work/idol/idol/new-dti-website/pull-from-idol.ts:95:5) {
status: 422,
request: {
method: 'POST',
url: 'https://api.github.com/repos/cornell-dti/idol/pulls',
headers: {
accept: 'application/vnd.github.v3+json',
'user-agent': 'cornell-dti/big-diff-warning …
```
> Pull from IDOL: Set Max Length for Diff Output in PR Description

- new-dti-website/components/apply/ApplicationTimeline.tsx
- new-dti-website/components/apply/ApplyFAQ.tsx
- new-dti-website/components/bottom.tsx
- new-dti-website/components/footer.tsx
- new-dti-website/components/navbar.tsx
- new-dti-website/components/team/MemberDisplay.tsx
- new-dti-website/components/team/MemberGroup.tsx
- new-dti-website/components/team/TeamFooter.tsx
For accessibility purposes, remove all instances of wrapping a `<button>` in `<a>`, and use `Link` (from Next) instead.
Buttons work the same. Now tabbing behavior is correct, where the component only highlights once.
Grepping for instances of `<a>` wrapping a `button` should no longer exist.
> Website: Remove Wrapping a <button> in <a>

- new-dti-website/config.json
~~We received leads feedback to show the “We are no longer accepting applicants” text everywhere where the apply button typically would be, so it doesn’t feel like a bug when applicants navigate back to the page and don’t see the apply button anymore.~~ We're going to redo this design to instead include a banner. Handled in a separate PR.
Also, fix application links on the Apply timeline.
https://www.notion.so/Website-Bold-Application-Text-and-Fix-Application-Links-1440ad723ce180e1879dc8bce2e069fe?pvs=4
The two "Google Form Application" links lead to the application now.
> Website: Bold Application Text and Fix Application Links

- new-dti-website/components/apply/ApplicationTimeline.tsx
- new-dti-website/components/apply/ApplyFAQ.tsx
- new-dti-website/components/apply/RoleDescription.tsx
- new-dti-website/components/course/DDProjects.tsx
- new-dti-website/components/icons.tsx
- new-dti-website/components/navbar.tsx
- new-dti-website/components/sponsor/SponsorshipTable.tsx
- new-dti-website/components/team/MemberDisplay.tsx
- new-dti-website/components/team/MemberGroup.tsx
- new-dti-website/components/team/TeamHero.tsx
- new-dti-website/components/ui/button.tsx
- new-dti-website/src/app/course/page.tsx
- new-dti-website/src/app/page.tsx
Change all buttons that are interactive, i.e. some functionality that does not redirect the user, to use button elements. 
* All icons: Home carousel, Team carousel, Team roles, Sponsors medals
* Apply tabs
* Navbar hamburger and close icons
* Member cards 
* Accordions on course and apply
Also fixed z-index issues with the apply banner being over the navbar on small viewports.
[Notion](https://www.notion.so/Website-Make-Anything-Clickable-a-Button-1440ad723ce180a29baaf8ad535f6caf)
Ensuring that tabbing through the page highlights all clickable elements.
> Website: Make All Interactive Elements Buttons

- backend/src/API/coffeeChatAPI.ts
- backend/src/api.ts
- backend/src/dao/CoffeeChatDao.ts
- backend/src/firebase.ts
- common-types/index.d.ts
- frontend/src/API/CoffeeChatAPI.ts
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsDashboard.tsx
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
- frontend/src/components/Modals/CoffeeChatDetailsModal.tsx
- frontend/src/consts.ts
This PR lists all members who meet a category if there is no submission in that category yet. The members listed won't already have a pending/approved coffee chat with the submitter, and won't be the submitter themselves.
Requires addition of `coffee-chat-bingo-board` collection, with documents formatted like 'fall-2024' to store boards from multiple semesters. Each document has format `category: [{netid: __, name: __}]`
https://github.com/user-attachments/assets/59b66b68-1dda-43df-a04c-54a589d75a4c
https://www.notion.so/Coffee-Chat-Suggestions-for-Categories-with-No-Submissions-13c0ad723ce1804ab3c0d35531f4112b?pvs=4
> Coffee Chat: Suggestions for Categories with No Submissions

- backend/package.json
- backend/scripts/pull-from-idol-images.ts
- yarn.lock
We previously didn't have any image compression logic, which required us to manually compress images when they exceed the limit.
Make the Pull from IDOL Images script compress images to < 300 KB. We can also revisit this if it makes the images too low quality/blurry.
We may consider overwriting the bucket's images with the compressed version, but only if we verify that the quality is not significantly diminished. For now, we should keep the images in the bucket as a source of truth for what the original image looked like.
https://www.notion.so/Website-Compress-Images-in-Pull-from-IDOL-Images-Job-1410ad723ce18056a2f1f224afae14d1?pvs=4
Pull from IDOL Images PR: https://github.com/cornell-dti/idol/pull/729
> Pull from IDOL Images: Compress Images to < 300 KB

- new-dti-website/components/apply/data/applications.json
- new-dti-website/components/team/TeamAbout.tsx
- new-dti-website/components/team/data/roleIcons.json
For the Product/Design/Development/Business icons, we should use the same order as on the “About” page.
Use the order based on number of ppl on each team:
1. Development
2. Design
3. Business
4. Product
https://www.notion.so/New-Website-APPLY-Icons-in-Applications-section-14d0ad723ce180f5be8ed66e0bda6355?pvs=4
> New DTI Website: Make Icon Order in 'Applications' section Consistent

- new-dti-website/src/app/sponsor/page.tsx
This PR addresses comments made about the sponsor page in the recent audit of the website.
* Changed the three features in a row to match the styling found on the course page.
* Fixed the "Become a Sponsor" section
* increased vertical padding
* increased image size
* use more consistent header styling (took from "introducing the team" on the team page)
* fixed text hierarchy 
[Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/DTI-New-Landing-Website?node-id=0-1&node-type=canvas&t=LmR5zT7OWnRtXGUw-0)
[3 features in a row section fix](https://www.notion.so/Idol-FA24-1030ad723ce1804ca825d0ec8972c711?p=14a0ad723ce180baaf29ff419361586b&pm=s)
["Become a sponsor!" section fixes](https://www.notion.so/Idol-FA24-1030ad723ce1804ca825d0ec8972c711?p=14a0ad723ce180c7a9d7d08c14bb8822&pm=s)
3 …
> Website: Sponsor Page Improvements

- new-dti-website/components/apply/ApplyFAQ.tsx
- new-dti-website/src/app/globals.css
For the FAQ accordion [here](https://github.com/cornell-dti/idol/blob/e6b082a57fab1e1e4b414934c169fb5ce5d2caf6/new-dti-website/components/course/DDProjects.tsx#L33), we should use the `<details>` and `<summary>` tags. See this [MDN article for details](https://developer.mozilla.org/en-US/blog/html-details-exclusive-accordions/).
Part of https://github.com/cornell-dti/idol/issues/734
Verify FAQ Accordion looks and behaves the same as before.
> New DTI Website: Use Details/Summary For FAQ Accordion

- new-dti-website/components/apply/ApplicationTimeline.tsx
- new-dti-website/src/app/apply/page.tsx
Before:
After:
https://www.notion.so/New-Website-Only-Show-Banner-When-Applications-Are-Closed-14c0ad723ce18059b0a4fa259b029b8c?pvs=4
https://www.notion.so/New-Website-APPLY-Timeline-tabs-14d0ad723ce18017859ddad112809f55?pvs=4
See screenshots.
> New Website: Apply Page, Reorder Timeline Tabs and Only Show Banner if Application is Closed

- new-dti-website/components/apply/RoleDescription.tsx
- new-dti-website/components/bottom.tsx
Quick PR:
1. Fix the "Learn more" and "How we give back" button links on the home page
2. Select the "Development" button by default on the Apply page role descriptions (since that is the leftmost-positioned role)
https://www.notion.so/14d0ad723ce180b68867ed72b07378f4?pvs=4
https://github.com/user-attachments/assets/fc8917bf-3130-4e43-9d46-048cf9aaf8d6
> New Website: Fix Broken Links and Show Development Role Description First

- .github/workflows/profile-update-notification.yml
- .github/workflows/pull-from-idol-images.yml
- .github/workflows/pull-from-idol.yml
Pull from IDOL and Pull from IDOL Images has been running for a few weeks now. People actually tend to update their profiles more frequently than I had anticipated, and the daily pings from it can get annoying. Also, leads agree that a weekly deploy cycle is fine.
Worst case, we can always manually run these jobs if we have an urgent update that needs to be deployed.
This PR:
- Makes Pull from IDOL, Pull from IDOL Images, and Profile Update Notifications happen Weekly
- Moves IDOL Profile Notifications to be 7 hours before Pull from IDOL (instead of 2 hours), so we have sufficient time to approve the changes
> Bump Cron Times: Weekly instead of Daily, Profile Update Notification Sent Earlier

- new-dti-website/components/apply/ApplicationTimeline.tsx
- new-dti-website/components/apply/ApplyFAQ.tsx
- new-dti-website/components/apply/RoleDescription.tsx
- new-dti-website/components/bottom.tsx
- new-dti-website/components/footer.tsx
- new-dti-website/components/navbar.tsx
- new-dti-website/components/team/MemberGroup.tsx
- new-dti-website/components/team/TeamFooter.tsx
- new-dti-website/src/app/apply/page.tsx
- new-dti-website/src/app/course/page.tsx
- new-dti-website/src/app/initiatives/page.tsx
- new-dti-website/src/app/products/page.tsx
- new-dti-website/src/app/sponsor/page.tsx
Per https://github.com/vercel/next.js/issues/50686, it seems like `next/link` causes a bug where navigating using the back and forward buttons leads to JavaScript bundles being downloaded mysteriously. I haven't gotten a clear answer as to why online, but it seems that removing them and switching out with the native `<a><a/>` tags removes that problem.
Let's remove all instances of `next/link` for now. If we find a proper way to incorporate them we can always add them back.
Repro steps:
On a prior deploy:
1. Start at home page
2. Click on products page
3. Click on DTI Logo to go back to home page
4. repeat 2 and 3 at least 5 times
5. Now hit the back button until you hit a prompt to download a file
On this deploy preview, repeat the same steps, observe that the bug no longer occurs.
> New Website: Remove next/link

- new-dti-website/components/team/MemberGroup.tsx
Quick PR. Preserve whitespace (newlines) in about section.
Before:
> New Website: Preserve Whitespace in About Section

- backend/src/API/coffeeChatAPI.ts
- backend/src/api.ts
- backend/src/dao/CoffeeChatDao.ts
- backend/tests/CoffeeChatAPI.test.ts
- backend/tests/CoffeeChatDao.test.ts
- backend/tests/data/createData.ts
`getCoffeeChatsByUser` is supposed to return coffee chats of a given user, supplied by the email. Looks like we previously only fetched by the requester.
Fetch by email supplied by the request query param.
Added/updated unit tests.
> Coffee Chat: Fix getCoffeeChatsByUser to fetch by Supplied Email

- new-dti-website/src/app/apply/page.tsx
fixes [this ](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce1805bab14fb021c01d950)
|Before|After|
|-|-|
|<img width="1469" alt="Screenshot 2024-12-07 at 6 27 18 PM" src="https://github.com/user-attachments/assets/73a4b6b5-9bb5-4220-8bed-46de201df676">|<img width="1469" alt="Screenshot 2024-12-07 at 6 27 29 PM" src="https://github.com/user-attachments/assets/3606b8ba-5de3-4d76-80f2-c742736a1e51">|
> Apply page: secondary btn styling

- new-dti-website/components/apply/ApplyFAQ.tsx
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce18091ae12e6dcb40809d9)
- made border gray 
- but on hover it becomes black
|State|Before|After|
|-|-|-|
|Default|<img width="1649" alt="Screenshot 2024-12-07 at 6 24 06 PM" src="https://github.com/user-attachments/assets/92140e43-16e4-40a0-8c60-ad306b7bbe77">|<img width="1649" alt="Screenshot 2024-12-07 at 6 23 51 PM" src="https://github.com/user-attachments/assets/3193adb7-f0e5-451c-80e4-b69d4e803e12">|
|Hover|<img width="1649" alt="Screenshot 2024-12-07 at 6 24 12 PM" src="https://github.com/user-attachments/assets/bd35c7d0-99d6-4f4d-9781-e1fad1478a3a">|<img width="1649" alt="Screenshot 2024-12-07 at 6 23 55 PM" src="https://github.com/user-attachments/assets/fe121210-fa99-407e-b926-eb88dc …
> Apply page: FAQ section styling

- new-dti-website/components/bottom.tsx
- new-dti-website/src/app/course/page.tsx
fixes [this](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4#1550ad723ce18072bf79d0d4ac1a9705)
|Before|After|
|-|-|
|<img width="1649" alt="Screenshot 2024-12-07 at 5 36 04 PM" src="https://github.com/user-attachments/assets/b023ee3e-0aaa-414d-9f8a-2956f4c31367">|<img width="1649" alt="Screenshot 2024-12-07 at 5 35 51 PM" src="https://github.com/user-attachments/assets/d72731ff-cd49-4a54-a8c9-e57ad2c55fc9">|
> Home page: used same label styles for text containers

- frontend/src/components/Admin/CoffeeChats/CoffeeChats.tsx
Added parenthesis around netid and made sure dropdown resets properly when going between specific member's bingo board and reviewing all coffee chats. 
https://github.com/user-attachments/assets/b16b4f03-75fa-4c2d-86d0-5be27559409f
> Parenthesis Around Netid and Reseting Dropdown Value

- new-dti-website/components/footer.tsx
[notion ](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5?pvs=4)
|Before|After|
|-|-|
|<img width="905" alt="Screenshot 2024-12-22 at 6 29 49 PM" src="https://github.com/user-attachments/assets/a5a544ed-2719-4697-9b8a-b6c4a78996d8" />|<img width="905" alt="Screenshot 2024-12-22 at 6 29 25 PM" src="https://github.com/user-attachments/assets/7713433a-af0b-4307-9ee9-5c4ba036d3c5" />|
> added hover state to footer social icons

- new-dti-website/components/blob.tsx
- new-dti-website/components/team/MemberDisplay.tsx
- new-dti-website/components/team/MemberGroup.tsx
- new-dti-website/components/team/TeamAbout.tsx
- new-dti-website/components/team/TeamFooter.tsx
- new-dti-website/components/team/data/roles.json
- new-dti-website/src/app/course/page.tsx
- new-dti-website/src/app/globals.css
This PR contains even more team page fixes from the latest leads sync.
[Notion](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5)
Netlify deploy vs. current website.
I cannot figure out how to avoid the weird shifting ... if anyone could help :)
> Website: More Team Page Improvements

- new-dti-website/components/team/data/alumni.json
Add Sophie Zhao, Sophia Pham, Ella Krechmer, Brandon Lee to alumni section (they've been removed from IDOL and the team section already).
> Add Retiring Leads to Alumni Section

- new-dti-website/components/apply/data/applications.json
- new-dti-website/config.json
- Update application link
- Per Megan's request, updating PM role description
> Website: Update product manager role description and application link

- frontend/src/components/Candidate-Decider/ApplicantCredentials.tsx
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/SearchBar.tsx
- frontend/src/utils.test.ts
- frontend/src/utils.ts
After setting up the candidate decider instance for SP25 I noticed that all the resumes were inaccessible due to a broken URL. After some testing, it looks like Google docs links are case sensitive, hence this small PR.
I've also included some small changes that were requested last semester by leads:
- 1-indexed dropdowns on the candidate search bar and candidate ID selector
- github, linkedin, resume, and portfolio links now open in a new tab 
N/A
Testing was done manually to:
- ensure that parsed resume URLs now work properly
- check that other credential headers that contain URLs still work
- verify that the correct applicants are still rated despite new 1-indexed display text
> fix candidate decider google docs links, other improvements requested from leads

- backend/src/API/coffeeChatAPI.ts
- backend/src/consts.ts
- backend/src/types/DataTypes.d.ts
- backend/tests/CoffeeChatAPI.test.ts
- backend/tests/data/createData.ts
- common-types/index.d.ts
- frontend/src/components/Admin/CoffeeChats/CoffeeChats.tsx
- frontend/src/components/Forms/CoffeeChatsForm/CoffeeChatsForm.tsx
This PR updates the bingo board for spring 2025. 
* Updated the bingo board. The board is still saved as a constant, but it will change with an upcoming PR.
* Updated autochecker to check "is an advisor" and "is a newbie". Everything else must be manually checked by the C&I lead until we obtain the data from the category form.
* Added an isArchived field for all past coffee chats. New coffee chats should have it set to false.
[Notion](https://www.notion.so/Idol-SP25-1890ad723ce180a19f3ff99268d34e53?p=1900ad723ce1809da802c767149da395&pm=s)
Tested the new bingo board such that it only displays unarchived chats, members could submit, and autocheck works.
https://github.com/user-attachments/assets/436c75da-dab1-49f5-9e14-c910de43ce02
`CoffeeChat` and `DBCoffeeChat` types have been updated and …
> IDOL: Update coffee chat bingo board for SP25

- new-dti-website/src/app/apply/page.tsx
- new-dti-website/src/app/course/page.tsx
- new-dti-website/src/app/initiatives/page.tsx
- new-dti-website/src/app/page.tsx
- new-dti-website/src/app/products/page.tsx
- new-dti-website/src/app/sponsor/page.tsx
- new-dti-website/src/app/team/page.tsx
- new-dti-website/src/hooks/useTitle.ts
The DTI website lacked titles, so all pages were just the URL.
> Website: Add meta titles

- .github/workflows/ci-build.yml
- .github/workflows/pull-from-idol-images.yml
- .github/workflows/pull-from-idol.yml
- .github/workflows/tec-request-notification.yml
This PR bumps the deprecated v1 of `actions/cache` to v4 as prescribed in this [GitHub blog post](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down), which has prevented previous PRs from building.
If this PR builds lol
> Bump actions/cache to v4

- backend/src/API/interviewSchedulerAPI.ts
- backend/src/api.ts
- backend/src/dao/InterviewSchedulerDao.ts
- backend/src/dao/InterviewSlotDao.ts
- backend/src/firebase.ts
- backend/src/types/DataTypes.d.ts
- backend/tests/InterviewSchedulerDao.test.ts
- backend/tests/data/createData.ts
- common-types/index.d.ts
- frontend/src/components/Common/FirestoreDataProvider.tsx
This PR adds the interview scheduler backend, adding CRUD operations for interview slots and interview schedulers. Some endpoints are duplicated for applicants and IDOL members for permission. Data sent back to applicants should be censored. Updating interview slots should be done transactionally to prevent overwritten data.
Unit tests in `InterviewSchedulerDao.test.ts`.
See the two new Firebase collections
> Interview Scheduler Backend

- new-dti-website/components/navbar.tsx
[figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1294-1572&p=f&t=51d4oYxL0O06amCX-11)
IDOL site giving day changes
made "Sponsor" link red to bedazzle it
made "Apply" a white button so that it doesn't look weird being a link next to "Sponsor"
made same changes for mobile too (and i left-aligned links for readability)
|-|-|-|
|Desktop|<img width="1557" alt="Screenshot 2025-02-22 at 3 54 46 PM" src="https://github.com/user-attachments/assets/c6354576-1fda-45a6-aafb-de33d37c847a" />|<img width="1557" alt="Screenshot 2025-02-22 at 3 54 56 PM" src="https://github.com/user-attachments/assets/00310947-c09f-4458-bfdb-427b8d136ac1" />|
|Mobile|<img width="415" alt="Screenshot 2025-02-22 at 3 55 24 PM" …
> Giving day: navbar updates to "Sponsor" and "Apply"

- new-dti-website/components/navbar.tsx
i notice the navbar didn't show an underline under the currently selected page. this is probably a regression from [my PR here](https://github.com/cornell-dti/idol/pull/853)
- added underline back when the item is selected (only on links, not on the Apply/Sponsor buttons)
|-|-|-|
|Desktop|<img width="1341" alt="Screenshot 2025-02-28 at 10 01 30 PM" src="https://github.com/user-attachments/assets/72f289b9-dffc-4e0f-83c2-3a938b0d4f53" />|<img width="1341" alt="Screenshot 2025-02-28 at 10 00 50 PM" src="https://github.com/user-attachments/assets/b22c0c29-8e80-466a-9be1-db9b08c647fd" />|
|Mobile|<img width="394" alt="Screenshot 2025-02-28 at 10 02 09 PM" src="https://github.com/user-attachments/assets/f7f9879b-6759-4cd6-affc-197faa0f8336" />|<img width="394" alt="Screenshot …
> [Giving day] fixed navbar selected item underline bug

- new-dti-website/components/bottom.tsx
- new-dti-website/src/app/globals.css
james spokes requested this lmao
also for code cleanliness replaced the hardcoded values in `bottom.tsx` with the CSS color variables
|-|-|-|
|Contrast levels|<img width="490" alt="Screenshot 2025-02-28 at 9 55 25 PM" src="https://github.com/user-attachments/assets/8805b2da-13ef-4be8-bb56-00475f2103d7" />|<img width="490" alt="Screenshot 2025-02-28 at 9 55 39 PM" src="https://github.com/user-attachments/assets/0671e9e5-d523-4689-83bb-32e37eb4e70c" />|
|Home page feature sections|<img width="1288" alt="Screenshot 2025-02-28 at 9 53 39 PM" src="https://github.com/user-attachments/assets/e8d744a3-02e4-47fb-9f40-8fdd9dbbee2d" />|<img width="1288" alt="Screenshot 2025-02-28 at 9 53 31 PM" src="https://github.com/user-attachments/assets/7932c6fb-26c7-44d3-ae45-d3c42592efa2" />| …
> [Giving Day] Changed secondary text color

- frontend/public/sample_interview_scheduler_input.csv
- frontend/src/API/InterviewSchedulerAPI.ts
- frontend/src/components/Admin/AdminInterviewScheduler/AdminInterviewScheduler.module.css
- frontend/src/components/Admin/AdminInterviewScheduler/AdminInterviewScheduler.tsx
- frontend/src/components/Modals/InterviewSchedulerDeleteModal.tsx
- frontend/src/pages/admin/index.tsx
- frontend/src/pages/admin/interview-scheduler.tsx
- frontend/src/utils.ts
This PR adds the admin view of the interview scheduler tool. Admins are allowed to handle all basic CRUD operations for an interview scheduler instance. Applicants are specified via a CSV file. Instances can be closed to prevent further updates on signing up. 
https://github.com/user-attachments/assets/07bdd308-a3dc-45e1-be53-fb7ce8a3baab
> Interview Scheduler Admin View

- backend/src/dao/InterviewSchedulerDao.ts
Added docs to InterviewSchedulerDao
> interview scheduler dao documentation

- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.module.css
- frontend/src/components/Admin/TeamEvent/TeamEventDashboard.tsx
- frontend/src/components/Forms/TeamEventCreditsForm/TeamEventCreditsForm.tsx
- frontend/src/utils.ts
I added a toggleable view that allows admins to track TEC credits across different periods.
Verified that toggling the new setting correctly switches between total TEC view and period-based TEC view.
Ensured that period-based TEC calculations display accurate credit requirements for each member.
Checked that the notify button correctly reflects members who have not met their TEC requirements per period.
https://github.com/user-attachments/assets/a37ec563-131a-4112-9d32-49c5b6cdbd3c
I still need to update the email message that goes out to members who haven't completed their TEC for the current period as currently the message is the same as the one that tells them they haven't competed enough TEC for the semester. 
Also I'm not sure how the policy should affect leads? Are they required to …
> Admin TEC Dashboard by Period

- frontend/src/components/Candidate-Decider/ApplicantCredentials.module.css
- frontend/src/components/Candidate-Decider/ApplicantCredentials.tsx
- frontend/src/components/Candidate-Decider/CandidateDecider.module.css
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/GlobalProgressPanel.tsx
- frontend/src/components/Candidate-Decider/LocalProgressPanel.tsx
- frontend/src/components/Candidate-Decider/ProgressPanel.module.css
- frontend/src/components/Candidate-Decider/ResponsesPanel.tsx
- frontend/src/pages/App.css
As part of an refresh of our internal tools, we're redesigning the IDOL Candidate Decider based on my new [figma mocks here](https://www.figma.com/design/qHNMOp6rrIFMv1wBXsVtYZ/SP25-IDOL-Candidate-Decider-Tool?node-id=122-1577&t=LZFXidMfUZKVlQcB-11).
This first PR is focused on moving all the components around to fit the new layout of the page. 
- First, I removed a few things:
- Removed the Ratings statistics (we don't want to show this anymore for bias reasons)
- Removed Global progress (we already have the "My progress" progress bar)
- Removed the "Show other people's votes" (we don't want this because of bias)
- Removed Candidate ID dropdown (we already have navigation with the main dropdown)
- Changed the layout of several components:
- Clearly defined a left and right column 
- …
> Clement candidate decider layout change

- new-dti-website-redesign/eslint.config.mjs
- new-dti-website-redesign/postcss.config.mjs
- new-dti-website/components/initiatives/InitiativeDisplay.tsx
For some reason, some text on the Initiatives page turns monospaced on mobile (????)
I think the `import { Inter } from 'next/font/google';` is also causing issues with my other [PR](https://github.com/cornell-dti/idol/pull/909) – specifically, it seems to [make the deploy fail](https://app.netlify.com/sites/cornelldti-idol/deploys/67f766dfc340750008ba5597).
- format fixes
- removed `Inter` font import – this should be OK since I think we're already setting the font in `new-dti-website/src/app/layout.tsx`
- Also removed the super weird conditional font family rendering for those `<p>` tags lol
- removed other unused code too
|Before|After|
|-|-|
|<img width="556" alt="Screenshot 2025-04-12 at 12 39 22 AM" src="https://github.com/user-attachments/assets/92cfb730-63b4-4a0d-bfee-22e360435b5a" …
> [DTI site] Removed `Inter` font import & mobile monospaced bug

- frontend/src/components/Candidate-Decider/ApplicantCredentials.module.css
- frontend/src/components/Candidate-Decider/ApplicantCredentials.tsx
- frontend/src/components/Candidate-Decider/CandidateDecider.module.css
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/LocalProgressPanel.tsx
- frontend/src/components/Candidate-Decider/ResponsesPanel.module.css
- frontend/src/components/Candidate-Decider/ResponsesPanel.tsx
- frontend/src/pages/App.css
- Part of Figma [designs here](https://www.figma.com/design/qHNMOp6rrIFMv1wBXsVtYZ/SP25-IDOL-Candidate-Decider-Tool?node-id=122-1577&t=p0uhtqriGHwRLsGt-11)
- Styling:
- Several CSS changes to padding, border, spacing
- Created new typography stylings for `h1 - h4` and `p`
- "See applicant name" switch
- Essentially I moved this component inside the `ApplicantCredentials` file so that it could be better controlled for styling purposes
- To make this work, some other misc changes like lifting `seeApplicantName` state up
- And also passing some of the other props from `CandidateDecider` (original location) to `ApplicantCredentials` (new desired location)
|Before|After|
|-|-|
|<img width="1855" alt="Screenshot 2025-04-10 at 2 07 33 AM" …
> [Cand decider] Typography updates & checkbox state refactoring

- frontend/src/components/Candidate-Decider/ApplicantCredentials.tsx
- frontend/src/components/Candidate-Decider/CandidateDecider.module.css
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/ResponsesPanel.tsx
- frontend/src/components/Common/Switch/Switch.module.css
- frontend/src/components/Common/Switch/Switch.tsx
- Created new `<Switch>` component
- Added styling
- Removed old `<Checkbox>` component
- [Based off of Figma designs](https://www.figma.com/design/qHNMOp6rrIFMv1wBXsVtYZ/SP25-IDOL-Candidate-Decider-Tool?node-id=122-471&m=dev)
| X | Before | After |
|-|-|-|
|Default|<img width="334" alt="def bef" src="https://github.com/user-attachments/assets/32c9f262-2fa3-46fe-bc6f-7ce5f947bc40" />|<img width="334" alt="def aft" src="https://github.com/user-attachments/assets/4bb4c2e5-dd02-4d97-a2eb-7babd87f57fb" />|
|Hover|<img width="334" alt="hov bef" src="https://github.com/user-attachments/assets/f7c786b2-b48f-422a-ba8e-18404e1443f5" />|<img width="334" alt="hov aft" src="https://github.com/user-attachments/assets/dde7d91f-f8c3-4db4-a965-01854fcb4c09" />|
|Active|<img width="334" alt="act bef" …
> [Cand decider] New `<Switch>` component

- new-dti-website-redesign/eslint.config.mjs
- new-dti-website-redesign/package.json
- new-dti-website-redesign/postcss.config.mjs
- new-dti-website-redesign/src/app/components/Button.tsx
- new-dti-website-redesign/src/app/components/IconButton.tsx
- new-dti-website-redesign/src/app/test/page.tsx
- yarn.lock
- New PR in favor of [old one](https://github.com/cornell-dti/idol/pull/904/) because `git rebase` is dumb :(
- Created `<Button>` component
- [Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1336-16568&t=OZU0wfHmAXC81yDx-11)
- Renders either a `<button>` or an `<a>` tag depending on the situation
- has `primary`, `secondary`, and `tertiary` variants
- accepts optional `badge` prop
- Created `<IconButton>` component
- [Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1336-16568&t=OZU0wfHmAXC81yDx-11)
- Renders either a `<button>` or an `<a>` tag depending on the situation
- has `primary`, `secondary`, and `tertiary` variants
- accepts React icon as child
- has `aria-label` prop for …
> [Newer DTI site] New `<Button>` & `<IconButton>` components, imported Lucide icons (v2)

- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Common/Input/Input.module.css
- frontend/src/components/Common/Input/Input.tsx
- Created new `<Input>` component
- It renders an `<input>` or `<textarea>` component accordingly
- You can also specify the height and resize properties of the input
|-|-|-|
|Default|<img width="577" alt="def bef" src="https://github.com/user-attachments/assets/1a7955ec-897a-4ca5-b6e5-298cd782ee2f" />|<img width="577" alt="def aft" src="https://github.com/user-attachments/assets/82de3475-69de-4609-afd0-8133f1636f9e" />|
|Hover|<img width="577" alt="def bef 2" src="https://github.com/user-attachments/assets/653bb926-a349-4cf8-ae45-121f26e91629" />|<img width="577" alt="hov aft" src="https://github.com/user-attachments/assets/88b9ab1d-fd26-4ea2-98ba-85f9e813fa25" />|
|Focus|<img width="577" alt="Screenshot 2025-04-14 at 2 31 01 PM" …
> [Cand decider] New `<Input>` component

- new-dti-website-redesign/src/app/components/Input.tsx
- new-dti-website-redesign/src/app/components/LabeledInput.tsx
- new-dti-website-redesign/src/app/test/page.tsx
- Created new `<Input>` and `<LabeledInput>` components
- `<Input>` supports both `<input>` and `<textarea>` 
- Supports basic accessibility attributes like `id`, `aria-describedby`, and `aria-invalid`
- `<LabeledInput>` adds a `label` and optional `error` prop
- Added these components and all their variants in the `/test` page
|State|Pic|
|-|-|
|Default|<img width="1048" alt="Screenshot 2025-04-15 at 10 02 18 PM" src="https://github.com/user-attachments/assets/79b9e797-8932-47d5-b8cc-a937fbb61134" />|
|Hover|<img width="1048" alt="Screenshot 2025-04-15 at 10 02 25 PM" src="https://github.com/user-attachments/assets/1df25e2b-e0a9-4197-983c-1109455de958" />|
|Focus|<img width="1048" alt="Screenshot 2025-04-15 at 10 02 28 PM" src="https://github.com/user-attachments/assets/c7c444ec-0e87-4c53 …
> [New website] New `<Input>` and `<LabeledInput>` components

- new-dti-website-redesign/src/app/components/CtaSection.tsx
- new-dti-website-redesign/src/app/test-page/page.tsx
- [Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1336-16568&m=dev)
- Created `<CtaSection>` (modeled on `<Hero>`)
- Props for heading, subheading, and links/labels for 2 buttons
- Added it 4 variants (2 buttons, 1 primary button, 1 secondary button, no buttons (on `/test-page`)
|Desktop|Mobile|
|-|-|
|<img width="1189" alt="Screenshot 2025-04-19 at 5 02 07 PM" src="https://github.com/user-attachments/assets/316edf10-e28c-49b2-bce2-981c7de88068" />|<img width="417" alt="Screenshot 2025-04-19 at 5 03 11 PM" src="https://github.com/user-attachments/assets/26983941-3723-439f-a5ec-1bf71897ee7e" />|
- Navigate to `/test-page` and ensure that all 4 variants look good as pictured
- Resize window to ensure that they are responsive
> [New Website] Created `<CtaSection>` component + added to `/test-page`

- new-dti-website-redesign/src/app/test-page/page.tsx
- new-dti-website-redesign/src/components/Hero.tsx
- new-dti-website-redesign/src/components/SectionSep.tsx
- Created `<SectionSep>` component which adds visual decoration/space between sections on a space ([Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1322-2367&m=dev))
- Based on [Figma responsiveness guidelines](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1336-13320&m=dev)
- If `grid` prop is true, renders a decorational grid element that is responsive.
- Fixed a bug with the `<Hero>` section component where the right-most container with the buttons wasn't exactly `1/4` of the page width
https://github.com/user-attachments/assets/dde05fbe-406a-4687-803f-d0fb2617a96f
- go to `/test-page`
- zoom out a bit
- resize window 
- make sure the squares keep their aspect ratio (ie: they are …
> [New Website] Created section separator + grids component

- new-dti-website-redesign/src/app/test-components/page.tsx
- new-dti-website-redesign/src/components/Button.tsx
- new-dti-website-redesign/src/components/CtaSection.tsx
- new-dti-website-redesign/src/components/Hero.tsx
- new-dti-website-redesign/src/components/Tabs.tsx
- Made changes to `<Button>`:
- Refactored into `forwardRef` to support native props better
- Added `role` so that we can differentiate `role="tab"` and the regular `role="button"`
- `<Hero>` and `<CtaSection>` components: made the subheadings more semantic by using `<p>` instead of `<h6>`
- Created `<Tabs>` component that uses `<Button>`
- `label` (str) and `content` (`React.ReactNode`) for the tab label and for the actual children of the tab panel
- Added some logic to support proper keyboard navigation between tabs for accessibility
- Used instances of `<Tabs>` on the `/test-components` page
https://github.com/user-attachments/assets/07dc0386-8d21-476d-8187-7a8a6e2c1ec7
- Head to `/test-components`
- Click the tabs and make sure they change the panel
- Use `tab` on your keyboard, and …
> [New website] Updates to `<Button>`, `<Tabs>` component, heading semantic fixes 

- frontend/src/components/Candidate-Decider/CandidateDecider.module.css
- frontend/src/components/Candidate-Decider/CandidateDecider.tsx
- frontend/src/components/Candidate-Decider/LocalProgressPanel.tsx
- frontend/src/components/Common/ProgressBar/ProgressBar.module.css
- frontend/src/components/Common/ProgressBar/ProgressBar.tsx
- frontend/src/pages/App.css
- Made new `<ProgressBar>` component (started off based on [Figma](https://www.figma.com/design/qHNMOp6rrIFMv1wBXsVtYZ/SP25-IDOL-Candidate-Decider-Tool?node-id=122-938&t=NifeuHr64QogmsBV-11), but then I took a different approach to designing it)
- Also fixed the styling of the adjacent elements
|Before|After|
|-|-|
|<img width="589" alt="Screenshot 2025-04-23 at 1 06 00 AM" src="https://github.com/user-attachments/assets/b5c8feef-d8ff-4cd5-8320-f5411fcd3289" />|<img width="589" alt="Screenshot 2025-04-23 at 1 05 40 AM" src="https://github.com/user-attachments/assets/73fd3c8e-71a9-476c-9b72-0c8412b36ca1" />|
- Head to cand decider
- Make sure all applicants are selected as "Undecided"
- For each candidate, change their status
- Make sure the bar changes width …
> [Cand decider] New `<ProgressBar>` component

- backend/src/API/candidateDeciderAPI.ts
- backend/src/API/interviewStatusAPI.ts
- backend/src/api.ts
- backend/src/dao/InterviewStatusDao.ts
- common-types/index.d.ts
- frontend/src/API/InterviewStatusAPI.ts
- frontend/src/components/Admin/InterviewStatus/AddInterviewStatusForm.tsx
- frontend/src/components/Admin/InterviewStatus/InterviewStatusBase.module.css
- frontend/src/components/Admin/InterviewStatus/InterviewStatusBase.tsx
- frontend/src/components/Admin/InterviewStatus/InterviewStatusDashboard.tsx
- frontend/src/pages/admin/interview-status/index.tsx
This pull request sorts interview statuses into separate instances and adds the ability for users to create brand‐new interview‐status instances. 
* **Feature:**
* Created `InterviewStatusBase` page that sorts applicants into instances.
* Added a “+ New Instance” button below the instance list in `InterviewStatusBase`.
* Implemented `handleNewEmptyInstance()` to prompt the user for a name and create an empty instance with that name.
* Implemented sorting that ensures that the applicants' statuses are always in a consistent order on the dashboard. 
* Added a delete instances endpoint in the InterviewStatusAPI
https://github.com/user-attachments/assets/86a84c25-65a8-4ce2-ba03-fa61edaf6c8a
1. **Test plan**
* Load the base screen: verify the “+ New Instance” button renders below existing …
> Add Instances to Interview Status Dashboard

- new-dti-website-redesign/src/app/test-components/page.tsx
- new-dti-website-redesign/src/components/IconWrapper.tsx
[Figma specs](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1336-16568&m=dev)
Realized that we needed a white colored iconwrapper so added that type (i had forgotten to add it when i created the component initially lol)
- Navigate to `/test-components`
- Scroll down to "Icon wrappers" section
- Ensure that there are 4 icon wrappers
- 2 primary (white colored), 1 default (`64px`) and 1 small (`48px`)
- 2 default (dark gray colored), 1 default (`64px`) and 1 small (`48px`
> [New Website] Added new type to `<IconWrapper>`

- new-dti-website-redesign/src/app/apply/page.tsx
- new-dti-website-redesign/src/app/course/page.tsx
- new-dti-website-redesign/src/app/globals.css
- new-dti-website-redesign/src/app/initiatives/page.tsx
- new-dti-website-redesign/src/app/page.tsx
- new-dti-website-redesign/src/app/products/page.tsx
- new-dti-website-redesign/src/app/sponsor/page.tsx
- new-dti-website-redesign/src/app/team/page.tsx
- new-dti-website-redesign/src/components/Footer.tsx
- Added skeleton sections for each page (just the title) so its easier for ppl to know what section goes where
- Removed old `<section>`s
- Minor styling border changes on footer
- Also added `<CtaSection>` and `<SectionSep>` components on the page 
- Navigate to each page in the navbar (Home, Team, Products, Course, Initiatives, Sponsor, Apply)
- Make sure they have temporary placeholder sections in accordance [with the Figma](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/SP25-Cornelldti.org-Website-Revamp?node-id=1325-12127&t=bdZBunMNsB3Opr1d-11)
- Make sure each page has a Cta section (the section with "Ready to join?" and 2 buttons)
https://github.com/user-attachments/assets/bdc82e6b-0c1e-46de-9611-666ac3f30399
> [New Website] Pages skeleton section

- new-dti-website-redesign/src/app/layout.tsx
- new-dti-website-redesign/src/components/Button.tsx
- new-dti-website-redesign/src/components/Layout.tsx
- new-dti-website-redesign/src/components/Navbar.tsx
- The current way of showing which page you were currently on in the navbar involved just a white underline, which wasn't very visible. it also didn't animate when you changed page, which made it kinda choppy
- This new design uses a pill `<span>` rendered independently of the link. It also uses `useLayoutEffect` to smoothly animate between each page
- For stylistic reasons, the pill highlight should be the same size as the "Apply" button. So I customized the `<Button>` component a bit to add a `small` prop, which is used in `<Navbar>`
- I also had to move `<Navbar>` to the root `layout.tsx` page so that the highlight animation persists across pages and doesn't reset
https://github.com/user-attachments/assets/0c357822-6909-46d5-a0ad-091915ea00f1
- Navigate to each page in navbar
- For all …
> [New Website] Smoothly animation page links in `<Navbar>`

- backend/scripts/shoutout-leaderboard.ts
Shoutout leaderboard script wasn't able to access firebase because it could not read `.env`.
Ran and it now works!
```
Collecting all shoutouts from 2025-04-01 until now...
[
[ 'Andrew Qian (ajq22)', 31 ],
[ 'Clément Rozé (cpr58)', 17 ],
[ 'Olina Zheng (oz36)', 14 ],
...
]
```
> add dontenv to shoutout leaderboard script

- new-dti-website-redesign/src/app/apply/page.tsx
- new-dti-website-redesign/src/app/course/page.tsx
- new-dti-website-redesign/src/app/design-system/components/button/page.tsx
- new-dti-website-redesign/src/app/globals.css
- new-dti-website-redesign/src/app/initiatives/page.tsx
- new-dti-website-redesign/src/app/page.tsx
- new-dti-website-redesign/src/app/products/page.tsx
- new-dti-website-redesign/src/app/sponsor/page.tsx
- new-dti-website-redesign/src/app/team/page.tsx
- new-dti-website-redesign/src/components/Button.tsx
- new-dti-website-redesign/src/components/CtaSection.tsx
- new-dti-website-redesign/src/components/Footer.tsx
- new-dti-website-redesign/src/components/Hero.tsx
- Added a `transparent` variant to `<Button>`, and update the design system library to show the change
- Changed the `<CtaSection>` component to include a full bleed background image (similar to the `<Hero>`)
- Some colorstylistic changes to `<Footer>`
|-|-|-|
|CTA Section|<img width="1505" alt="Screenshot 2025-05-22 at 12 20 35 AM" src="https://github.com/user-attachments/assets/6b298ab2-86b5-4ac1-b10f-f618c9571a61" />|<img width="1505" alt="Screenshot 2025-05-22 at 12 21 02 AM" src="https://github.com/user-attachments/assets/bf7bd594-e5df-42fc-a5a6-9389ee6c9566" />
|Footer|<img width="1503" alt="Screenshot 2025-05-22 at 12 20 13 AM" src="https://github.com/user-attachments/assets/288cc9ac-b78b-48e9-ba45-695678fb513d" />|<img width="1503" alt="Screenshot 2025-05-22 at 12 …
> [New Website] New `<Button>` variant, `<CtaSection>` changes, `<Footer>` changes

- new-dti-website-redesign/src/app/design-system/PageLayout.tsx
- new-dti-website-redesign/src/app/layout.tsx
- new-dti-website-redesign/src/app/page.tsx
- new-dti-website-redesign/src/components/Banner.tsx
- new-dti-website-redesign/src/components/Button.tsx
- new-dti-website-redesign/src/components/Layout.tsx
- new-dti-website-redesign/src/components/Navbar.tsx
- Made `<Banner>` flushed top to the navbar
- Fixed bug where you could scroll on rest of page when mobile navbar was open
- Added `id`s to `<main>`
- added "Skip to main content" links
https://github.com/user-attachments/assets/9a52fa39-2e42-4320-8920-1019bfac71a5
It's a little technical but here are some instructions
- Open `localhost:3000`
- Press `tab`
- Ensure that the "Skip to main content" link is visible
- Press `tab` a few times 
- Ensure that you're able to navigate around the links **in the navbar** (eg: logo, Team, Products, Course, etc.)
- Reload the page and press `tab` once again
- Now click `enter`
- Ensure that when you press `tab` again, you skip over all the links in the navbar. 
- The first focused element should be the white CTA button in the hero section (eg: "Apply …
> [New Website] Mobile nav & banner polish, added "Skip to main" link

- new-dti-website-redesign/package.json
- yarn.lock
ESlint was not properly linting due to dependency issues introduced in `new-dti-website-redesign`. This caused more linting errors in CI that usual. Downgrading to the version supported in root `package.json` fixed it.
Confirm that eslint lints on VSCode when writing bad code.
> downgrade eslint version

- new-dti-website-redesign/src/app/team/TeamDisplay.tsx
- new-dti-website-redesign/src/app/team/WhoWeAre.tsx
- new-dti-website-redesign/src/app/team/page.tsx
- new-dti-website-redesign/src/components/Tabs.tsx
Fixed some issues from Notion:
- Doesn't wrap "Full Team" to 2 lines on the tabs anymore
- changes "Development" label to "Dev" on certain screen sizes
- Transition delay on pie chart hovering (applies to role legend as well)
- Scrolls down to "Introducing the team" section when clicking "Meet the team"
[Tabs](https://www.notion.so/23f0ad723ce18020afe9eca59fefd1ed?v=23f0ad723ce180e3961e000c13e00fe0&p=2440ad723ce180109caaf6e0654dca63&pm=s)
[Pie Chart](https://www.notion.so/23f0ad723ce18020afe9eca59fefd1ed?v=23f0ad723ce180e3961e000c13e00fe0&p=23f0ad723ce180e28d09d84dec39ef51&pm=s)
[Scrolling](https://www.notion.so/23f0ad723ce18020afe9eca59fefd1ed?v=23f0ad723ce180e3961e000c13e00fe0&p=2440ad723ce18004a8c3fdad1d0b620a&pm=s)
> [New Website] Team Page various fixes

- new-dti-website-redesign/src/components/TeamCard.tsx
- new-dti-website-redesign/src/utils/memberUtils.ts
Incubator members' subteam was not being properly displayed. Furthermore, products with no links were being hyperlinked to the team website (e.g. Lead, CU Raise). This PR fixes both bugs.
Verify incubator shows up for incubator members.
Verify products with no links do not link to the team page anymore.
> add incubator, remove product redirects

- frontend/src/components/Admin/InterviewStatus/InterviewStatusDashboard.tsx
- Added a summary row to bottom of dashboard table listing how many applicants are accepted for each round
[Edit application dashboard](https://www.notion.so/FA25-Roadmap-2410ad723ce18141927bea8c5860f4ab?p=2410ad723ce181ef8c39f9602396c0c8&pm=s)
- Go to Interview Status Dashboard
- Add applicants with different statuses
- Check that the summary row at the bottom of table updates accordingly
- Filter by different rounds/applicants and check updated counts
> add accepted applicant summary to app dashboard

- frontend/src/components/Interview-Scheduler/InterviewScheduler.tsx
- frontend/src/components/Interview-Scheduler/SchedulingCalendar.tsx
- frontend/src/components/Interview-Scheduler/SlotHooks.tsx
To provide better visibility for interview scheduler, this PR adds different displays. This facilitates easier tracking of unfulfilled time slots. Previously, it just displayed the start time of the slot. Now, leads can choose to see three extra display options.
* Leads: displaying the name of the lead assigned to the slot.
* Members: displaying the name of the member(s) assigned to the slot, joined by comma.
* Applicant: displaying the name of the applicant.
Member view:
Applicant view:
Lead view:
> add different displays for interview scheduler calendar

- frontend/src/components/Admin/InterviewStatus/InterviewStatusDashboard.tsx
This pull request fixes a minor bug where the Interview Status Dashboard only displayed results matching _all_ selected filters instead of _any_.
1. Apply multiple filters in the Interview Status Dashboard.
2. Verify that results include instances matching _any_ of the selected filters.
3. Confirm that results update correctly when filters are added or removed.
> Fix Filter Bug for Interview Status Dashboard
